import csv
import json
import os
from pathlib import Path

ROOT = Path("D:/InSynBio-AI-Research/Antibody_Engineer_Suite")
WIKI_DIR = ROOT / "internal_wiki"
ATLAS_DIR = WIKI_DIR / "atlas"

# Data Sources
SEQ_FILE = ROOT / "data/thera_sabdab/out/confirmed70_sequences_full.csv"
GERMLINE_ADA_FILE = ROOT / "data/thera_sabdab/out/confirmed70_human_humanized_germline_ada.csv"
MASTER_ADA_FILE = ROOT / "data/immunogenicity_knowledge_base/master/ada_master_136_curated.csv"

def load_csv(path):
    if not path.exists():
        print(f"Warning: {path} not found.")
        return []
    with open(path, mode='r', encoding='utf-8') as f:
        return list(csv.DictReader(f))

def main():
    if not ATLAS_DIR.exists():
        ATLAS_DIR.mkdir(parents=True)

    print("Loading data sources...")
    seq_data = load_csv(SEQ_FILE)
    germline_ada_data = load_csv(GERMLINE_ADA_FILE)
    master_ada_data = load_csv(MASTER_ADA_FILE)

    # Index by antibody name
    atlas = {}

    # 1. Base sequences
    for row in seq_data:
        name = row['antibody_name']
        atlas[name] = {
            "name": name,
            "format": row['thera_format'],
            "arm1_heavy": row['arm1_heavy_aa'],
            "arm1_light": row['arm1_light_aa'],
            "arm2_heavy": row.get('arm2_heavy_aa', ''),
            "arm2_light": row.get('arm2_light_aa', ''),
            "vhh1": row.get('vhh1_aa', ''),
            "vhh2": row.get('vhh2_aa', ''),
            "vhh3": row.get('vhh3_aa', ''),
            "notes": row['sequence_notes'],
            "sources": row['sequence_sources']
        }

    # 2. Germline and ADA %
    for row in germline_ada_data:
        name = row['antibody_name']
        if name in atlas:
            atlas[name].update({
                "genetics_class": row['thera_genetics_class'],
                "ada_pct": row['ada_first_pct'],
                "ada_display": row['ada_value_display'],
                "vh_germline": row['vh_germline'],
                "vl_germline": row['vl_germline'],
                "vh_family": row['vh_family'],
                "vl_family": row['vl_family']
            })

    # 3. Master ADA details (targets, indications)
    for row in master_ada_data:
        name = row.get('name') or row.get('antibody_name')
        if name in atlas:
            atlas[name].update({
                "targets": row.get('targets', ''),
                "indications": row.get('indications', ''),
                "company": row.get('company', ''),
                "phase": row.get('phase', '')
            })

    # Save aggregated JSON
    atlas_json_path = ROOT / "data/clinical_kb/Antibody_Atlas_1142_Aggregated.json"
    atlas_json_path.parent.mkdir(parents=True, exist_ok=True)
    with open(atlas_json_path, 'w', encoding='utf-8') as f:
        json.dump(list(atlas.values()), f, indent=2, ensure_ascii=False)
    print(f"Aggregated data saved to {atlas_json_path}")

    # Generate Markdown profiles
    print(f"Generating {len(atlas)} antibody profiles in {ATLAS_DIR}...")
    for name, data in atlas.items():
        safe_name = name.replace("/", "_").replace(" ", "_")
        md_path = ATLAS_DIR / f"{safe_name}.md"
        
        # Build sequence block
        seq_block = ""
        if data.get('arm1_heavy'):
            seq_block += f"### Arm 1 Heavy\n```\n{data['arm1_heavy']}\n```\n"
        if data.get('arm1_light'):
            seq_block += f"### Arm 1 Light\n```\n{data['arm1_light']}\n```\n"
        if data.get('vhh1'):
            seq_block += f"### VHH 1\n```\n{data['vhh1']}\n```\n"

        content = f"""# Antibody Profile: {name}

## 📊 Quick Info
*   **Format**: {data.get('format', 'N/A')}
*   **Genetics**: {data.get('genetics_class', 'N/A')}
*   **Target(s)**: {data.get('targets', 'N/A')}
*   **Company**: {data.get('company', 'N/A')}
*   **Phase**: {data.get('phase', 'N/A')}

## 🧬 Germline Analysis
*   **VH Germline**: {data.get('vh_germline', 'N/A')} ({data.get('vh_family', 'N/A')})
*   **VL Germline**: {data.get('vl_germline', 'N/A')} ({data.get('vl_family', 'N/A')})

## 🛡️ Clinical Immunogenicity
*   **Reported ADA**: {data.get('ada_pct', 'N/A')}%
*   **Clinical Context**: {data.get('ada_display', 'N/A')}

## 📝 Sequences
{seq_block}

## 🔗 Metadata
*   **Sources**: {data.get('sources', 'N/A')}
*   **Notes**: {data.get('notes', 'N/A')}

---
*Generated by InSynBio Atlas Engine on 2026-04-11*
"""
        with open(md_path, 'w', encoding='utf-8') as f:
            f.write(content)

    print("Wiki generation complete.")

if __name__ == "__main__":
    main()
