"""
ADC Design Report Generator
============================
Renders ADCProposal lists into structured Markdown and JSON reports,
following the InSynBio CURSOR_REPORT_ENGINE_V3 conventions.

Usage
-----
    from core.adc_design.adc_design_report import ADCDesignReport
    report = ADCDesignReport(proposals, query_params)
    report.write_markdown("output/adc_design_proposal.md")
    report.write_json("output/adc_design_proposal.json")
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from .adc_decision_engine import ADCProposal


class ADCDesignReport:
    """Generates a structured ADC design proposal report."""

    def __init__(
        self,
        proposals: list[ADCProposal],
        query: dict[str, Any],
    ):
        self.proposals = proposals
        self.query = query
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    def to_markdown(self) -> str:
        lines = [
            "# ADC Intelligent Design Proposal",
            "",
            f"**Generated**: {self.timestamp}  ",
            f"**Engine**: InSynBio ADC Decision Engine v1.0  ",
            "",
            "## Query Parameters",
            "",
            f"| Parameter | Value |",
            f"|-----------|-------|",
        ]
        for k, v in self.query.items():
            lines.append(f"| {k} | {v} |")

        lines += ["", "---", "", "## Ranked Design Proposals", ""]

        if not self.proposals:
            lines.append("*No compatible ADC designs found for the given parameters.*")
            return "\n".join(lines)

        for p in self.proposals:
            score_pct = f"{p.score_total * 100:.1f}%"
            lines += [
                f"### Rank #{p.rank} — {p.target_antigen} + {p.payload_name} (Score: {score_pct})",
                "",
                "| Component | Recommendation |",
                "|-----------|---------------|",
                f"| Target Antigen | **{p.target_antigen}** ({p.antigen_tier}) |",
                f"| Binder Format | {p.binder_format} |",
                f"| Linker | {p.linker_name} ({p.linker_type}) |",
                f"| Payload | **{p.payload_name}** ({p.payload_class}) |",
                f"| Conjugation | {p.conjugation_method} |",
                f"| DAR Range | {p.dar_range[0]} – {p.dar_range[1]} |",
                f"| Bystander Effect | {'Yes' if p.bystander_effect else 'No'} |",
                "",
                "**Score Breakdown**",
                "",
                "| Dimension | Score |",
                "|-----------|-------|",
            ]
            for dim, val in p.score_breakdown.items():
                bar = "█" * int(val * 10) + "░" * (10 - int(val * 10))
                lines.append(f"| {dim.replace('_', ' ').title()} | {bar} {val:.2f} |")

            lines += ["", f"**Rationale**: {p.rationale}", ""]

            if p.precedent_programs:
                lines.append(
                    f"**Precedent Programs**: {', '.join(p.precedent_programs)}"
                )
            lines.append(f"**Differentiation**: {p.differentiation_notes}")

            if p.safety_warnings:
                lines += ["", "⚠ **Safety Warnings**", ""]
                for w in p.safety_warnings:
                    lines.append(f"- {w}")

            if p.fto_alerts:
                lines += ["", "📋 **FTO / Patent Alerts**", ""]
                for a in p.fto_alerts:
                    lines.append(f"- {a}")

            lines += ["", "---", ""]

        lines += self._summary_section()
        return "\n".join(lines)

    def _summary_section(self) -> list[str]:
        lines = [
            "## Executive Summary",
            "",
            f"The engine evaluated **{len(self.proposals)}** ADC design configurations "
            f"for **{self.query.get('disease_subtype', 'the specified indication')}**.",
            "",
        ]

        if self.proposals:
            top = self.proposals[0]
            lines += [
                f"**Top Recommendation**: {top.target_antigen} + {top.payload_name} "
                f"via {top.conjugation_method} (DAR {top.dar_range[0]}–{top.dar_range[1]})",
                "",
            ]

            all_warnings = set()
            for p in self.proposals:
                all_warnings.update(p.safety_warnings)
            if all_warnings:
                lines += ["**Key Safety Considerations Across All Designs**:", ""]
                for w in sorted(all_warnings):
                    lines.append(f"- {w}")

        lines += [
            "",
            "---",
            f"*Report generated by InSynBio ADC Decision Engine | {self.timestamp}*",
        ]
        return lines

    def to_json(self) -> str:
        return json.dumps(
            {
                "metadata": {
                    "generated": self.timestamp,
                    "engine": "InSynBio ADC Decision Engine v1.0",
                    "query": self.query,
                },
                "proposals": [p.to_dict() for p in self.proposals],
            },
            indent=2,
            ensure_ascii=False,
        )

    def write_markdown(self, path: str | Path) -> Path:
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(self.to_markdown(), encoding="utf-8")
        return p

    def write_json(self, path: str | Path) -> Path:
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(self.to_json(), encoding="utf-8")
        return p
