"""Audit donor vs converted CDR1/CDR2/CDR3 for all 6 CD3 panel samples."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from core.vhh.vhh_scaffold_match_and_craft import _build_vhh_residue_map_and_regions

SAMPLES = {
    "SP34": (
        "DIKLQSGAELARPGASVKMSCKTSGYTFTRYTMHWVKQRPGQGLEWIGYINPSRGYTNYNQKFKDKATLTTDKSSSTAYMQLSSLTSEDSAVYYCARYYDDHYCLDYWGQGTTLTVSS",
        "EVQLVESGGGLIQPGGSLRLSCAVSGYTFTRYTMSWVRQAPGKGLEWVSVINPSRGYTNYNQKFKDRFTISRDNSKNTLYLQMNSLRAEDTAVYYCARYYDDHYSLDYWGQGTMVTVSS",
    ),
    "Teplizumab": (
        "QVQLVQSGGGVVQPGRSLRLSCKASGYTFTRYTMHWVRQAPGKGLEWIGYINPSRGYTNYNQKVKDRFTISRDNSKNTAFLQMDSLRPEDTGVYFCARYYDDHYCLDYWGQGTPVTVSS",
        "EVQLVESGGGLVQPGGSLRLSCAASGYTFTRYTMSWVRQAPGKGLEWVSAINPSRGYTNYNQKVKDRFTISRDNAKNTLYLQMNSLRAEDTAVYYCARYYDDHYSLDYWGQGTLVTVSS",
    ),
    "Visilizumab": (
        "QVQLVQSGAEVKKPGASVKVSCKASGYTFISYTMHWVRQAPGQGLEWMGYINPRSGYTHYNQKLKDKATLTADKSASTAYMELSSLRSEDTAVYYCARSAYYDYDGFAYWGQGTLVTVSS",
        "EVQLVESGGGLVQPGGSLRLSCAASGYTFISYTMSWVRQAPGKGLEWVSAINPRSGYTHYNQKLKDRFTISRDNAKNTLYLQMNSLRAEDTAVYYCARSAYYDYDGFAYWGQGTLVTVSS",
    ),
    "Otelixizumab": (
        "EVQLLESGGGLVQPGGSLRLSCAASGFTFSSFPMAWVRQAPGKGLEWVSTISTSGGRTYYRDSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAKFRQYSGGFDYWGQGTLVTVSS",
        "EVQLVESGGGLVQPGGSLQLSCAASGFTFSSFPMSWVRQAPGKGLEWVSAISTSGGRTYYRDSVKGRFTISRDNAKNTLYLQMNSLRAEDTAVYYCAKFRQYSGGFDYWGQGTLVTVSS",
    ),
    "Foralumab": (
        "QVQLVESGGGVVQPGRSLRLSCAASGFKFSGYGMHWVRQAPGKGLEWVAVIWYDGSKKYYVDSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCARQMGYWHFDLWGRGTLVTVSS",
        "EVQLVESGGGLVQPGGSLRLSCAASGFKFSGYGMYWVRQAPGKGLEWVSEIWYDGSKKYYVDSVKGRFTISRDNAKNTLYLQMNSLRPEDTAVYYCARQMGYWHFDLRGQGTLVTVSS",
    ),
    "OKT3": (
        "QVQLVQSGAEVKKPGASVKVSCKASGYTFTRYTMHWVRQAPGQGLEWIGYINPSRGYTNYNQKFKDRVTMTRDTSTSTVYMELSSLRSEDTAVYYCARYYDDHYCLDYWGQGTLVTVSS",
        "EVQLVESGGGLVQPGGSLRLSCAASGYTFTRYTMSWVRQAPGKGLEWVSAINPSRGYTNYNQKFKDRFTISRDNAKNTLYLQMNSLRAEDTAVYYCARYYDDHYSLDYWGQGTLVTVSS",
    ),
}


def extract_cdrs(seq: str):
    rmap, regions = _build_vhh_residue_map_and_regions(seq)
    out = {}
    ordered = getattr(rmap, "_ordered_rows", [])
    for cdr in ["CDR1", "CDR2", "CDR3"]:
        if cdr not in regions:
            out[cdr] = ("(missing)", (None, None))
            continue
        lo, hi = regions[cdr]
        residues = [aa for (pos, _ins, aa) in ordered if lo <= pos <= hi]
        out[cdr] = ("".join(residues), (lo, hi))
    return out


print(f"{'Sample':<14}{'Region':<7}{'Donor CDR':<22}{'Converted CDR':<22}{'OK?':<8}")
print("-" * 80)
for name, (donor, converted) in SAMPLES.items():
    d = extract_cdrs(donor)
    c = extract_cdrs(converted)
    for cdr in ["CDR1", "CDR2", "CDR3"]:
        ds, drng = d[cdr]
        cs, crng = c[cdr]
        ok = "OK" if ds == cs else "DIFF"
        print(f"{name:<14}{cdr:<7}{ds + ' ' + str(drng):<22}{cs + ' ' + str(crng):<22}{ok:<8}")
    print()
