def extract_vh(prot):
    # Signal peptide for HC is usually MEFGLSWVFLVAILKGVQC (19 aa)
    # VH starts with QVQL or EVQL
    start_motifs = ["QVQL", "EVQL"]
    start_idx = -1
    for m in start_motifs:
        idx = prot.find(m)
        if idx != -1:
            start_idx = idx
            break
    
    # VH ends with WGQGTSVTVSS or WGQGTLVTVSS
    end_motifs = ["WGQGTSVTVSS", "WGQGTLVTVSS"]
    end_idx = -1
    for m in end_motifs:
        idx = prot.find(m)
        if idx != -1:
            end_idx = idx + len(m)
            break
    
    if start_idx != -1 and end_idx != -1:
        return prot[start_idx : end_idx]
    return "Not found"

def extract_vl(prot):
    # Signal peptide for LC is usually MDMRVPAQLLGLLLLWFPGSRC (22 aa)
    # VL starts with DIQM, EIVL, EIVM, or DIVM
    start_motifs = ["DIQM", "EIVL", "EIVM", "DIVM"]
    start_idx = -1
    for m in start_motifs:
        idx = prot.find(m)
        if idx != -1:
            start_idx = idx
            break
            
    # VL ends with FGQGTKVELK or FGQGTKLEIK
    end_motifs = ["FGQGTKVELK", "FGQGTKLEIK"]
    end_idx = -1
    for m in end_motifs:
        idx = prot.find(m)
        if idx != -1:
            end_idx = idx + len(m)
            break
    
    if start_idx != -1 and end_idx != -1:
        return prot[start_idx : end_idx]
    return "Not found"

sequences = {
    "Tanezumab-Chim-DogFR4-HC": "MEFGLSWVFLVAILKGVQCQVQLQESGPGLVKPSETLSLTCTVSGFSLIGYDLNWIRQPPGKGLEWIGIIWGDGTTDYNSAVKSRVTISKDTSKNQFSLKLSSVTAADTAVYYCARGGYWYATSYYFDYWGQGTSVTVSSASTTAPSVFPLAPSCGSTSGSTVALACLVSGYFPEPVTVSWNSGSLTSGVHTFPSVLQSSGLYSLSSMVTVPSSRWPSETFTCNVAHPASKTKVDKPVPKRENGRVPRPPDCPKCPAPEMLGGPSVFIFPPKPKDTLLIARTPEVTCVVVDLDPEDPEVQISWFVDGKQMQTAKTQPREEQFNGTYRVVSVLPIGHQDWLKGKQFTCKVNNKALPSPIERTISKARGQAHQPSVYVLPPSREELSKNTVSLTCLIKDFFPPDIDVEWQSNGQQEPESKYRTTPPQLDEDGSYFLYSKLSVDKSRWQRGDTFICAVMHEALHNHYTQKSLSHSPGK",
    "Tanezumab-Chim-DogFR4-LC": "MDMRVPAQLLGLLLLWFPGSRCDIQMTQSPSSLSASVGDRVTITCRASQSISNNLNWYQQKPGKAPKLLIYYTSRFHSGVPSRFSGSGSGTDFTFTISSLQPEDIATYYCQQEHTLPYTFGQGTKVELKRNDAQPAVYLFQPSPDQLHTGSASVVCLLNSFYPKDINVKWKVDGVIQDTGIQESVTEQDKDSTYSLSSTLTMSSTEYLSHELYSCEITHKSLPSTLIKSFQRSECQRVD",
    "Tanezumab-V1b-DogFR4-HC": "MEFGLSWVFLVAILKGVQCEVQLVESGGDLVKPGGSLRLSCVASGFSLIGYDLNWVRQAPGKGLQWLSIIWGDGTTDYNSAVKSRFTISRDNAKNTLYLQLQSLRAEETAVYYCARGGYWYATSYYFDYWGQGTSVTVSSASTTAPSVFPLAPSCGSTSGSTVALACLVSGYFPEPVTVSWNSGSLTSGVHTFPSVLQSSGLYSLSSMVTVPSSRWPSETFTCNVAHPASKTKVDKPVPKRENGRVPRPPDCPKCPAPEMLGGPSVFIFPPKPKDTLLIARTPEVTCVVVDLDPEDPEVQISWFVDGKQMQTAKTQPREEQFNGTYRVVSVLPIGHQDWLKGKQFTCKVNNKALPSPIERTISKARGQAHQPSVYVLPPSREELSKNTVSLTCLIKDFFPPDIDVEWQSNGQQEPESKYRTTPPQLDEDGSYFLYSKLSVDKSRWQRGDTFICAVMHEALHNHYTQKSLSHSPGK",
    "Tanezumab-V1b-DogFR4-LC": "MDMRVPAQLLGLLLLWFPGSRCEIVLTQSPASLSLSQEEKVTITCRASQSISNNLNWYQQKPGQAPKLLIYYTSRFHSGVPSRFSGSGSGTDFSFTISSLEPEDVAVYYCQQEHTLPYTFGQGTKVELKRNDAQPAVYLFQPSPDQLHTGSASVVCLLNSFYPKDINVKWKVDGVIQDTGIQESVTEQDKDSTYSLSSTLTMSSTEYLSHELYSCEITHKSLPSTLIKSFQRSECQRVD",
    "Tanezumab-V2-DogFR4-HC": "MEFGLSWVFLVAILKGVQCEVQLVESGGDLVKPGGSLRLSCVASGFSLIGYDLNWVRQAPGKGLQWIGIIWGDGTTDYNSAVKSRVTISKDTAKNTFYLQLQSLRAEETAVYYCARGGYWYATSYYFDYWGQGTSVTVSSASTTAPSVFPLAPSCGSTSGSTVALACLVSGYFPEPVTVSWNSGSLTSGVHTFPSVLQSSGLYSLSSMVTVPSSRWPSETFTCNVAHPASKTKVDKPVPKRENGRVPRPPDCPKCPAPEMLGGPSVFIFPPKPKDTLLIARTPEVTCVVVDLDPEDPEVQISWFVDGKQMQTAKTQPREEQFNGTYRVVSVLPIGHQDWLKGKQFTCKVNNKALPSPIERTISKARGQAHQPSVYVLPPSREELSKNTVSLTCLIKDFFPPDIDVEWQSNGQQEPESKYRTTPPQLDEDGSYFLYSKLSVDKSRWQRGDTFICAVMHEALHNHYTQKSLSHSPGK",
    "Tanezumab-V2-DogFR4-LC": "MDMRVPAQLLGLLLLWFPGSRCEIVMTQSPASLSLSQEEKVTITCRASQSISNNLNWYQQKPGQAPKLLIYYTSRFHSGVPSRFSGSGSGTDFSFTISSLEPEDVAVYYCQQEHTLPYTFGQGTKVELKRNDAQPAVYLFQPSPDQLHTGSASVVCLLNSFYPKDINVKWKVDGVIQDTGIQESVTEQDKDSTYSLSSTLTMSSTEYLSHELYSCEITHKSLPSTLIKSFQRSECQRVD",
    "Ranevetmab-Atlas-HC": "MEFGLSWVFLVAILKGVQCEVQLVESGGGLVQPGGSLRLSCVASGFSLTNNNVNWVRQAPGKGLEWVGGVWAGGATDYNSALKSRFTISRDNAKNTVFLQMHSLRSEDTAVYYCARDGGYSSSTLYAMDAWGQGTSVTVSSASTTAPSVFPLAPSCGSTSGSTVALACLVSGYFPEPVTVSWNSGSLTSGVHTFPSVLQSSGLYSLSSMVTVPSSRWPSETFTCNVAHPASKTKVDKPVPKRENGRVPRPPDCPKCPAPEMLGGPSVFIFPPKPKDTLLIARTPEVTCVVVDLDPEDPEVQISWFVDGKQMQTAKTQPREEQFNGTYRVVSVLPIGHQDWLKGKQFTCKVNNKALPSPIERTISKARGQAHQPSVYVLPPSREELSKNTVSLTCLIKDFFPPDIDVEWQSNGQQEPESKYRTTPPQLDEDGSYFLYSKLSVDKSRWQRGDTFICAVMHEALHNHYTQKSLSHSPGK",
    "Ranevetmab-Atlas-LC": "MDMRVPAQLLGLLLLWFPGSRCDIVMTQSPASLSLSQGETVTITCRASEDIYNALAWYQQKPGQAPKLLIYNTDTLHTGVPSRFSGSGSGTDFSLTISSLEPEDVAVYYCQHYFHYPRTFGQGTKVELKRNDAQPAVYLFQPSPDQLHTGSASVVCLLNSFYPKDINVKWKVDGVIQDTGIQESVTEQDKDSTYSLSSTLTMSSTEYLSHELYSCEITHKSLPSTLIKSFQRSECQRVD"
}

for name, seq in sequences.items():
    if "-HC" in name:
        print(f"{name} VH: {extract_vh(seq)}")
    else:
        print(f"{name} VL: {extract_vl(seq)}")
