import pandas as pd


ada_path = "data/immunogenicity_knowledge_base/master/ada_master_328_final_comprehensive.csv"
df = pd.read_csv(ada_path)

updates = {
    "Ebronucimab": {
        "ada_value": "In a phase I randomized, double-blind, placebo-controlled single-dose escalation study in healthy volunteers, 3 ebronucimab-treated subjects tested ADA-positive at least once; ADA incidence among ebronucimab-treated subjects was 12.5% (3/24).",
        "ada_value_display": "12.5% ADA (3/24 ebronucimab-treated healthy volunteers)",
        "ada_first_pct": 12.5,
        "nab_pct": "Not stated",
        "assay_platform": "ADA assessment; platform not stated in retrieved abstract text",
        "pk_efficacy_impact": "Ebronucimab was well tolerated; no specific ADA impact on PK/PD or safety was stated in the retrieved abstract text.",
        "evidence_source": "Circulation/AHA scientific abstract mirrored by R Discovery, Abstract 9318",
        "citation_urls": "https://www.ahajournals.org/doi/10.1161/circ.146.suppl_1.9318; https://discovery.researcher.life/article/abstract-9318-the-safety-pharmacokinetics-pharmacodynamics-and-immunogenicity-of-ebronucimab-in-healthy-volunteers-result-from-a-phase-i-randomized-double-blind-placebo-controlled-single-dose-escalation-study/bffca5f5487b3c7992fe9a071094a563",
        "ada_source_url_primary": "https://discovery.researcher.life/article/abstract-9318-the-safety-pharmacokinetics-pharmacodynamics-and-immunogenicity-of-ebronucimab-in-healthy-volunteers-result-from-a-phase-i-randomized-double-blind-placebo-controlled-single-dose-escalation-study/bffca5f5487b3c7992fe9a071094a563",
        "ada_source_type_curated": "conference_abstract",
        "ada_has_text_evidence": True,
        "ada_source_section": "Abstract Results/Immunogenicity: 3 subjects ADA-positive at least once during the study; incidence of ADAs in ebronucimab-treated subjects was 12.5% (3/24).",
        "verify_note": "Normalized source fields from retrievable abstract text; AHA DOI page returned access restriction but mirrored abstract contained the original text.",
    },
    "Eculizumab": {
        "ada_value": "SOLIRIS immunogenicity was evaluated using two immunoassays. In PNH, antibodies were detected in 3/196 (2%) by ELISA and 5/161 (3%) by ECL; in aHUS, 3/100 (3%) were antibody-positive; in NMOSD, 2/96 (2%) were antibody-positive. Low-positive neutralizing antibody values were seen in 2/161 PNH patients and 1/100 aHUS patients, with none in NMOSD.",
        "ada_value_display": "PNH: 2-3%; aHUS: 3%; NMOSD: 2%",
        "ada_first_pct": 2.0,
        "nab_pct": "PNH 1.2% (2/161); aHUS 1% (1/100); NMOSD 0%",
        "assay_platform": "ELISA and ECL ADA assays; ECL-based neutralizing assay",
        "pk_efficacy_impact": "No apparent correlation of antibody development to clinical response was observed.",
        "evidence_source": "FDA SOLIRIS prescribing information, Section 12.6 Immunogenicity",
        "citation_urls": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/125166s448,761108s038lbl.pdf",
        "ada_source_url_primary": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/125166s448,761108s038lbl.pdf",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 12.6 Immunogenicity: PNH 3/196 (2%) by ELISA and 5/161 (3%) by ECL; aHUS 3/100 (3%); NMOSD 2/96 (2%); low-positive neutralizing antibodies in 2/161 PNH and 1/100 aHUS; no apparent correlation to clinical response.",
        "verify_note": "Replaced '<2%' display with current label indication-specific values.",
    },
    "Efalizumab": {
        "ada_value": "In the NEJM plaque psoriasis trial, anti-efalizumab antibodies developed in 5% of efalizumab-treated subjects; no safety-profile difference was observed between antibody-positive and antibody-negative subjects.",
        "ada_value_display": "5% anti-efalizumab antibodies",
        "ada_first_pct": 5.0,
        "nab_pct": "Not stated",
        "assay_platform": "Anti-efalizumab antibody assessment; platform not stated in retrieved text",
        "pk_efficacy_impact": "No safety-profile difference was observed in subjects with anti-efalizumab antibodies; clinical significance was described as unclear in later review text.",
        "evidence_source": "NEJM efalizumab plaque psoriasis trial; PubMed safety review retained as supplemental source",
        "citation_urls": "https://www.nejm.org/doi/full/10.1056/NEJMoa030002; https://pubmed.ncbi.nlm.nih.gov/16503742/",
        "ada_source_url_primary": "https://www.nejm.org/doi/full/10.1056/NEJMoa030002",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "NEJM safety results: Anti-efalizumab antibodies developed in 5% of treated subjects; safety profile did not differ from antibody-negative subjects.",
        "verify_note": "Normalized to original trial text; PubMed review also states approximately 5%.",
    },
    "Elezanumab": {
        "ada_value": "Across the phase 1 single-ascending-dose and multiple-ascending-dose elezanumab studies, one healthy participant had pre-dose ADA titers and one had post-dose ADA titers after 150 mg SC elezanumab; all MAD participants tested ADA-negative. No apparent PK effect was observed.",
        "ada_value_display": "Treatment-emergent ADA: 2.0% (1/50 treated); detectable ADA including baseline: 4.0% (2/50)",
        "ada_first_pct": 2.0,
        "nab_pct": "Not assayed per protocol because no evidence suggested ADA affected PK",
        "assay_platform": "Validated titer-based electrochemiluminescence bridging immunoassay",
        "pk_efficacy_impact": "No apparent decrease in exposure was observed when positive titers occurred.",
        "evidence_source": "Annals of Neurology / PMC phase 1 elezanumab study",
        "citation_urls": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10100020/; https://pubmed.ncbi.nlm.nih.gov/36093738/",
        "ada_source_url_primary": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10100020/",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity: 2 healthy participants had detectable ADA titers, one pre-dose and one post-dose; all MAD participants tested ADA-negative; NAbs were not assayed because no ADA PK effect was evident.",
        "verify_note": "Kept treatment-emergent 2.0% but corrected NAb field; prior 0.4% neutralizing value was not found in the retrieved article.",
    },
    "Elotuzumab": {
        "ada_value": "Across four clinical studies including ELOQUENT-2, 72/390 (18.5%) EMPLICITI-treated evaluable patients tested positive for treatment-emergent anti-product antibodies by ECL assay; in ELOQUENT-3, 19/53 (36%) tested positive. Neutralizing antibodies were detected post-treatment in 19/299 evaluable patients across the four clinical trials and 2/53 in ELOQUENT-3.",
        "ada_value_display": "18.5% TE anti-product antibodies across four trials; 36% in ELOQUENT-3",
        "ada_first_pct": 18.5,
        "nab_pct": "19/299 across four trials; 2/53 in ELOQUENT-3",
        "assay_platform": "Electrochemiluminescent ADA assay; neutralizing antibody assay in ADA-evaluable samples",
        "pk_efficacy_impact": "Most ADA occurred within the first 2 months and resolved by 2-4 months in most patients; label does not state a clinically adverse efficacy or safety impact in the immunogenicity section.",
        "evidence_source": "FDA EMPLICITI prescribing information, Section 6.2 Immunogenicity",
        "citation_urls": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2018/761035s008lbl.pdf; https://link.springer.com/article/10.1208/s12248-016-0033-9",
        "ada_source_url_primary": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2018/761035s008lbl.pdf",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 6.2 Immunogenicity: 72/390 (18.5%) positive across four studies including ELOQUENT-2; 19/53 (36%) in ELOQUENT-3; neutralizing antibodies in 19/299 and 2/53, respectively.",
        "verify_note": "Replaced mixed 15%/18.5% display with FDA label-confirmed pooled value.",
    },
    "Emapalumab": {
        "ada_value": "GAMIFANT immunogenicity was evaluated by ECLIA. Anti-therapeutic antibodies were detected in 3/64 (5%) subjects after treatment; treatment-emergent ATAs were detected in 1/33 (3%) patients in the primary HLH clinical trial and had neutralizing ability.",
        "ada_value_display": "5% ATA overall (3/64); 3% treatment-emergent ATA in primary HLH trial (1/33)",
        "ada_first_pct": 5.0,
        "nab_pct": "1/33 primary HLH trial patient had neutralizing ability",
        "assay_platform": "Electrochemiluminescence-based immunoassay (ECLIA)",
        "pk_efficacy_impact": "No evidence of altered safety or efficacy profile was identified in primary HLH patients who developed antibodies.",
        "evidence_source": "DailyMed/FDA GAMIFANT prescribing information, Section 6.2 Immunogenicity",
        "citation_urls": "https://fda.report/DailyMed/a865e0ef-8685-4f69-8838-648c4f3bab47; https://www.drugs.com/pro/gamifant.html",
        "ada_source_url_primary": "https://fda.report/DailyMed/a865e0ef-8685-4f69-8838-648c4f3bab47",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 6.2 Immunogenicity: ATAs detected in 3/64 (5%); treatment-emergent ATAs in 1/33 (3%) primary HLH patients, with neutralizing ability; no altered safety or efficacy profile identified.",
        "verify_note": "Corrected prior 10% value; retrieved label supports 5% overall and 3% primary-HLH treatment-emergent incidence.",
    },
    "Emicizumab": {
        "ada_value": "In HAVEN 1-4, emicizumab was associated with antidrug antibodies in 5.1% of patients (34/668). Most patients did not have changed plasma concentrations or increased bleeding; neutralizing antibodies were detected in less than 1% of cases and were presumed to reduce plasma concentration and efficacy in affected cases.",
        "ada_value_display": "5.1% ADA (34/668 HAVEN 1-4); <1% neutralizing",
        "ada_first_pct": 5.1,
        "nab_pct": "<1% neutralizing anti-emicizumab antibodies",
        "assay_platform": "Anti-emicizumab antibody assessment; platform not stated in retrieved review text",
        "pk_efficacy_impact": "Most ADA did not alter concentrations or bleeding; rare neutralizing antibodies decreased emicizumab concentration and efficacy.",
        "evidence_source": "Haematologica review summarizing HAVEN 1-4 clinical trial immunogenicity",
        "citation_urls": "https://haematologica.org/article/view/haematol.2022.282099",
        "ada_source_url_primary": "https://haematologica.org/article/view/haematol.2022.282099",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Clinical use section: antidrug antibodies in 5.1% (34/668) HAVEN 1-4 patients; neutralizing antibodies in <1% with decreased plasma concentration and efficacy.",
        "verify_note": "Normalized source fields from peer-reviewed review text.",
    },
    "Enfortumab": {
        "ada_value": "In the PADCEV label, 365 patients were tested for immunogenicity; 4 patients (1%) were confirmed transiently positive for anti-therapeutic antibody and 1 patient (0.3%) was confirmed persistently positive at any post-baseline time point.",
        "ada_value_display": "1% transient ATA (4/365); 0.3% persistent ATA (1/365)",
        "ada_first_pct": 1.0,
        "nab_pct": "Not stated",
        "assay_platform": "Immunogenicity/ATA assay (label; method-dependent)",
        "pk_efficacy_impact": "No impact of ATA on efficacy, safety, or pharmacokinetics was observed.",
        "evidence_source": "FDA PADCEV prescribing information, Section 6.2 Immunogenicity",
        "citation_urls": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/761137s000lbl.pdf",
        "ada_source_url_primary": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/761137s000lbl.pdf",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 6.2 Immunogenicity: 4/365 (1%) transiently positive and 1/365 (0.3%) persistently positive for ATA; no impact on efficacy, safety, or PK observed.",
        "verify_note": "Normalized source fields from FDA label text.",
    },
    "Enuzovimab": {
        "ada_value": "In the phase 1 healthy Chinese adult HFB30132A/enozuvimab study, ADA testing did not detect any anti-HFB30132A antibodies in serum during serial testing; a single IV infusion did not induce an immunogenic response in the study.",
        "ada_value_display": "0% ADA detected in phase 1 healthy Chinese adult study",
        "ada_first_pct": 0.0,
        "nab_pct": "Not applicable/no anti-HFB30132A antibodies detected",
        "assay_platform": "Validated electrochemiluminescence immunoassay-affinity capture elution bridging ADA assay",
        "pk_efficacy_impact": "No ADA detected; ADA impact on PK/safety not assessable.",
        "evidence_source": "Frontiers in Pharmacology phase 1 HFB30132A/enozuvimab study",
        "citation_urls": "https://www.frontiersin.org/articles/10.3389/fphar.2023.1117293/full; https://pubmed.ncbi.nlm.nih.gov/39793935/",
        "ada_source_url_primary": "https://www.frontiersin.org/articles/10.3389/fphar.2023.1117293/full",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Results/Immunogenicity: ADA test did not detect any anti-HFB30132A antibodies in serum during serial testing; HFB30132A did not induce immunogenic response.",
        "verify_note": "Corrected prior 1.5% value; retrieved Frontiers article supports no detected ADA in the phase 1 study.",
    },
    "Eptinezumab": {
        "ada_value": "In an integrated immunogenicity evaluation across five eptinezumab migraine trials, pooled treatment-emergent ADA occurred in 15.8% of eptinezumab-treated patients and NAbs occurred in 6.2%. Across study 2, PROMISE-1, PROMISE-2, and PREVAIL, treatment-emergent ADA was 15.9% (316/1993) and NAb positivity was 6.2% (124/1993).",
        "ada_value_display": "15.8% pooled treatment-emergent ADA; 6.2% NAb",
        "ada_first_pct": 15.8,
        "nab_pct": "6.2% pooled NAb",
        "assay_platform": "Tiered ECL bridging ADA assay; competitive ligand-binding NAb assay",
        "pk_efficacy_impact": "Integrated analyses found no clinically meaningful ADA impact on efficacy or safety; ADA/NAb responses were low-titer and transient.",
        "evidence_source": "Frontiers in Immunology integrated eptinezumab clinical immunogenicity evaluation",
        "citation_urls": "https://www.frontiersin.org/journals/immunology/articles/10.3389/fimmu.2021.765822/full",
        "ada_source_url_primary": "https://www.frontiersin.org/journals/immunology/articles/10.3389/fimmu.2021.765822/full",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Abstract/Results and Table 2: pooled TE ADA 15.8% and NAb 6.2%; second-generation pooled studies 316/1993 (15.9%) TE ADA and 124/1993 (6.2%) NAb; no clinically meaningful efficacy or safety impact.",
        "verify_note": "Replaced prior study-specific 20.6% display with integrated immunogenicity evaluation pooled TE ADA value.",
    },
    "Erenumab": {
        "ada_value": "In Aimovig clinical studies, anti-erenumab antibody development during the double-blind treatment phase occurred in 6.3% (56/884) of subjects receiving 70 mg erenumab, 3 of whom had in vitro neutralizing activity, and in 2.6% (13/504) receiving 140 mg erenumab, none of whom had in vitro neutralizing activity.",
        "ada_value_display": "6.3% at 70 mg; 2.6% at 140 mg",
        "ada_first_pct": 6.3,
        "nab_pct": "70 mg: 3 subjects with in vitro neutralizing activity; 140 mg: 0",
        "assay_platform": "Anti-erenumab antibody assessment (EMA product information; method-dependent)",
        "pk_efficacy_impact": "No impact of anti-erenumab antibody development was stated in the retrieved EMA product information excerpt.",
        "evidence_source": "EMA Aimovig product information, Immunogenicity section",
        "citation_urls": "https://ec.europa.eu/health/documents/community-register/2018/20180726141585/anx_141585_en.pdf; https://www.ema.europa.eu/en/documents/product-information/aimovig-epar-product-information_en.pdf",
        "ada_source_url_primary": "https://ec.europa.eu/health/documents/community-register/2018/20180726141585/anx_141585_en.pdf",
        "ada_source_type_curated": "ema_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity: anti-erenumab antibodies in 6.3% (56/884) at 70 mg, 3 with neutralizing activity; 2.6% (13/504) at 140 mg, none neutralizing.",
        "verify_note": "Normalized source fields from EMA product information.",
    },
    "Etaracizumab": {
        "ada_value": "In the phase I advanced solid tumor study of etaracizumab (Abegrin), the retrieved abstract states etaracizumab was well tolerated at doses up to 6 mg/kg with no evidence of immunogenicity.",
        "ada_value_display": "0% / no evidence of immunogenicity in phase I study",
        "ada_first_pct": 0.0,
        "nab_pct": "Not applicable/no immunogenicity detected",
        "assay_platform": "Immunogenicity assessment; platform not stated in retrieved abstract text",
        "pk_efficacy_impact": "No evidence of immunogenicity was reported; no ADA impact assessable.",
        "evidence_source": "Investigational New Drugs phase I etaracizumab/Abegrin study",
        "citation_urls": "https://link.springer.com/article/10.1007/s10637-007-9077-0",
        "ada_source_url_primary": "https://link.springer.com/article/10.1007/s10637-007-9077-0",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Abstract/Summary: etaracizumab was well tolerated at doses up to 6 mg/kg with no evidence of immunogenicity.",
        "verify_note": "Corrected prior 5.0% value; retrieved clinical study source supports no evidence of immunogenicity rather than a 5% ADA rate.",
    },
    "Etrolizumab": {
        "ada_value": "In a randomized phase I study in moderate-to-severe ulcerative colitis, antietrolizumab antibodies were detected in 2/38 drug-treated patients: one in the SAD 0.3 mg/kg IV cohort and one in the MD 0.5 mg/kg SC cohort. Titers were low and close to the minimum reportable level; no PK effect or allergic-reaction AEs were observed.",
        "ada_value_display": "5.3% antietrolizumab antibodies (2/38 drug-treated patients)",
        "ada_first_pct": 5.3,
        "nab_pct": "Not stated",
        "assay_platform": "ATA assay with immunodepletion confirmation; detailed platform not stated in retrieved text",
        "pk_efficacy_impact": "No PK-profile effect and no allergic-reaction adverse events were observed in the two ATA-positive patients.",
        "evidence_source": "Gut / PMC randomized phase I etrolizumab study",
        "citation_urls": "https://pmc.ncbi.nlm.nih.gov/articles/PMC3711369/; https://gut.bmj.com/content/62/8/1122.long",
        "ada_source_url_primary": "https://pmc.ncbi.nlm.nih.gov/articles/PMC3711369/",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity results: antietrolizumab antibodies detected in 2/38 drug-treated patients; low titers; no PK effect and no allergic-reaction AEs.",
        "verify_note": "Corrected prior 2% value to source-confirmed 2/38 (5.3%) from the phase I study.",
    },
    "Evinacumab": {
        "ada_value": "In EVKEEZA trials during the 24-week treatment period, anti-evinacumab-dgnb antibody formation was 0% (0/56) in adult and pediatric patients aged 12 years and older with HoFH in Trials 1 and 2. In pediatric patients aged 5 to 11 years with HoFH in Trial 3, anti-evinacumab-dgnb antibody formation was 5% (1/20), with no effect on efficacy or evinacumab-dgnb concentrations in that patient.",
        "ada_value_display": "0% in HoFH patients >=12 years (0/56); 5% in pediatric 5-11 years (1/20)",
        "ada_first_pct": 0.0,
        "nab_pct": "Not stated",
        "assay_platform": "Immunogenicity assay (label; method-dependent)",
        "pk_efficacy_impact": "In the one pediatric patient with anti-evinacumab antibodies, no effects on efficacy or evinacumab-dgnb concentrations were observed; overall effect is unknown due to low occurrence.",
        "evidence_source": "FDA EVKEEZA prescribing information, Section 12.6 Immunogenicity",
        "citation_urls": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761181s002lbl.pdf; https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=73412138-6d8f-4ea6-bb72-a740190470ff",
        "ada_source_url_primary": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761181s002lbl.pdf",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 12.6 Immunogenicity: Trials 1 and 2 >=12 years 0/56 (0%); Trial 3 ages 5-11 years 1/20 (5%); no efficacy or concentration effects in the antibody-positive patient.",
        "verify_note": "Corrected prior 2% value; current FDA label supports 0% in the primary >=12-year HoFH trial population and 5% in younger pediatric Trial 3.",
    },
    "Evolocumab": {
        "ada_value": "In pooled placebo- and active-controlled REPATHA trials, 0.3% (48/17,992) of adult patients treated with at least one dose tested positive for development of binding anti-drug antibodies; none tested positive for neutralizing antibodies.",
        "ada_value_display": "0.3% binding ADA (48/17,992); 0% neutralizing",
        "ada_first_pct": 0.3,
        "nab_pct": "0% / none tested positive for neutralizing antibodies",
        "assay_platform": "Electrochemiluminescent bridging screening immunoassay; in vitro biological neutralizing assay",
        "pk_efficacy_impact": "No evidence that anti-drug binding antibodies impacted pharmacokinetics, clinical response, or safety.",
        "evidence_source": "DailyMed/FDA REPATHA prescribing information, Section 6.2 Immunogenicity",
        "citation_urls": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=709338ae-ab8f-44a9-b7d5-abaabec3493a",
        "ada_source_url_primary": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=709338ae-ab8f-44a9-b7d5-abaabec3493a",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 6.2 Immunogenicity: 0.3% (48/17,992) adult patients binding ADA-positive; none neutralizing; no PK, clinical response, or safety impact.",
        "verify_note": "Corrected prior 0.1%/7 of 4846 display to current DailyMed pooled adult label value of 0.3% (48/17,992).",
    },
}

for col in set().union(*(entry.keys() for entry in updates.values())):
    if col not in df.columns:
        df[col] = pd.NA
    df[col] = df[col].astype("object")

for name, data in updates.items():
    mask = df["antibody_name"].fillna("").astype(str).str.casefold() == name.casefold()
    if mask.any():
        for col, val in data.items():
            df.loc[mask, col] = val
        print(f"Updated {name}")
    else:
        print(f"MISSING {name}")

df.to_csv(ada_path, index=False)
