import pandas as pd

ada_path = "data/immunogenicity_knowledge_base/master/ada_master_328_final_comprehensive.csv"
df = pd.read_csv(ada_path)

updates = {
    "Tarlatamab": {
        "ada_value": "In IMDELLTRA labeling, among patients who received the approved recommended dosage and were evaluable for ADA against tarlatamab-dlle, 3.2% (4/124) tested positive for anti-tarlatamab-dlle antibodies; no patients developed neutralizing antibodies based on a cell-based bioassay.",
        "ada_value_display": "3.2% ADA (4/124); 0% neutralizing",
        "ada_first_pct": 3.2,
        "nab_pct": "0% / none developed neutralizing antibodies",
        "assay_platform": "ADA assay with cell-based neutralizing bioassay",
        "pk_efficacy_impact": "Because of low ADA occurrence, the effect on pharmacokinetics, pharmacodynamics, safety, or effectiveness is unknown.",
        "evidence_source": "FDA IMDELLTRA prescribing information, Section 12.6 Immunogenicity",
        "citation_urls": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761344s000lbl.pdf",
        "ada_source_url_primary": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761344s000lbl.pdf",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 12.6 Immunogenicity: 3.2% (4/124) evaluable patients tested positive for anti-tarlatamab-dlle antibodies; none developed neutralizing antibodies; impact unknown due to low occurrence.",
        "verify_note": "Replaced legacy 8% value with FDA label-confirmed 3.2%.",
    },
    "Teprotumumab": {
        "ada_value": "A Drugs review of teprotumumab in thyroid eye disease reports that anti-drug antibodies were detected at low levels in 4 (2.3%) patients in the phase II and III TED clinical trials and did not alter teprotumumab pharmacokinetics.",
        "ada_value_display": "2.3% ADA (4 patients) in phase II/III TED trials",
        "ada_first_pct": 2.3,
        "nab_pct": "Not stated",
        "assay_platform": "ADA assessment in phase II/III TED trials; platform not specified in retrieved review text",
        "pk_efficacy_impact": "Low-level ADAs did not alter teprotumumab pharmacokinetics.",
        "evidence_source": "Drugs review article: Teprotumumab: A Review in Thyroid Eye Disease",
        "citation_urls": "https://link.springer.com/article/10.1007/s40265-022-01804-1",
        "ada_source_url_primary": "https://link.springer.com/article/10.1007/s40265-022-01804-1",
        "ada_source_type_curated": "peer_reviewed_review",
        "ada_has_text_evidence": True,
        "ada_source_section": "Pharmacokinetics section: anti-drug antibodies detected in four (2.3%) patients in phase II and III TED clinical trials at low levels and did not alter pharmacokinetics.",
        "verify_note": "Normalized source fields from peer-reviewed review.",
    },
    "Tezepelumab": {
        "ada_value": "In TEZSPIRE labeling, in asthma studies NAVIGATOR and an additional trial, ADA were detected at any time in 29/601 (5%) patients receiving the recommended regimen during 48 to 52 weeks; 11 patients (2%) developed treatment-emergent antibodies and one patient (<1%) developed neutralizing antibodies. In CRSwNP WAYPOINT, 5/164 (3%) developed treatment-emergent ADA and one ADA-positive patient had neutralizing antibodies.",
        "ada_value_display": "Asthma: 5% ADA any time (29/601), 2% treatment-emergent; CRSwNP: 3% treatment-emergent",
        "ada_first_pct": 5.0,
        "nab_pct": "Asthma: <1% neutralizing; CRSwNP: 1 ADA-positive patient had neutralizing antibodies",
        "assay_platform": "ADA and neutralizing antibody assays (label; method-dependent)",
        "pk_efficacy_impact": "No evidence of ADA impact on pharmacokinetics, pharmacodynamics, efficacy, or safety was observed in asthma; CRSwNP had insufficient ADA-positive numbers for formal assessment.",
        "evidence_source": "DailyMed/FDA TEZSPIRE prescribing information, Section 12.6 Immunogenicity",
        "citation_urls": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=60f0aa03-ad25-4d48-80ce-7fcfa76f325f",
        "ada_source_url_primary": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=60f0aa03-ad25-4d48-80ce-7fcfa76f325f",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 12.6 Immunogenicity: asthma 29/601 (5%) ADA at any time, 11/601 (2%) treatment-emergent, one neutralizing; CRSwNP 5/164 (3%) treatment-emergent ADA.",
        "verify_note": "Replaced mixed legacy values with current label-confirmed indication-specific values.",
    },
    "Tibulizumab": {
        "ada_value": "No precise numerical ADA incidence for tibulizumab was confirmed in retrieved sources. Available retrieval found trial registry/general ligand references, but no citable immunogenicity percentage.",
        "ada_value_display": "No confirmed numerical ADA percentage found in retrieved sources",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not confirmed",
        "assay_platform": "Not confirmed",
        "pk_efficacy_impact": "Not confirmed",
        "evidence_source": "No confirmed numerical ADA source retrieved",
        "citation_urls": "https://ctis.eu/search/trial/2024-519335-42-01.html; https://www.guidetoimmunopharmacology.org/GRAC/LigandDisplayForward?ligandId=10350&tab=summary",
        "ada_source_url_primary": pd.NA,
        "ada_source_type_curated": pd.NA,
        "ada_has_text_evidence": False,
        "ada_source_section": pd.NA,
        "verify_note": "Cleared legacy 3.3% because no retrievable source with a precise tibulizumab ADA percentage was found.",
    },
    "Tildrakizumab": {
        "ada_value": "In ILUMYA labeling, up to Week 64 approximately 6.5% of subjects treated with ILUMYA 100 mg developed antibodies to tildrakizumab. Of subjects who developed antibodies, approximately 40%, corresponding to 2.5% of all ILUMYA-treated subjects, had neutralizing antibodies.",
        "ada_value_display": "6.5% ADA; 2.5% all-treated neutralizing",
        "ada_first_pct": 6.5,
        "nab_pct": "Approximately 40% of ADA-positive subjects, 2.5% of all ILUMYA-treated subjects",
        "assay_platform": "ADA and neutralizing antibody assays (label; method-dependent)",
        "pk_efficacy_impact": "Neutralizing antibodies were associated with lower serum tildrakizumab concentrations and reduced efficacy.",
        "evidence_source": "DailyMed/FDA ILUMYA prescribing information, Section 6.2 Immunogenicity",
        "citation_urls": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c6a322bb-51b9-4f0e-8642-62a9682ffcde&audience=consumer",
        "ada_source_url_primary": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c6a322bb-51b9-4f0e-8642-62a9682ffcde&audience=consumer",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 6.2 Immunogenicity: up to Week 64, approximately 6.5% developed antibodies; approximately 40% of ADA-positive subjects, 2.5% of all treated subjects, had neutralizing antibodies; neutralizing antibodies associated with lower concentrations and reduced efficacy.",
        "verify_note": "Normalized source fields from FDA label.",
    },
    "Timigutuzumab": {
        "ada_value": "No precise numerical ADA incidence for timigutuzumab/TrasGEX was confirmed in retrieved sources. The retrieved review/source material did not provide a citable timigutuzumab immunogenicity percentage.",
        "ada_value_display": "No confirmed numerical ADA percentage found in retrieved sources",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not confirmed",
        "assay_platform": "Not confirmed",
        "pk_efficacy_impact": "Not confirmed",
        "evidence_source": "No confirmed numerical ADA source retrieved",
        "citation_urls": "https://mdpi-res.com/d_attachment/biomedicines/biomedicines-09-01277/article_deploy/biomedicines-09-01277-v2.pdf?version=1632377073; https://drugs.ncats.io/drug/A5HYI6N66H",
        "ada_source_url_primary": pd.NA,
        "ada_source_type_curated": pd.NA,
        "ada_has_text_evidence": False,
        "ada_source_section": pd.NA,
        "verify_note": "Cleared legacy 10-15% because no retrievable source with a precise timigutuzumab ADA percentage was found.",
    },
    "Tislelizumab": {
        "ada_value": "In TEVIMBRA labeling, anti-tislelizumab antibody incidence was 22% (66/300) in RATIONALE-306 up to 26 months, 14.5% (32/221) in RATIONALE-302 up to 22 months, and 22.7% (108/475) in RATIONALE-305 throughout the ADA analysis treatment period.",
        "ada_value_display": "RATIONALE-306: 22%; RATIONALE-302: 14.5%; RATIONALE-305: 22.7%",
        "ada_first_pct": 22.0,
        "nab_pct": "NAb among ADA-positive: RATIONALE-306 1.5% (1/66), RATIONALE-302 3.1% (1/32), RATIONALE-305 5.6% (6/108)",
        "assay_platform": "ADA and neutralizing antibody assays (label; method-dependent)",
        "pk_efficacy_impact": "No specific ADA clinical impact statement was extracted from the retrieved label section.",
        "evidence_source": "DailyMed/FDA TEVIMBRA prescribing information, Section 12.6 Immunogenicity",
        "citation_urls": "https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=08ef1e3e-496f-4b0b-94ee-fbba3cc1985a",
        "ada_source_url_primary": "https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=08ef1e3e-496f-4b0b-94ee-fbba3cc1985a",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 12.6 Immunogenicity: RATIONALE-306 22% (66/300), RATIONALE-302 14.5% (32/221), RATIONALE-305 22.7% (108/475); neutralizing antibodies 1.5%, 3.1%, and 5.6% among ADA-positive patients.",
        "verify_note": "Replaced legacy 3.5% with current FDA label trial-specific values.",
    },
    "Tixagevimab": {
        "ada_value": "In a first-in-human phase 1 AZD7442 study, no ADAs were detected up to Day 211. At Day 361, one participant among 50 AZD7442 recipients tested positive for anti-tixagevimab ADAs, and four and three participants tested positive for anti-cilgavimab ADAs in the 300 mg intramuscular and intravenous cohorts, respectively. Only one ADA-positive individual had treatment-emergent ADAs, with a titer of 1:80 to cilgavimab.",
        "ada_value_display": "Anti-tixagevimab ADA at Day 361: 1/50 (2.0%); treatment-emergent ADA: 1/50 to cilgavimab",
        "ada_first_pct": 2.0,
        "nab_pct": "Not stated for anti-drug antibodies; SARS-CoV-2 neutralizing activity was pharmacodynamic, not ADA neutralization",
        "assay_platform": "ADA assessment for tixagevimab-cilgavimab over 361 days",
        "pk_efficacy_impact": "The study reported similar tixagevimab/cilgavimab pharmacokinetic profiles and maintained neutralizing activity over the study period; no ADA-driven clinical effect was stated.",
        "evidence_source": "PMC first-in-human AZD7442 phase 1 study",
        "citation_urls": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10175065/",
        "ada_source_url_primary": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10175065/",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity/ADA results: no ADAs through Day 211; at Day 361, one participant tested anti-tixagevimab ADA-positive and 7 anti-cilgavimab ADA-positive across cohorts; only one treatment-emergent ADA-positive individual, to cilgavimab.",
        "verify_note": "Replaced unsupported 4.1% component value with source-confirmed phase 1 ADA findings.",
    },
    "Tocilizumab": {
        "ada_value": "In ACTEMRA RA 24-week controlled clinical studies, 2876 patients were tested for anti-tocilizumab antibodies; 46 (2%) developed positive anti-tocilizumab antibodies, of whom 5 had medically significant hypersensitivity leading to withdrawal. Thirty patients (1%) developed neutralizing antibodies.",
        "ada_value_display": "2% anti-tocilizumab antibodies (46/2876); 1% neutralizing",
        "ada_first_pct": 2.0,
        "nab_pct": "1% (30 patients) neutralizing antibodies",
        "assay_platform": "Anti-tocilizumab antibody assays (label; method-dependent)",
        "pk_efficacy_impact": "Five anti-tocilizumab antibody-positive patients had medically significant hypersensitivity reactions leading to withdrawal.",
        "evidence_source": "FDA ACTEMRA prescribing information, Immunogenicity section",
        "citation_urls": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2017/125276s111,125472s023lbl.pdf",
        "ada_source_url_primary": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2017/125276s111,125472s023lbl.pdf",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity: 2876 tested, 46 (2%) anti-tocilizumab antibody-positive; 5 with medically significant hypersensitivity leading to withdrawal; 30 (1%) neutralizing.",
        "verify_note": "Normalized source fields from FDA label.",
    },
    "Toripalimab": {
        "ada_value": "In LOQTORZI labeling, 3.4% of 146 evaluable JUPITER-02 NPC patients receiving toripalimab 240 mg every 3 weeks with gemcitabine/cisplatin tested positive for treatment-emergent ADA. In POLARIS-02, 3.7% of 190 evaluable NPC patients receiving toripalimab 3 mg/kg every 2 weeks developed treatment-emergent ADA. Neutralizing antibodies were not tested.",
        "ada_value_display": "JUPITER-02: 3.4% treatment-emergent ADA; POLARIS-02: 3.7%",
        "ada_first_pct": 3.4,
        "nab_pct": "Neutralizing antibodies were not tested",
        "assay_platform": "ADA assay (label; method-dependent)",
        "pk_efficacy_impact": "Due to low ADA incidence, the effect on pharmacokinetics, pharmacodynamics, safety, or effectiveness is unknown.",
        "evidence_source": "DailyMed/FDA LOQTORZI prescribing information, Section 12.6 Immunogenicity",
        "citation_urls": "https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=82e7921a-1e84-4988-9799-0ad7d19b2a75",
        "ada_source_url_primary": "https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=82e7921a-1e84-4988-9799-0ad7d19b2a75",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 12.6 Immunogenicity: JUPITER-02 3.4% treatment-emergent ADA among 146 evaluable patients; POLARIS-02 3.7% among 190 evaluable patients; neutralizing antibodies not tested; effect unknown.",
        "verify_note": "Replaced animal/early-phase legacy summary with current FDA label-confirmed human ADA rates.",
    },
    "Tralokinumab": {
        "ada_value": "In ADBRY labeling, during the initial 16-week treatment period in ECZTRA 1, ECZTRA 2, ECZTRA 3, and the vaccine-response trial, ADA incidence was 1.4% for subjects treated with ADBRY 300 mg every other week and 1.3% for placebo; neutralizing antibodies were seen in 0.1% of ADBRY-treated subjects and 0.2% of placebo-treated subjects. Across all trial periods, ADA incidence among ADBRY recipients was 4.6%, with 0.9% persistent ADA and 1.0% neutralizing antibodies.",
        "ada_value_display": "Initial 16 weeks: 1.4% ADA; all trial periods: 4.6% ADA",
        "ada_first_pct": 1.4,
        "nab_pct": "Initial 16 weeks: 0.1%; all trial periods: 1.0% neutralizing",
        "assay_platform": "ADA and neutralizing antibody assays (label; method-dependent)",
        "pk_efficacy_impact": "No clinically significant PK, safety, or efficacy differences were observed in antibody-positive patients, including neutralizing antibody-positive patients.",
        "evidence_source": "DailyMed/FDA ADBRY prescribing information, Section 12.6 Immunogenicity",
        "citation_urls": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d8020b69-3001-44e2-9b5d-5f93d9aaf6e1",
        "ada_source_url_primary": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=d8020b69-3001-44e2-9b5d-5f93d9aaf6e1",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 12.6 Immunogenicity: initial 16 weeks 1.4% ADA with ADBRY and 1.3% placebo; neutralizing 0.1% vs 0.2%; across all periods ADBRY ADA 4.6%, persistent 0.9%, neutralizing 1.0%; no clinically significant PK/safety/efficacy differences.",
        "verify_note": "Replaced asthma-trial legacy summary with current ADBRY atopic dermatitis label values.",
    },
    "Trastuzumab": {
        "ada_value": "In current HERCEPTIN labeling, among 903 women with metastatic breast cancer, human anti-human antibody (HAHA) to Herceptin was detected in one patient by ELISA; this patient did not experience an allergic reaction. Samples for HAHA assessment were not collected in adjuvant breast cancer studies.",
        "ada_value_display": "1/903 HAHA-positive (0.11%) by ELISA",
        "ada_first_pct": 0.11,
        "nab_pct": "Not stated",
        "assay_platform": "ELISA for human anti-human antibody to Herceptin",
        "pk_efficacy_impact": "The single HAHA-positive patient did not experience an allergic reaction; clinical relevance is not known.",
        "evidence_source": "Genentech HERCEPTIN prescribing information, Section 12.6 Immunogenicity",
        "citation_urls": "https://www.gene.com/download/pdf/herceptin_prescribing.pdf",
        "ada_source_url_primary": "https://www.gene.com/download/pdf/herceptin_prescribing.pdf",
        "ada_source_type_curated": "drug_label_or_monograph",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 12.6 Immunogenicity: among 903 women with metastatic breast cancer, HAHA to Herceptin detected in one patient by ELISA; no allergic reaction; clinical relevance unknown.",
        "verify_note": "Replaced legacy '<8%' estimate with source-confirmed 1/903 HAHA-positive label value.",
    },
    "Ustekinumab": {
        "ada_value": "In STELARA labeling, approximately 6% to 12.4% of subjects treated in plaque psoriasis and psoriatic arthritis clinical trials developed antibodies to ustekinumab, generally low-titer. In Crohn's disease and ulcerative colitis trials, 2.9% and 4.6% of subjects, respectively, developed antibodies after approximately one year of treatment.",
        "ada_value_display": "Psoriasis/PsA: 6-12.4% ADA; Crohn's disease: 2.9%; UC: 4.6%",
        "ada_first_pct": 6.0,
        "nab_pct": "Plaque psoriasis: majority of antibody-positive subjects had neutralizing antibodies",
        "assay_platform": "ADA and neutralizing antibody assays (label; method-dependent)",
        "pk_efficacy_impact": "In plaque psoriasis, antibodies were associated with reduced or undetectable serum ustekinumab concentrations and reduced efficacy; no apparent association with injection-site reactions was seen in CD/UC.",
        "evidence_source": "FDA STELARA prescribing information, Immunogenicity section",
        "citation_urls": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/125261s171,761044s019lbl.pdf",
        "ada_source_url_primary": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/125261s171,761044s019lbl.pdf",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity: 6-12.4% antibodies in plaque psoriasis/PsA; generally low-titer; plaque psoriasis antibodies associated with reduced/undetectable concentrations and reduced efficacy; CD 2.9%, UC 4.6%.",
        "verify_note": "Updated from older indication-specific 2.3% value to current label indication range.",
    },
    "Vedolizumab": {
        "ada_value": "In current ENTYVIO labeling, using a drug-tolerant ECL method, IV continuous-treatment UC/CD trials through 52 weeks had 6% anti-vedolizumab antibodies (86/1427); 20 patients were persistently positive and 56 developed neutralizing antibodies. Subcutaneous continuous-treatment UC/CD trials through 52 weeks had 3.4% ADA (13/381), with 7 persistently positive and 7 neutralizing.",
        "ada_value_display": "IV continuous treatment: 6% ADA (86/1427); SC continuous treatment: 3.4% (13/381)",
        "ada_first_pct": 6.0,
        "nab_pct": "IV: 56/86 ADA-positive developed neutralizing antibodies; SC: 7/13 ADA-positive developed neutralizing antibodies",
        "assay_platform": "Drug-tolerant electrochemiluminescence (ECL) method",
        "pk_efficacy_impact": "Among persistent IV anti-vedolizumab antibody-positive patients, 14/20 had markedly reduced or undetectable trough concentrations and 15/20 did not achieve clinical remission at Week 52; overall safety/effectiveness impact not fully characterized due to low persistent ADA occurrence.",
        "evidence_source": "DailyMed/FDA ENTYVIO prescribing information, Section 12.6 Immunogenicity",
        "citation_urls": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6e94621c-1a95-4af9-98d1-52b9e6f1949c",
        "ada_source_url_primary": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6e94621c-1a95-4af9-98d1-52b9e6f1949c",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 12.6 Immunogenicity: IV continuous treatment 6% (86/1427), 20 persistent, 56 neutralizing; persistent ADA associated with reduced/undetectable trough concentrations and lack of Week 52 remission in most persistent-positive patients; SC 3.4% (13/381), 7 persistent, 7 neutralizing.",
        "verify_note": "Replaced older 2.4%/22.1% legacy values with current label values using drug-tolerant ECL method.",
    },
    "Vunakizumab": {
        "ada_value": "No precise numerical ADA incidence for vunakizumab was confirmed in retrieved sources. Available phase 2/phase 3 summaries did not provide a citable immunogenicity percentage.",
        "ada_value_display": "No confirmed numerical ADA percentage found in retrieved sources",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not confirmed",
        "assay_platform": "Not confirmed",
        "pk_efficacy_impact": "Not confirmed",
        "evidence_source": "No confirmed numerical ADA source retrieved",
        "citation_urls": "https://pubmed.ncbi.nlm.nih.gov/35026342/; https://www.em-consulte.com/article/1695587/efficacy-and-safety-of-vunakizumab-in-moderate-to-",
        "ada_source_url_primary": pd.NA,
        "ada_source_type_curated": pd.NA,
        "ada_has_text_evidence": False,
        "ada_source_section": pd.NA,
        "verify_note": "Cleared legacy 10-15% because no retrievable source with a precise vunakizumab ADA percentage was found.",
    },
    "Zalifrelimab": {
        "ada_value": "No precise numerical ADA incidence for zalifrelimab was confirmed in retrieved peer-reviewed or regulatory-accessible sources. Retrieved clinical trial material did not report a citable zalifrelimab immunogenicity percentage.",
        "ada_value_display": "No confirmed numerical ADA percentage found in retrieved sources",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not confirmed",
        "assay_platform": "Not confirmed",
        "pk_efficacy_impact": "Not confirmed",
        "evidence_source": "No confirmed numerical ADA source retrieved",
        "citation_urls": "https://pubmed.ncbi.nlm.nih.gov/40378054/",
        "ada_source_url_primary": pd.NA,
        "ada_source_type_curated": pd.NA,
        "ada_has_text_evidence": False,
        "ada_source_section": pd.NA,
        "verify_note": "Cleared legacy 20% value because no retrievable source with a precise zalifrelimab ADA percentage was found.",
    },
    "Zimberelimab": {
        "ada_value": "No precise numerical ADA incidence for zimberelimab/GLS-010 was confirmed in retrieved sources. Retrieved preclinical and phase II clinical sources did not provide a citable ADA percentage.",
        "ada_value_display": "No confirmed numerical ADA percentage found in retrieved sources",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not confirmed",
        "assay_platform": "Not confirmed",
        "pk_efficacy_impact": "Not confirmed",
        "evidence_source": "No confirmed numerical ADA source retrieved",
        "citation_urls": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10804044/; https://www.frontiersin.org/journals/oncology/articles/10.3389/fonc.2021.736955/full",
        "ada_source_url_primary": pd.NA,
        "ada_source_type_curated": pd.NA,
        "ada_has_text_evidence": False,
        "ada_source_section": pd.NA,
        "verify_note": "Cleared legacy 0.0% because no retrievable source with a precise zimberelimab ADA percentage was found.",
    },
}

for col in set().union(*(entry.keys() for entry in updates.values())):
    if col not in df.columns:
        df[col] = pd.NA
    df[col] = df[col].astype("object")

for name, data in updates.items():
    mask = df["antibody_name"].fillna("").astype(str).str.casefold() == name.casefold()
    if mask.any():
        for col, val in data.items():
            df.loc[mask, col] = val
        print(f"Updated {name}")
    else:
        print(f"MISSING {name}")

df.to_csv(ada_path, index=False)
