import pandas as pd


ada_path = "data/immunogenicity_knowledge_base/master/ada_master_328_final_comprehensive.csv"
df = pd.read_csv(ada_path)

updates = {
    "Tovetumab": {
        "ada_value": "ADA incidence not stated in retrieved tovetumab/MEDI-575 public clinical and PK-PD sources",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "Not stated in retrieved public result text; clinical programs included recurrent glioblastoma and NSCLC studies",
        "dose_freq": "Not stated in retrieved public result text",
        "route_curated": "Intravenous",
        "assay_platform": "Anti-drug antibody sample analysis acknowledged in PK-PD publication; clinical ADA incidence not stated",
        "pk_efficacy_impact": "Retrieved sources describe tovetumab PK-PD modeling and clinical development, but no ADA incidence or ADA impact",
        "evidence_source": "NCATS/Inxight Drugs tovetumab page; Synapse tovetumab page; AAPS Journal tovetumab PK-PD biomarker article",
        "citation_urls": "https://drugs.ncats.io/drug/2XY62K75UV; https://synapse.patsnap.com/drug/3da8bf4612594901ab309bb62de40ad2; https://link.springer.com/article/10.1208/s12248-020-00523-3",
        "ada_source_url_primary": "https://link.springer.com/article/10.1208/s12248-020-00523-3",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "AAPS Journal article acknowledges PK, anti-drug antibody, and PDGF-AA sample analysis supporting clinical development; retrieved clinical/public pages do not state ADA incidence.",
        "verify_note": "Prior MSD 5.0% value was not supported by retrieved tovetumab source text.",
    },
    "Tregalizumab": {
        "ada_value": "ADA incidence not stated in retrieved tregalizumab/BT-061 clinical-result and review sources",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "25, 100, or 200 mg SC once weekly in TREAT 2b phase IIb RA study",
        "dose_freq": "Once weekly subcutaneous dosing",
        "route_curated": "Subcutaneous",
        "assay_platform": "Not stated in retrieved sources",
        "pk_efficacy_impact": "Retrieved EudraCT result and review sources describe efficacy/safety and PK analysis sets but do not report ADA incidence or ADA impact",
        "evidence_source": "EU Clinical Trials Register TREAT 2b result page; Annals of the Rheumatic Diseases TREAT 2b article; Frontiers in Immunology/PMC tregalizumab review",
        "citation_urls": "https://www.clinicaltrialsregister.eu/ctr-search/trial/2013-000114-38/results; https://ard.bmj.com/content/77/4/495; https://pmc.ncbi.nlm.nih.gov/articles/PMC4724712/",
        "ada_source_url_primary": "https://www.clinicaltrialsregister.eu/ctr-search/trial/2013-000114-38/results",
        "ada_source_pmids": "26834751",
        "ada_source_type_curated": "clinical_trial_registry",
        "ada_has_text_evidence": True,
        "ada_source_section": "EudraCT TREAT 2b result page lists study design, doses, safety/PK sets, and outcomes; retrieved text does not contain ADA, anti-drug antibody, or immunogenicity incidence.",
        "verify_note": "Prior MSD 12.0% value was not supported by retrieved tregalizumab source text; unrelated Positive/Negative fields in EudraCT were not ADA fields.",
    },
    "Trevogrumab": {
        "ada_value": "ADA assessment is planned/ongoing in retrieved trevogrumab COURAGE trial sources; numeric ADA incidence not stated",
        "ada_value_display": "ADA assessed/planned; numeric not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "Dose levels blinded/not stated in retrieved public COURAGE sources",
        "dose_freq": "SC or IV in Part A; SC trevogrumab with semaglutide in Parts B/C depending on arm",
        "route_curated": "Subcutaneous; Intravenous",
        "assay_platform": "ADA assessment described as whether the body makes antibodies against study drug; assay platform not stated",
        "pk_efficacy_impact": "Retrieved active phase 2 COURAGE trial pages list ADA assessment as a research question, but no results or impact are available",
        "evidence_source": "Trials Today NCT06299098 COURAGE page; Veeva CTV COURAGE page; AdisInsight/Larvol search results",
        "citation_urls": "https://www.trialstoday.org/trial/NCT06299098; https://ctv.veeva.com/study/a-study-to-test-if-trevogrumab-or-trevogrumab-with-garetosmab-when-taken-with-semaglutide-is-safe-an",
        "ada_source_url_primary": "https://www.trialstoday.org/trial/NCT06299098",
        "ada_source_type_curated": "clinical_trial_registry",
        "ada_has_text_evidence": True,
        "ada_source_section": "COURAGE trial page states the study asks whether the body makes antibodies against the study drug, which could affect efficacy or safety; no numeric ADA result is reported.",
        "verify_note": "Prior MSD 4.0% value was not supported by retrieved trevogrumab source text.",
    },
    "Tusamitamab": {
        "ada_value": "Incidence of anti-therapeutic antibodies against tusamitamab ravtansine was a protocol endpoint; numeric ATA/ADA incidence not stated in retrieved public article/protocol text",
        "ada_value_display": "ATA assessed/planned; numeric not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "100 mg/m2 every 2 weeks in CARMEN-LC06 protocol; phase I alternative schedules included 120-170 mg/m2 loading dose then 100 mg/m2 Q2W or 120-190 mg/m2 Q3W",
        "dose_freq": "Every 2 weeks or every 3 weeks depending on study/cohort",
        "route_curated": "Intravenous",
        "assay_platform": "Anti-therapeutic antibody assessment planned; assay platform not stated in retrieved text",
        "pk_efficacy_impact": "Retrieved phase I article and CARMEN-LC06 protocol describe PK and immunogenicity endpoints, but no numeric ATA incidence or impact",
        "evidence_source": "Sanofi CARMEN-LC06 NCT05245071 protocol; Cancer Research Communications/PMC phase I alternative dosing article; PubMed first-in-human study result",
        "citation_urls": "https://cdn.clinicaltrials.gov/large-docs/71/NCT05245071/Prot_000.pdf; https://pmc.ncbi.nlm.nih.gov/articles/PMC10461573/; https://pubmed.ncbi.nlm.nih.gov/35026412/",
        "ada_source_url_primary": "https://cdn.clinicaltrials.gov/large-docs/71/NCT05245071/Prot_000.pdf",
        "ada_source_pmids": "35026412",
        "ada_source_type_curated": "clinical_trial_document",
        "ada_has_text_evidence": True,
        "ada_source_section": "CARMEN-LC06 protocol objective/endpoints: evaluate immunogenicity of tusamitamab ravtansine by incidence of participants with anti-therapeutic antibodies; retrieved sources do not state numeric incidence.",
        "verify_note": "Prior pending 1.0% value was not supported by retrieved tusamitamab source text.",
    },
    "Upinitatug": {
        "ada_value": "ADA/immunogenicity incidence not stated in retrieved upinitatug/upifitamab rilsodotin (XMT-1536/UpRi) public trial sources",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "Not stated in retrieved registry summary",
        "dose_freq": "Intravenous infusion once every 4 weeks in NCT03319628",
        "route_curated": "Intravenous",
        "assay_platform": "Not stated in retrieved public sources",
        "pk_efficacy_impact": "NCT03319628 registry summary states pharmacokinetics were assessed using proprietary assays and no results were posted; ADA incidence not reported",
        "evidence_source": "CDEK/ClinicalTrials.gov-derived NCT03319628 record; ICH GCP NCT03319628 record; Antibody Society upifitamab/upinitatug page",
        "citation_urls": "https://cdek.pharmacy.purdue.edu/trial/NCT03319628/; https://ichgcp.net/clinical-trials-registry/NCT03319628; https://db.antibodysociety.org/db0/2594/",
        "ada_source_url_primary": "https://cdek.pharmacy.purdue.edu/trial/NCT03319628/",
        "ada_source_type_curated": "clinical_trial_registry",
        "ada_has_text_evidence": True,
        "ada_source_section": "NCT03319628 public record describes XMT-1536/upifitamab rilsodotin IV every 4 weeks and PK assessment; no posted results and no ADA/immunogenicity incidence stated.",
        "verify_note": "Prior pending 2.0% value was not supported by retrieved upinitatug/upifitamab source text.",
    },
    "Vadastuximab": {
        "ada_value": "ADA incidence not stated in retrieved vadastuximab talirine/SGN-CD33A public trial and drug sources",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "Not stated in retrieved public CASCADE summary",
        "dose_freq": "Not stated in retrieved public CASCADE summary",
        "route_curated": "Intravenous",
        "assay_platform": "Not stated in retrieved public sources",
        "pk_efficacy_impact": "Retrieved CASCADE and drug pages describe trial discontinuation after higher deaths/fatal infections in SGN-CD33A arm; no ADA incidence or impact reported",
        "evidence_source": "Seattle Genetics CASCADE discontinuation SEC release; Veeva/Orphanet CASCADE trial pages; IUPHAR/BPS vadastuximab talirine page; Antibody Society entry",
        "citation_urls": "https://www.sec.gov/Archives/edgar/data/1060736/000119312517206413/d389609dex991.htm; https://ctv.veeva.com/study/vadastuximab-talirine-sgn-cd33a-33a-combined-with-azacitidine-or-decitabine-in-older-patients-wit; https://www.guidetopharmacology.org/GRAC/LigandDisplayForward?ligandId=9434&tab=clinical; https://db.antibodysociety.org/db0/2517/",
        "ada_source_url_primary": "https://www.guidetopharmacology.org/GRAC/LigandDisplayForward?ligandId=9434&tab=clinical",
        "ada_source_type_curated": "drug_database",
        "ada_has_text_evidence": True,
        "ada_source_section": "Retrieved public pages describe SGN-CD33A clinical use and trial holds/discontinuation, but do not report ADA, anti-drug antibody, or immunogenicity incidence.",
        "verify_note": "Prior pending 2.0% value was not supported by retrieved vadastuximab source text.",
    },
    "Vantictumab": {
        "ada_value": "2/48 patients (4.2%) developed anti-drug antibodies at some point during the phase Ib vantictumab plus paclitaxel study; ADA did not impact exposure",
        "ada_value_display": "4.2% (2/48)",
        "ada_first_pct": 4.2,
        "nab_pct": "Not stated",
        "dose_mg": "Vantictumab 3.5-14 mg/kg Q2W or 3-8 mg/kg Q4W with paclitaxel 90 mg/m2",
        "dose_freq": "Every 2 weeks or every 4 weeks depending on cohort",
        "route_curated": "Intravenous",
        "assay_platform": "Blood samples for ADA obtained on cycle 1 day 1, cycle 3 day 1, every other subsequent cycle, and treatment termination; assay platform not stated",
        "pk_efficacy_impact": "ADA development in 2/48 patients did not impact exposure",
        "evidence_source": "Breast Cancer Research and Treatment/PMC phase Ib vantictumab plus paclitaxel study; PubMed PMID 32803633",
        "citation_urls": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7572714/; https://pubmed.ncbi.nlm.nih.gov/32803633/",
        "ada_source_url_primary": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7572714/",
        "ada_source_pmids": "32803633",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Pharmacokinetic and immunogenicity analysis: two of 48 patients (4.2%) developed ADAs at some point during the study; this did not impact exposure.",
        "verify_note": "Corrected prior unsourced MSD 35.0% value to source-confirmed 4.2%.",
    },
    "Varisacumab": {
        "ada_value": "Clinical ADA incidence not stated in retrieved varisacumab public drug/source pages",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "Not stated in retrieved varisacumab public sources",
        "dose_freq": "Not stated in retrieved varisacumab public sources",
        "route_curated": "Not stated in retrieved varisacumab public sources",
        "assay_platform": "A commercial anti-varisacumab antibody ELISA kit was found, but no clinical ADA incidence was retrieved",
        "pk_efficacy_impact": "Retrieved varisacumab sources identify a VEGFA-targeting antibody and development status; no clinical ADA incidence or impact reported. MEDI3617 was excluded as a different anti-Ang2 antibody.",
        "evidence_source": "Thera-SAbDab varisacumab entry; AdisInsight search result; FineTest anti-varisacumab antibody ELISA kit page; Johns Hopkins MEDI3617 page excluded as different agent",
        "citation_urls": "https://opig.stats.ox.ac.uk/webapps/sabdab-sabpred/therasabdab/therasummary/?INN=varisacumab&format=Whole+mAb&clintrial=Phase-II%2FIII; https://www.fn-test.com/product/eu6561/; https://pure.johnshopkins.edu/en/publications/phase-i-study-of-medi3617-a-selective-angiopoietin-2-inhibitor-al",
        "ada_source_url_primary": "https://opig.stats.ox.ac.uk/webapps/sabdab-sabpred/therasabdab/therasummary/?INN=varisacumab&format=Whole+mAb&clintrial=Phase-II%2FIII",
        "ada_source_type_curated": "drug_database",
        "ada_has_text_evidence": True,
        "ada_source_section": "Retrieved varisacumab-specific results do not report clinical ADA incidence. Anti-varisacumab ELISA kit availability is not clinical incidence evidence.",
        "verify_note": "Prior pending 1.0% value was not supported by retrieved varisacumab source text; MEDI3617 was not assigned to varisacumab.",
    },
}

for col in set().union(*(entry.keys() for entry in updates.values())):
    if col not in df.columns:
        df[col] = pd.NA
    df[col] = df[col].astype("object")

for name, data in updates.items():
    mask = df["antibody_name"].fillna("").astype(str).str.casefold() == name.casefold()
    if mask.any():
        for col, val in data.items():
            df.loc[mask, col] = val
        print(f"Updated {name}")
    else:
        print(f"MISSING {name}")

df.to_csv(ada_path, index=False)
