import pandas as pd


ada_path = "data/immunogenicity_knowledge_base/master/ada_master_328_final_comprehensive.csv"
df = pd.read_csv(ada_path)

updates = {
    "Exidavnemab": {
        "ada_value": "The PubMed abstract for two phase 1 single-ascending-dose studies states that anti-drug antibody rates were low and that immunogenicity had no effect on pharmacokinetics or safety, but no precise ADA percentage was stated in the retrieved abstract/search text.",
        "ada_value_display": "Low ADA rate reported; numeric incidence not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "assay_platform": "Immunogenicity assessed; platform not stated in retrieved abstract text",
        "pk_efficacy_impact": "No effect of immunogenicity on pharmacokinetics or safety was stated.",
        "evidence_source": "PubMed abstract: phase 1 exidavnemab safety/tolerability/pharmacokinetics study",
        "citation_urls": "https://pubmed.ncbi.nlm.nih.gov/39105497/; https://doi.org/10.1002/jcph.6103",
        "ada_source_url_primary": "https://pubmed.ncbi.nlm.nih.gov/39105497/",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Abstract: anti-drug antibody rates were low and there was no effect of immunogenicity on pharmacokinetics or safety; no precise numeric ADA incidence was reported in the retrievable abstract text.",
        "verify_note": "Cleared prior 7.0% value because no precise percentage was found in retrievable PubMed/DOI/search text.",
    },
    "Faricimab": {
        "ada_value": "In VABYSMO nAMD and DME studies, pre-treatment anti-faricimab antibody incidence was approximately 1.8% and 0.8%, respectively; after initiation of dosing, anti-faricimab antibodies were detected in approximately 10.4% and 8.4% of patients with nAMD and DME, respectively.",
        "ada_value_display": "10.4% nAMD; 8.4% DME post-dose anti-faricimab antibodies",
        "ada_first_pct": 10.4,
        "nab_pct": "Not stated",
        "assay_platform": "Plasma immunoassays",
        "pk_efficacy_impact": "Label does not state a specific ADA effect on PK, safety, or efficacy.",
        "evidence_source": "FDA VABYSMO prescribing information, Section 6.2 Immunogenicity",
        "citation_urls": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2022/761235s000lbl.pdf; https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=04cc9ef7-c02a-4e92-a655-0062674e8487",
        "ada_source_url_primary": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2022/761235s000lbl.pdf",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 6.2 Immunogenicity: after initiation of dosing, anti-faricimab antibodies were detected in approximately 10.4% and 8.4% of patients with nAMD and DME, respectively.",
        "verify_note": "Corrected unrelated stored PubMed link and replaced approximate 10% with label-confirmed 10.4% nAMD value.",
    },
    "Favezelimab": {
        "ada_value": "Not stated in retrieved PubMed/PMC efficacy and safety sources for favezelimab plus pembrolizumab; the stored 42.9% value was not confirmed as ADA incidence.",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "assay_platform": "Not stated",
        "pk_efficacy_impact": "Not stated",
        "evidence_source": "Retrieved PubMed/PMC sources did not report a numeric favezelimab ADA incidence",
        "citation_urls": "https://pubmed.ncbi.nlm.nih.gov/40668662/; https://pmc.ncbi.nlm.nih.gov/articles/PMC9832734/",
        "ada_source_url_primary": pd.NA,
        "ada_source_type_curated": pd.NA,
        "ada_has_text_evidence": False,
        "ada_source_section": "Retrieved sources report efficacy/safety outcomes but no numeric ADA incidence; 42.9% was not found as an immunogenicity value.",
        "verify_note": "Cleared prior 42.9% value because reverse retrieval did not confirm it as ADA incidence.",
    },
    "Fremanezumab": {
        "ada_value": "In placebo-controlled AJOVY studies, treatment-emergent anti-drug antibody responses were observed in 6/1701 (0.4%) AJOVY-treated patients; one of the six patients developed anti-AJOVY neutralizing antibodies at Day 84. In an ongoing long-term open-label study, ADA were detected in 1.6% of patients and two of 17 had neutralizing activity.",
        "ada_value_display": "0.4% TE ADA (6/1701); 1 neutralizing at Day 84",
        "ada_first_pct": 0.4,
        "nab_pct": "1 of 6 ADA-positive patients in controlled studies; 2/17 ADA-positive patients in long-term open-label study",
        "assay_platform": "ADA and neutralizing antibody assays (label; method-dependent)",
        "pk_efficacy_impact": "Label states these data do not demonstrate an impact of anti-fremanezumab antibody development on efficacy or safety.",
        "evidence_source": "FDA AJOVY prescribing information, Section 6.2 Immunogenicity",
        "citation_urls": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761089s030lbl.pdf; https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=98e344ea-5916-4947-b6f2-4a76ccc04b6b",
        "ada_source_url_primary": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761089s030lbl.pdf",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 6.2 Immunogenicity: ADA responses were observed in 6/1701 (0.4%) AJOVY-treated patients; one developed neutralizing antibodies at Day 84; no demonstrated efficacy or safety impact.",
        "verify_note": "Corrected unrelated stored PubMed link; retained label-confirmed 0.4% value.",
    },
    "Fulranumab": {
        "ada_value": "A PubMed-indexed assay-method article states that initial high apparent anti-fulranumab antibody incidence (>60%) in clinical samples was due to NGF interference and false-positive assay signal; a precise true clinical ADA percentage was not stated in the retrieved text.",
        "ada_value_display": "True ADA incidence not stated; apparent >60% was false-positive assay interference",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "assay_platform": "Bridging electrochemiluminescence ADA assay revised to remove NGF interference",
        "pk_efficacy_impact": "Not stated for a precise ADA-positive population; article focuses on assay interference.",
        "evidence_source": "PubMed assay-method article on fulranumab immunogenicity false-positive elimination",
        "citation_urls": "https://pubmed.ncbi.nlm.nih.gov/24590506/; https://link.springer.com/article/10.1208/s12248-014-9581-z",
        "ada_source_url_primary": "https://pubmed.ncbi.nlm.nih.gov/24590506/",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Abstract: initial high apparent anti-fulranumab antibody incidence (>60%) was due to fulranumab-bound NGF released during acid-dissociation; revised method identifies true fulranumab-specific ADA, but no precise clinical ADA percentage is stated.",
        "verify_note": "Cleared prior 6.0% value because reverse retrieval did not confirm a precise 6% ADA rate.",
    },
    "Galcanezumab": {
        "ada_value": "In controlled EMGALITY migraine studies up to 6 months, anti-galcanezumab-gnlm antibody development occurred in 4.8% (33/688) of patients receiving EMGALITY once monthly; 32/33 had in vitro neutralizing activity. With 12 months of treatment in an open-label study, up to 12.5% (16/128) developed anti-galcanezumab antibodies, most with neutralizing antibodies.",
        "ada_value_display": "4.8% ADA (33/688); 32/33 neutralizing in vitro",
        "ada_first_pct": 4.8,
        "nab_pct": "32/33 ADA-positive patients in controlled studies had in vitro neutralizing activity",
        "assay_platform": "In vitro immunoassay for binding antibodies; in vitro ligand-binding neutralizing assay",
        "pk_efficacy_impact": "Anti-galcanezumab antibody development was not found to affect PK, safety, or efficacy, but available data are limited.",
        "evidence_source": "DailyMed/FDA EMGALITY prescribing information, Section 6.2 Immunogenicity",
        "citation_urls": "https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=33a147be-233a-40e8-a55e-e40936e28db0&version=14; https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761063s010lbl.pdf",
        "ada_source_url_primary": "https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=33a147be-233a-40e8-a55e-e40936e28db0&version=14",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 6.2 Immunogenicity: controlled studies up to 6 months showed 4.8% (33/688) ADA; 32/33 had in vitro neutralizing activity; open-label 12-month study up to 12.5%.",
        "verify_note": "Normalized source fields from current label text.",
    },
    "Garadacimab": {
        "ada_value": "In VANGUARD, 2.6% (1/39) of patients who received garadacimab-gxii tested positive for anti-garadacimab antibodies during the 6-month treatment period; ADA development did not affect PK, safety, or clinical response.",
        "ada_value_display": "2.6% anti-garadacimab antibodies (1/39)",
        "ada_first_pct": 2.6,
        "nab_pct": "Not stated",
        "assay_platform": "ADA assay (label; method-dependent)",
        "pk_efficacy_impact": "ADA development did not affect pharmacokinetics, safety, or clinical response.",
        "evidence_source": "FDA ANDEMBRY prescribing information, Section 12.6 Immunogenicity",
        "citation_urls": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761367s000lbl.pdf; https://pmc.ncbi.nlm.nih.gov/articles/PMC11804312/",
        "ada_source_url_primary": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761367s000lbl.pdf",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 12.6 Immunogenicity: VANGUARD 2.6% (1/39) ADA-positive; ADA did not affect PK, safety, or clinical response.",
        "verify_note": "Corrected unrelated stored PubMed link and replaced '<2%' with FDA label-confirmed 2.6%.",
    },
    "Gemtuzumab": {
        "ada_value": "Current MYLOTARG label states that immunogenicity was not studied in clinical trials using the recommended dose regimens; no confirmed numeric ADA incidence was found in retrievable official label text.",
        "ada_value_display": "Not studied using recommended dose regimens",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "assay_platform": "Not applicable/not studied in recommended-dose clinical trials",
        "pk_efficacy_impact": "Not stated",
        "evidence_source": "DailyMed/FDA MYLOTARG prescribing information, Section 6.3 Immunogenicity",
        "citation_urls": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=32fd2bb2-1cfa-4250-feb8-d7956c794e05; https://labeling.pfizer.com/ShowLabeling.aspx?id=15470",
        "ada_source_url_primary": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=32fd2bb2-1cfa-4250-feb8-d7956c794e05",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 6.3 Immunogenicity: immunogenicity of MYLOTARG was not studied in clinical trials using the recommended dose regimens.",
        "verify_note": "Cleared prior 1.1% value because official label does not confirm a numeric ADA rate for recommended dose regimens.",
    },
    "Golimumab": {
        "ada_value": "In the SIMPONI label, antibodies to golimumab were detected in 57 (4%) SIMPONI-treated patients across phase 3 RA, PsA, and AS trials through Week 24; concomitant MTX was associated with a lower antibody proportion (approximately 2% versus 7% without MTX). Most antibody-positive patients had neutralizing antibodies.",
        "ada_value_display": "4% anti-golimumab antibodies across phase 3 RA/PsA/AS trials",
        "ada_first_pct": 4.0,
        "nab_pct": "Most antibody-positive patients had neutralizing antibodies",
        "assay_platform": "ELISA; cell-based functional neutralizing assay",
        "pk_efficacy_impact": "Small number of antibody-positive patients limited definitive conclusions about efficacy or safety relationships.",
        "evidence_source": "FDA SIMPONI prescribing information, Immunogenicity section",
        "citation_urls": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2011/125289s0064lbl.pdf",
        "ada_source_url_primary": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2011/125289s0064lbl.pdf",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity: antibodies to SIMPONI detected in 57 (4%) treated patients through Week 24; approximately 2% with MTX versus 7% without MTX; most antibody-positive patients neutralizing.",
        "verify_note": "Normalized source fields and updated numeric value to label-confirmed 4%.",
    },
    "Guselkumab": {
        "ada_value": "In the current TREMFYA label, up to Week 52 approximately 6% of adult plaque psoriasis subjects developed ADA and approximately 7% of ADA-positive subjects had neutralizing antibodies; up to Week 156, approximately 9% developed ADA. Pediatric plaque psoriasis incidence was 18% (21/114), PsA was 2%, UC was 11% up to Week 56, and Crohn's disease was 5% to 9% depending on trial.",
        "ada_value_display": "Adult plaque psoriasis: 6% ADA to Week 52; 9% to Week 156; indication-specific rates 2-18%",
        "ada_first_pct": 6.0,
        "nab_pct": "Adult plaque psoriasis: approximately 7% of ADA-positive subjects neutralizing to Week 52",
        "assay_platform": "ADA and neutralizing antibody assays (label; method-dependent)",
        "pk_efficacy_impact": "Some ADA-positive subjects had lower trough levels and one adult psoriasis subject experienced loss of efficacy after high titers; generally no consistent clinical-response association was identified.",
        "evidence_source": "FDA TREMFYA prescribing information, Section 12.6 Immunogenicity",
        "citation_urls": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761061s028s029lbl.pdf",
        "ada_source_url_primary": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761061s028s029lbl.pdf",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 12.6 Immunogenicity: adult plaque psoriasis 6% ADA to Week 52 and 9% to Week 156; 7% of ADA-positive subjects neutralizing to Week 52; pediatric plaque psoriasis 18%, PsA 2%, UC 11%, Crohn's disease 5-9%.",
        "verify_note": "Replaced systematic-review 14.7% summary with current label indication-specific values; ada_first_pct uses adult plaque psoriasis Week 52 rate.",
    },
    "Inebilizumab": {
        "ada_value": "In UPLIZNA Study 1, treatment-emergent anti-inebilizumab-cdon antibodies were detected in 5.6% of patients receiving UPLIZNA. In Study 2, treatment-emergent antibodies occurred in 8.8% (6/68) during the 52-week randomized controlled period; neutralizing antibodies were not directly assessed.",
        "ada_value_display": "5.6% Study 1; 8.8% (6/68) Study 2",
        "ada_first_pct": 5.6,
        "nab_pct": "Neutralizing antibodies were not directly assessed in Study 2",
        "assay_platform": "ADA assay (label; method-dependent)",
        "pk_efficacy_impact": "No identified clinically significant ADA effect on PK, PD, safety, or effectiveness during Study 1 and Study 2 treatment periods.",
        "evidence_source": "FDA UPLIZNA prescribing information, Section 12.6 Immunogenicity",
        "citation_urls": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761142s003lbl.pdf; https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=834db232-afb0-4dcf-93e0-009ce8245c20",
        "ada_source_url_primary": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761142s003lbl.pdf",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 12.6 Immunogenicity: Study 1 treatment-emergent antibodies 5.6%; Study 2 8.8% (6/68); neutralizing antibodies not directly assessed; no clinically significant ADA effect identified.",
        "verify_note": "Corrected unrelated stored PubMed link and replaced 10-15% legacy display with label-confirmed 5.6%/8.8%.",
    },
    "Infliximab": {
        "ada_value": "The infliximab label states that in adult RA and Crohn's disease patients given a 3-dose induction regimen followed by maintenance dosing, antibodies to infliximab occurred in approximately 10% through 1 to 2 years. In PsA, antibodies occurred in 15%; in plaque psoriasis studies, rates ranged from 20% to 51% depending on dose/study. A drug-tolerant ECLIA method detected 52% in pediatric UC, higher than EIA due to higher sensitivity.",
        "ada_value_display": "Adult RA/CD EIA: approximately 10%; PsA 15%; psoriasis 20-51%; pediatric UC ECLIA 52%",
        "ada_first_pct": 10.0,
        "nab_pct": "Not separately specified in label excerpt",
        "assay_platform": "Original enzyme immunoassay (EIA); later drug-tolerant ECLIA in pediatric UC",
        "pk_efficacy_impact": "Antibody-positive patients were more likely to have higher clearance, reduced efficacy, and infusion reactions.",
        "evidence_source": "FDA infliximab prescribing information, Section 6.2 Immunogenicity",
        "citation_urls": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2021/103772s5401lbl.pdf",
        "ada_source_url_primary": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2021/103772s5401lbl.pdf",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 6.2 Immunogenicity: adult RA/CD approximately 10% through 1-2 years; PsA 15%; psoriasis 20-51%; pediatric UC EIA 7% and ECLIA 52%; antibody-positive patients more likely to have higher clearance, reduced efficacy, and infusion reactions.",
        "verify_note": "Normalized source fields from FDA label while preserving assay-dependent context.",
    },
    "Itolizumab": {
        "ada_value": "A peer-reviewed review summarizing the phase III psoriasis study states that 35 (15.75%) patients were ADA-positive: 31 (13.9%) developed ADAs for the first time and 4 (1.79%) had increased titers from baseline. No clinical correlation with adverse events or decreased efficacy was established.",
        "ada_value_display": "15.75% ADA-positive in phase III psoriasis study (35 patients)",
        "ada_first_pct": 15.75,
        "nab_pct": "Not stated",
        "assay_platform": "ADA assessment; platform not stated in retrieved review text",
        "pk_efficacy_impact": "No clinical correlation between increased ADA titers and adverse events or decreased efficacy was established.",
        "evidence_source": "PMC peer-reviewed review summarizing itolizumab phase III immunogenicity",
        "citation_urls": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4407739/; https://pubmed.ncbi.nlm.nih.gov/24703722/",
        "ada_source_url_primary": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4407739/",
        "ada_source_type_curated": "peer_reviewed_review",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity of Itolizumab: phase III study ADA-positive 35 (15.75%); 31 (13.9%) treatment-emergent, 4 (1.79%) increased titers; no clinical correlation with AEs or decreased efficacy.",
        "verify_note": "Corrected unrelated stored PMID; retained 15.75% based on retrievable PMC review text that cites the phase III study.",
    },
    "Ixekizumab": {
        "ada_value": "In the TALTZ label, by Week 12 approximately 9% of subjects treated every 2 weeks developed antibodies to ixekizumab; approximately 22% at the recommended dosing regimen developed antibodies during the 60-week treatment period. Approximately 10% of antibody-positive subjects, equivalent to 2% of treated subjects, had neutralizing antibodies; neutralizing antibodies were associated with reduced drug concentrations and loss of efficacy.",
        "ada_value_display": "9% by Week 12; 22% through 60 weeks; 2% treated subjects neutralizing",
        "ada_first_pct": 9.0,
        "nab_pct": "Approximately 2% of treated subjects at recommended regimen had neutralizing antibodies",
        "assay_platform": "ECL bridging immunoassay; neutralizing antibody assay with drug-interference limitations",
        "pk_efficacy_impact": "Neutralizing antibodies were associated with reduced drug concentrations and loss of efficacy.",
        "evidence_source": "FDA TALTZ prescribing information, Section 6.2 Immunogenicity",
        "citation_urls": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2016/125521s000lbl.pdf",
        "ada_source_url_primary": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2016/125521s000lbl.pdf",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 6.2 Immunogenicity: approximately 9% developed antibodies by Week 12; approximately 22% during 60-week treatment; about 2% of treated subjects had neutralizing antibodies associated with reduced drug concentration and loss of efficacy.",
        "verify_note": "Replaced pooled meta-analysis 14.29% value with label-confirmed indication/regimen-specific values; ada_first_pct uses Week 12 label rate.",
    },
    "Lanadelumab": {
        "ada_value": "In TAKHZYRO Trial 1 in adults and pediatric patients 12 years and older, 10 (12%) lanadelumab-flyo-treated and 2 (5%) placebo-treated patients had at least one ADA-positive sample during the 26-week treatment period; titers were low and two lanadelumab 150 mg q4wks patients had low-titer neutralizing antibodies. In an open-label pediatric study, 3/20 (15%) developed ADAs and one had neutralizing antibodies.",
        "ada_value_display": "12% ADA in Trial 1 (10 treated patients); two low-titer neutralizing",
        "ada_first_pct": 12.0,
        "nab_pct": "Two Trial 1 patients had low-titer neutralizing antibodies; pediatric open-label study: one neutralizing",
        "assay_platform": "ADA and neutralizing antibody assays (label; method-dependent)",
        "pk_efficacy_impact": "ADA including neutralizing antibodies did not appear to adversely affect PK, PD, safety, or clinical response.",
        "evidence_source": "FDA TAKHZYRO prescribing information, Section 12.6 Immunogenicity",
        "citation_urls": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/761090s010lbl.pdf; https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=15f99d8c-efe7-4f7d-aa20-0d0f1e30c6e8",
        "ada_source_url_primary": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/761090s010lbl.pdf",
        "ada_source_type_curated": "fda_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Section 12.6 Immunogenicity: Trial 1 10 (12%) lanadelumab-treated and 2 (5%) placebo-treated ADA-positive; titers low; two low-titer neutralizing; pediatric open-label 3/20 (15%) ADA and one neutralizing; no adverse PK/PD/safety/response effect.",
        "verify_note": "Corrected unrelated stored PubMed link; retained 12% using FDA label-confirmed Trial 1 value.",
    },
}

for col in set().union(*(entry.keys() for entry in updates.values())):
    if col not in df.columns:
        df[col] = pd.NA
    df[col] = df[col].astype("object")

for name, data in updates.items():
    mask = df["antibody_name"].fillna("").astype(str).str.casefold() == name.casefold()
    if mask.any():
        for col, val in data.items():
            df.loc[mask, col] = val
        print(f"Updated {name}")
    else:
        print(f"MISSING {name}")

df.to_csv(ada_path, index=False)
