import pandas as pd


ada_path = "data/immunogenicity_knowledge_base/master/ada_master_328_final_comprehensive.csv"
df = pd.read_csv(ada_path)

updates = {
    "Tarperprumig": {
        "ada_value": "ClinicalTrials.gov-derived results for NCT04631562 reported positive ADAs to ALXN1820 in 3/45 active-treated participants overall: 2/7 in Cohort 8 ALXN1820 150 mg SC weekly x5 and 1/6 in Cohort 9 ALXN1820 150 mg SC weekly x5; no ADA-positive participants were listed in single-dose active cohorts or placebo",
        "ada_value_display": "3/45 active-treated (6.7%); positives in repeated-dose SC cohorts",
        "ada_first_pct": 6.7,
        "nab_pct": "Not stated",
        "dose_mg": "12.5-2250 mg SC single or multiple ascending doses; 450 mg IV single dose",
        "dose_freq": "Single dose or weekly SC dosing for 3-5 weeks depending on cohort",
        "route_curated": "Subcutaneous; Intravenous",
        "assay_platform": "Positive antidrug antibodies to ALXN1820 reported in clinical trial results; assay platform not stated in retrieved registry text",
        "pk_efficacy_impact": "Published abstract/search result states ADA titers were mostly low and did not impact pharmacokinetics; registry result provides positive ADA counts by cohort",
        "evidence_source": "ClinicalTrials.gov-derived CDEK NCT04631562 result record; Veeva CTV NCT04631562 record; HRA ALXN1820 study summary; PubMed PMID 40134111",
        "citation_urls": "https://cdek.pharmacy.purdue.edu/trial/NCT04631562/; https://ctv.veeva.com/study/study-of-alxn1820-in-healthy-adult-participants; https://www.hra.nhs.uk/planning-and-improving-research/application-summaries/research-summaries/safety-pk-and-pd-study-of-alxn1820-in-healthy-adult-participants/; https://pubmed.ncbi.nlm.nih.gov/40134111/",
        "ada_source_url_primary": "https://cdek.pharmacy.purdue.edu/trial/NCT04631562/",
        "ada_source_pmids": "40134111",
        "ada_source_type_curated": "clinical_trial_registry",
        "ada_has_text_evidence": True,
        "ada_source_section": "Clinical result endpoint: Number of Participants With Positive Antidrug Antibodies (ADAs) to ALXN1820 SC and IV; counts show Cohort 8 2/7 and Cohort 9 1/6, with no positive count shown for other active cohorts or placebo.",
        "verify_note": "Replaced prior unsourced MSD/ECL 4.0% value with registry-count-derived 3/45 active-treated ADA positivity.",
    },
    "Tebotelimab": {
        "ada_value": "Tebotelimab anti-drug antibodies were detected in 17% of monotherapy-treated patients with available preliminary immunogenicity data; PK analyses confirmed exposure was not affected in ADA-positive patients",
        "ada_value_display": "17.0%",
        "ada_first_pct": 17.0,
        "nab_pct": "Not stated",
        "dose_mg": "1-1200 mg IV every 2 weeks in monotherapy dose escalation; 400-600 mg IV every 2 weeks in expansion cohorts depending on regimen",
        "dose_freq": "Every 2 weeks",
        "route_curated": "Intravenous",
        "assay_platform": "Anti-tebotelimab ADA detected in immunogenicity analysis; PK quantification used ELISA, specific ADA assay platform not stated in retrieved text",
        "pk_efficacy_impact": "For patients with detectable anti-drug antibodies, pharmacokinetic analyses confirmed tebotelimab exposure was not affected",
        "evidence_source": "Nature Medicine/PMC tebotelimab phase 1 trial; PubMed PMID 37857711; Nature extended data table",
        "citation_urls": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10667103/; https://pubmed.ncbi.nlm.nih.gov/37857711/; https://www.nature.com/articles/s41591-023-02593-0",
        "ada_source_url_primary": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10667103/",
        "ada_source_pmids": "37857711",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "PK/immunogenicity section: immunogenicity analysis was conducted on 269 monotherapy patients; tebotelimab ADAs were detected in 17% of monotherapy patients, 13% in dose escalation and 18% in cohort expansion; exposure was not affected.",
        "verify_note": "Corrected prior pending 2.0% value to source-confirmed 17.0%.",
    },
    "Tenatumomab": {
        "ada_value": "ADA/HAMA incidence not stated in retrieved tenatumomab public trial and drug sources",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "131I-tenatumomab dose escalation; exact administered dose not stated in retrieved summary",
        "dose_freq": "Not stated in retrieved public summary",
        "route_curated": "Intravenous radiolabeled antibody",
        "assay_platform": "Not stated in retrieved public sources",
        "pk_efficacy_impact": "NCT02602067 public summaries identify pharmacokinetics of tenatumomab in serum as a secondary objective, but no ADA/HAMA incidence or impact was retrieved",
        "evidence_source": "NCT02602067 public trial summaries; Synapse tenatumomab page; PMC tenascin-C/tenatumomab target-evaluation article",
        "citation_urls": "https://cdek.pharmacy.purdue.edu/trial/NCT02602067/; https://ctv.veeva.com/study/131iodine-tenatumomab-treatment-in-tenascin-c-positive-cancer-patients; https://synapse.patsnap.com/drug/c0751e94cd60404581260409287a582c; https://pmc.ncbi.nlm.nih.gov/articles/PMC5839400/",
        "ada_source_url_primary": "https://cdek.pharmacy.purdue.edu/trial/NCT02602067/",
        "ada_source_type_curated": "clinical_trial_registry",
        "ada_has_text_evidence": True,
        "ada_source_section": "Trial summaries describe 131I-tenatumomab phase 1 dose escalation with pharmacokinetics of tenatumomab in serum as an objective; no ADA, HAMA, or immunogenicity incidence is reported in retrieved text.",
        "verify_note": "Prior ELISA 70.0% value was not supported by retrieved tenatumomab source text.",
    },
    "Teneliximab": {
        "ada_value": "ADA incidence not stated in retrieved teneliximab/BMS-224819 public drug sources",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "Not stated in retrieved public sources",
        "dose_freq": "Not stated in retrieved public sources",
        "route_curated": "Not stated in retrieved public sources",
        "assay_platform": "Not stated in retrieved public sources",
        "pk_efficacy_impact": "Retrieved sources identify teneliximab/BMS-224819 as a mouse-human chimeric anti-CD40 IgG1 monoclonal antibody; no clinical ADA incidence or impact reported",
        "evidence_source": "NCATS/Inxight Drugs teneliximab page; Synapse teneliximab page; TargetMol teneliximab page",
        "citation_urls": "https://drugs.ncats.io/substance/G0MV33WQ6V; https://synapse.patsnap.com/drug/064cf910eab44b1f852a0f62c4391dbf; https://www.targetmol.com/compound/teneliximab",
        "ada_source_url_primary": "https://drugs.ncats.io/substance/G0MV33WQ6V",
        "ada_source_type_curated": "drug_database",
        "ada_has_text_evidence": True,
        "ada_source_section": "NCATS page identifies teneliximab/BMS-224819 as an investigational mouse-chimeric anti-CD40 IgG1 monoclonal antibody; no ADA or immunogenicity incidence is stated.",
        "verify_note": "Prior ELISA 12.0% value was not supported by retrieved teneliximab source text.",
    },
    "Tesidolumab": {
        "ada_value": "ADA incidence not stated in retrieved tesidolumab public clinical sources",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "20 mg/kg tesidolumab single IV dose in phase 1 DDI study",
        "dose_freq": "Single intravenous dose in retrieved DDI study",
        "route_curated": "Intravenous; Intravitreal formulations also investigated",
        "assay_platform": "No ADA assay platform stated in retrieved sources",
        "pk_efficacy_impact": "High-dose IVIg significantly reduced tesidolumab exposure in a phase 1 DDI study; ADA incidence was not reported in retrieved text",
        "evidence_source": "American Journal of Transplantation/ScienceDirect phase 1 tesidolumab-IVIg DDI study; IUPHAR/BPS tesidolumab clinical page; NCATS/Inxight Drugs tesidolumab page",
        "citation_urls": "https://www.sciencedirect.com/science/article/pii/S1600613522225763; https://www.guidetopharmacology.org/GRAC/LigandDisplayForward?ligandId=8711&tab=clinical; https://drugs.ncats.io/substance/3FO6689MSD",
        "ada_source_url_primary": "https://www.sciencedirect.com/science/article/pii/S1600613522225763",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Retrieved DDI study reports tesidolumab PK/PD and safety after 20 mg/kg IV dosing, but does not report ADA or immunogenicity incidence.",
        "verify_note": "Prior MSD 1.0% value was not supported by retrieved tesidolumab source text.",
    },
    "Timolumab": {
        "ada_value": "ADA samples were collected in the BUTEO timolumab/BTT1023 protocol, but numeric ADA incidence was not stated in retrieved protocol or final-result summary",
        "ada_value_display": "ADA assessed/planned; numeric not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "8 mg/kg BTT1023/timolumab starting and confirmed dose in PSC BUTEO study",
        "dose_freq": "IV infusions on days 1 and 8 and then biweekly, up to 7 infusions over 78 days",
        "route_curated": "Intravenous",
        "assay_platform": "Anti-drug antibody blood sampling planned; assay platform not stated in retrieved protocol text",
        "pk_efficacy_impact": "BUTEO final summary confirmed sufficient circulating levels and no short-term safety signals at 8 mg/kg, but no ADA incidence or impact was stated",
        "evidence_source": "BMJ Open/PMC BUTEO trial protocol; Oxford Experimental Medicine Division final-result summary; IUPHAR/BPS timolumab page",
        "citation_urls": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5734279/; https://www.expmedndm.ox.ac.uk/publications/1993441; https://www.guidetopharmacology.org/GRAC/LigandDisplayForward?ligandId=9097",
        "ada_source_url_primary": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5734279/",
        "ada_source_type_curated": "clinical_trial_document",
        "ada_has_text_evidence": True,
        "ada_source_section": "Protocol methods: serum was to be collected at specified time points for circulating BTT1023 levels and anti-drug antibodies; final-result summary did not state numeric ADA incidence.",
        "verify_note": "Prior MSD 4.0% value was not supported by retrieved timolumab/BTT1023 source text.",
    },
    "Tixentamig": {
        "ada_value": "ADA incidence not stated in retrieved tixentamig public drug/source pages",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "Not stated in retrieved public sources",
        "dose_freq": "Not stated in retrieved public sources",
        "route_curated": "Not stated in retrieved public sources",
        "assay_platform": "Not stated in retrieved public sources",
        "pk_efficacy_impact": "Retrieved NCATS and product/source pages identify tixentamig as an investigational CD3E x CLDN18 bispecific antibody; no clinical ADA incidence or impact reported",
        "evidence_source": "NCATS/Inxight Drugs tixentamig page; UNII/NDCList tixentamig page; Humimmu product page",
        "citation_urls": "https://drugs.ncats.io/drug/2X6WP45UD6; https://ndclist.com/unii/2x6wp45ud6; https://www.humimmu.com/products/anti-human-vegfa-cd274-bispecific-antibody-clone-pumitamig-ships-in-3-5-weeks-copy",
        "ada_source_url_primary": "https://drugs.ncats.io/drug/2X6WP45UD6",
        "ada_source_type_curated": "drug_database",
        "ada_has_text_evidence": True,
        "ada_source_section": "NCATS page identifies tixentamig as an investigational bispecific antibody targeting CD3E and CLDN18.2; no ADA or immunogenicity incidence is stated.",
        "verify_note": "Prior MSD/ECL 3.8% value was not supported by retrieved tixentamig source text.",
    },
    "Tosatoxumab": {
        "ada_value": "ADA incidence not stated in retrieved tosatoxumab/AR-301 public drug and clinical-development sources",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "Not stated in retrieved public drug pages",
        "dose_freq": "Not stated in retrieved public drug pages",
        "route_curated": "Intravenous",
        "assay_platform": "Not stated in retrieved public sources",
        "pk_efficacy_impact": "Retrieved sources identify tosatoxumab/AR-301 as a fully human IgG1 monoclonal antibody targeting Staphylococcus aureus alpha-toxin in pneumonia development; no ADA incidence or impact reported",
        "evidence_source": "IUPHAR/BPS tosatoxumab page; Synapse tosatoxumab page; Orphanet tosatoxumab/AR-301 page; Aridis AR-301 page",
        "citation_urls": "https://www.guidetopharmacology.org/GRAC/LigandDisplayForward?ligandId=13362&tab=clinical; https://synapse.patsnap.com/drug/68efe2fa325c4d5194ced9a25c6c3d64; https://www.orpha.net/en/drug/substance/299537?mode=pat&name=&region=&status=all; http://aridispharma.com/ar-301/",
        "ada_source_url_primary": "https://www.guidetopharmacology.org/GRAC/LigandDisplayForward?ligandId=13362&tab=clinical",
        "ada_source_type_curated": "drug_database",
        "ada_has_text_evidence": True,
        "ada_source_section": "Retrieved public pages identify tosatoxumab/AR-301 and clinical development context, but do not report ADA, anti-drug antibody, or immunogenicity incidence.",
        "verify_note": "Prior MSD 1.0% value was not supported by retrieved tosatoxumab source text.",
    },
}

for col in set().union(*(entry.keys() for entry in updates.values())):
    if col not in df.columns:
        df[col] = pd.NA
    df[col] = df[col].astype("object")

for name, data in updates.items():
    mask = df["antibody_name"].fillna("").astype(str).str.casefold() == name.casefold()
    if mask.any():
        for col, val in data.items():
            df.loc[mask, col] = val
        print(f"Updated {name}")
    else:
        print(f"MISSING {name}")

df.to_csv(ada_path, index=False)
