import pandas as pd


ada_path = "data/immunogenicity_knowledge_base/master/ada_master_328_final_comprehensive.csv"
df = pd.read_csv(ada_path)

updates = {
    "Ranibizumab PDS": {
        "ada_value": "In SUSVIMO-treated patients, anti-ranibizumab antibodies were reported in 12% (29/247) of AMD patients, 13% (41/320) of DME patients, and 17% (17/99) of DR patients; no clinically meaningful differences in PK, efficacy, or safety were observed",
        "ada_value_display": "12% AMD; 13% DME; 17% DR anti-ranibizumab antibodies",
        "ada_first_pct": 12.0,
        "nab_pct": "Not stated",
        "dose_mg": "Ranibizumab 100 mg/mL ocular implant refill-exchange every 24 weeks",
        "dose_freq": "Continuous delivery with refill-exchange approximately every 24 weeks",
        "route_curated": "Intravitreal via ocular implant",
        "assay_platform": "Serum samples evaluated for anti-ranibizumab antibodies; assay platform not stated in retrieved label text",
        "pk_efficacy_impact": "No clinically meaningful differences in pharmacokinetics, efficacy, or safety were observed in patients with anti-ranibizumab antibodies",
        "evidence_source": "Genentech SUSVIMO prescribing information",
        "citation_urls": "https://www.gene.com/download/pdf/susvimo_prescribing.pdf; https://www.drugs.com/pro/susvimo.html",
        "ada_source_url_primary": "https://www.gene.com/download/pdf/susvimo_prescribing.pdf",
        "ada_source_type_curated": "regulatory_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity section: after SUSVIMO implant insertion and treatment, anti-ranibizumab antibodies were detected in 12% (29/247) AMD, 13% (41/320) DME, and 17% (17/99) DR patients.",
        "verify_note": "Replaced prior broad 12-17% entry with label-specific indication counts.",
    },
    "Rovalpituzumab": {
        "ada_value": "ADA incidence not stated in retrieved rovalpituzumab tesirine public phase 1 and TRINITY phase 2 publications",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "0.3 mg/kg once every 6 weeks for two cycles in TRINITY",
        "dose_freq": "Every 6 weeks",
        "route_curated": "Intravenous",
        "assay_platform": "Not stated in retrieved public text",
        "pk_efficacy_impact": "Retrieved publications describe efficacy, safety, and PK but do not report ADA incidence or impact",
        "evidence_source": "TRINITY phase 2 rovalpituzumab tesirine study; Lancet Oncology first-in-human rovalpituzumab tesirine study",
        "citation_urls": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7105795/; https://pmc.ncbi.nlm.nih.gov/articles/PMC5481162/",
        "ada_source_url_primary": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7105795/",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Retrieved phase 1 and TRINITY phase 2 articles do not state ADA, anti-drug antibody, or immunogenicity incidence.",
        "verify_note": "Prior 2.0% value was not supported by retrieved rovalpituzumab source text.",
    },
    "Tisotumab": {
        "ada_value": "In recurrent or metastatic cervical cancer patients treated with TIVDAK 2 mg/kg every 3 weeks, anti-tisotumab vedotin-tftv antibody formation was 5.7% (12/211) in innovaTV 301 and 5.4% (5/93) in innovaTV 204",
        "ada_value_display": "5.7% (12/211) innovaTV 301; 5.4% (5/93) innovaTV 204",
        "ada_first_pct": 5.7,
        "nab_pct": "0% (0/211) in innovaTV 301 cell-based assay; 2.2% (2/93) in innovaTV 204 ELISA-based assay",
        "dose_mg": "2 mg/kg up to 200 mg IV every 3 weeks",
        "dose_freq": "Every 3 weeks",
        "route_curated": "Intravenous",
        "assay_platform": "Cell-based neutralizing antibody assay in innovaTV 301; ELISA-based neutralizing antibody assay in innovaTV 204",
        "pk_efficacy_impact": "Low ADA-positive counts prevented conclusions about immunogenicity effects on PK, efficacy, or safety",
        "evidence_source": "DailyMed/FDA TIVDAK prescribing information",
        "citation_urls": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c9fe3f32-4219-466e-acb9-3f609b4f4df1; https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761208s007lbl.pdf",
        "ada_source_url_primary": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c9fe3f32-4219-466e-acb9-3f609b4f4df1",
        "ada_source_type_curated": "regulatory_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity section: anti-tisotumab vedotin-tftv antibody formation was 5.7% (12/211) in innovaTV 301 and 5.4% (5/93) in innovaTV 204.",
        "verify_note": "Source-confirmed 5.7% label value retained.",
    },
    "Tremelimumab": {
        "ada_value": "In IMJUDO label immunogenicity data, 11% (20/182) of HIMALAYA ADA-evaluable patients tested positive for anti-tremelimumab-actl antibodies; in POSEIDON, 14% (38/278) tested positive",
        "ada_value_display": "11% HIMALAYA (20/182); 14% POSEIDON (38/278)",
        "ada_first_pct": 11.0,
        "nab_pct": "40% (8/20) of ADA-positive HIMALAYA patients and 82% (31/38) of ADA-positive POSEIDON patients were NAb-positive",
        "dose_mg": "300 mg single priming dose with durvalumab in HIMALAYA; 75 mg for up to five doses with durvalumab and platinum chemotherapy in POSEIDON",
        "dose_freq": "Single priming dose or every 3 weeks for up to five doses depending on regimen",
        "route_curated": "Intravenous",
        "assay_platform": "ADA and neutralizing antibody assessments described in label; assay method details not stated in retrieved label text",
        "pk_efficacy_impact": "No identified clinically significant effect on PK or safety; effect on effectiveness unknown",
        "evidence_source": "DailyMed/FDA IMJUDO prescribing information",
        "citation_urls": "https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=6690679c-be2f-4588-a2e4-89fff74dd6be; https://www.accessdata.fda.gov/drugsatfda_docs/label/2022/761289s001lbl.pdf",
        "ada_source_url_primary": "https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=6690679c-be2f-4588-a2e4-89fff74dd6be",
        "ada_source_type_curated": "regulatory_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity section: HIMALAYA 11% (20/182) ADA-positive, 40% (8/20) NAb-positive among ADA-positive; POSEIDON 14% (38/278) ADA-positive, 82% (31/38) NAb-positive among ADA-positive.",
        "verify_note": "Corrected prior broad 1.8-16.7% range to label-confirmed HIMALAYA and POSEIDON values.",
    },
    "Vatelizumab": {
        "ada_value": "Clinical ADA incidence not stated in retrieved vatelizumab public drug and trial sources",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "Not stated in retrieved public sources",
        "dose_freq": "Not stated in retrieved public sources",
        "route_curated": "Not stated in retrieved public sources",
        "assay_platform": "Anti-vatelizumab ADA reagent available for assay development; no clinical incidence found",
        "pk_efficacy_impact": "Retrieved public sources identify vatelizumab trials and ADA reagent availability but do not report clinical ADA incidence or impact",
        "evidence_source": "Creative Biolabs vatelizumab and anti-vatelizumab ADA reagent pages; Veeva EMPIRE trial page",
        "citation_urls": "https://www.creativebiolabs.net/Anti-Human-ITGA2-Therapeutic-Antibody-Vatelizumab-13732.htm; https://ctv.veeva.com/study/efficacy-and-safety-of-vatelizumab-in-patients-with-relapsing-remitting-multiple-sclerosis",
        "ada_source_url_primary": "https://www.creativebiolabs.net/Anti-Human-ITGA2-Therapeutic-Antibody-Vatelizumab-13732.htm",
        "ada_source_type_curated": "drug_database",
        "ada_has_text_evidence": True,
        "ada_source_section": "Retrieved vatelizumab-specific public pages do not report clinical ADA, anti-drug antibody, or immunogenicity incidence.",
        "verify_note": "Prior 2.0% value was not supported by retrieved vatelizumab source text.",
    },
    "Vibostolimab": {
        "ada_value": "Clinical ADA incidence not stated in retrieved vibostolimab public review and program sources",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "Dose varies by KEYVIBE study; not assigned from retrieved program review",
        "dose_freq": "Varies by study",
        "route_curated": "Intravenous",
        "assay_platform": "Not stated in retrieved public review text",
        "pk_efficacy_impact": "Retrieved KEYVIBE program review and first-in-human citation describe development program and safety/efficacy context but do not report ADA incidence",
        "evidence_source": "KEYVIBE program PMC review; PubMed first-in-human vibostolimab study citation; JITC pharmacology characterization article",
        "citation_urls": "https://pmc.ncbi.nlm.nih.gov/articles/PMC11497960/; https://pubmed.ncbi.nlm.nih.gov/34800678/; https://jitc.bmj.com/content/13/8/e008972",
        "ada_source_url_primary": "https://pmc.ncbi.nlm.nih.gov/articles/PMC11497960/",
        "ada_source_pmids": "34800678",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Retrieved vibostolimab public review and article pages do not state ADA, anti-drug antibody, or immunogenicity incidence.",
        "verify_note": "Prior 1.0% value was not supported by retrieved vibostolimab source text.",
    },
    "Visilizumab": {
        "ada_value": "In a 32-subject open-label phase 1 severe ulcerative colitis study, antibodies to visilizumab were detected in 7/31 patients (23%) with day 15 or day 30 samples available; antibodies in 6/7 patients were neutralizing",
        "ada_value_display": "23% (7/31 ADA-positive; 6/7 neutralizing)",
        "ada_first_pct": 23.0,
        "nab_pct": "6/7 ADA-positive patients had neutralizing antibodies",
        "dose_mg": "10 or 15 mcg/kg IV",
        "dose_freq": "Up to two doses 24 hours apart in the phase 1 severe UC study",
        "route_curated": "Intravenous",
        "assay_platform": "Antibodies to visilizumab detected by ELISA; cell-based bioassay used for neutralizing antibodies",
        "pk_efficacy_impact": "No evidence that antibody development affected safety, pharmacokinetics, or activity in the study",
        "evidence_source": "Gastroenterology phase 1 visilizumab severe ulcerative colitis article",
        "citation_urls": "https://cdr.lib.unc.edu/downloads/70795j26h; https://academic.oup.com/ibdjournal/article/16/4/620/4628305",
        "ada_source_url_primary": "https://cdr.lib.unc.edu/downloads/70795j26h",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity section: in 7 of 31 patients (23%) with day 15 or day 30 samples, antibodies to visilizumab were detected; antibodies in 6 of 7 were neutralizing.",
        "verify_note": "Corrected prior unsupported 2.0% value to source-confirmed 7/31 = 23%.",
    },
    "Vobarilizumab": {
        "ada_value": "Clinical ADA incidence not stated in retrieved vobarilizumab/ALX-0061 public trial and drug sources",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "Not stated as ADA-source-confirmed in retrieved public text",
        "dose_freq": "Subcutaneous regimens studied in RA and SLE programs",
        "route_curated": "Subcutaneous",
        "assay_platform": "Immunogenicity listed as a secondary objective in public trial source; numeric incidence not stated",
        "pk_efficacy_impact": "Retrieved sources describe clinical development and safety, but do not report ADA incidence or impact",
        "evidence_source": "Synapse vobarilizumab page; IUPHAR/BPS vobarilizumab page; Ablynx phase IIb public release search result",
        "citation_urls": "https://synapse.patsnap.com/drug/68af01cfff044f45b55b5cd8d32bf839; https://www.guidetopharmacology.org/GRAC/LigandDisplayForward?ligandId=8363&tab=clinical; https://drugs.ncats.io/drug/9OD8ISS64U",
        "ada_source_url_primary": "https://synapse.patsnap.com/drug/68af01cfff044f45b55b5cd8d32bf839",
        "ada_source_type_curated": "drug_database",
        "ada_has_text_evidence": True,
        "ada_source_section": "Retrieved vobarilizumab source lists immunogenicity as a secondary objective in SLE study but does not state anti-drug antibody incidence.",
        "verify_note": "Prior 31.0% value was not supported by retrieved vobarilizumab source text.",
    },
    "Zanolimumab": {
        "ada_value": "Clinical ADA incidence not stated in retrieved zanolimumab public clinical publications",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "980 mg dose reported in relapsed/refractory non-cutaneous peripheral T-cell lymphoma phase II trial",
        "dose_freq": "Not stated as ADA-source-confirmed in retrieved text",
        "route_curated": "Intravenous",
        "assay_platform": "Not stated in retrieved public clinical text",
        "pk_efficacy_impact": "Retrieved publications identify zanolimumab as a fully human anti-CD4 antibody and describe clinical activity/safety, but do not report ADA incidence or impact",
        "evidence_source": "British Journal of Haematology zanolimumab phase II trial; Expert Opinion review; DrugBank zanolimumab page",
        "citation_urls": "https://onlinelibrary.wiley.com/doi/10.1111/j.1365-2141.2010.08298.x; https://www.tandfonline.com/doi/full/10.1517/14712590802528696; https://go.drugbank.com/drugs/DB17376",
        "ada_source_url_primary": "https://onlinelibrary.wiley.com/doi/10.1111/j.1365-2141.2010.08298.x",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Retrieved zanolimumab clinical/public pages do not state ADA, anti-zanolimumab antibody, or immunogenicity incidence.",
        "verify_note": "Prior 2.0% value was not supported by retrieved zanolimumab source text.",
    },
    "Zenocutuzumab": {
        "ada_value": "In patients receiving BIZENGRI at the approved recommended dosage for up to 30 months, 7/153 (4.6%) developed anti-zenocutuzumab antibodies",
        "ada_value_display": "4.6% (7/153)",
        "ada_first_pct": 4.6,
        "nab_pct": "Not stated",
        "dose_mg": "750 mg IV every 2 weeks",
        "dose_freq": "Every 2 weeks",
        "route_curated": "Intravenous",
        "assay_platform": "Anti-drug antibody assessment described in label; assay method details not stated in retrieved label text",
        "pk_efficacy_impact": "Because of low ADA occurrence, effects on PK, PD, safety, and efficacy are unknown",
        "evidence_source": "DailyMed/FDA BIZENGRI prescribing information",
        "citation_urls": "https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=2a33e782-fc75-4dba-b77c-a44536ac13a5; https://www.bizengrihcp.com/pi",
        "ada_source_url_primary": "https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=2a33e782-fc75-4dba-b77c-a44536ac13a5",
        "ada_source_type_curated": "regulatory_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity section: 7 of 153 (4.6%) patients developed anti-zenocutuzumab antibodies.",
        "verify_note": "Corrected prior rounded 5.0% value to source-confirmed 4.6%.",
    },
}

for col in set().union(*(entry.keys() for entry in updates.values())):
    if col not in df.columns:
        df[col] = pd.NA
    df[col] = df[col].astype("object")

for name, data in updates.items():
    mask = df["antibody_name"].fillna("").astype(str).str.casefold() == name.casefold()
    if mask.any():
        for col, val in data.items():
            df.loc[mask, col] = val
        print(f"Updated {name}")
    else:
        print(f"MISSING {name}")

df.to_csv(ada_path, index=False)
