import pandas as pd


ada_path = "data/immunogenicity_knowledge_base/master/ada_master_328_final_comprehensive.csv"
df = pd.read_csv(ada_path)

updates = {
    "Brazikumab": {
        "ada_value": "Post-baseline anti-drug antibodies were detected in 2/104 patients in the 100-week open-label period of the phase 2a Crohn disease study; ADAs were transient and non-neutralizing",
        "ada_value_display": "2/104 post-baseline ADA-positive (1.9%); transient non-neutralizing",
        "ada_first_pct": 1.9,
        "nab_pct": "0%; post-baseline ADAs were reported as non-neutralizing",
        "dose_mg": "700 mg IV at weeks 0 and 4 followed by 210 mg SC every 4 weeks in the open-label period",
        "dose_freq": "IV induction then SC every 4 weeks",
        "route_curated": "Intravenous; Subcutaneous",
        "assay_platform": "Antidrug antibodies assessed at weeks 0, 8, 24, and 112 and 28 weeks after last dose",
        "pk_efficacy_impact": "Post-baseline ADAs were transient and non-neutralizing; no ADA-associated PK/safety impact was stated",
        "evidence_source": "BMC Gastroenterology/PMC open-label phase 2a brazikumab Crohn disease study",
        "citation_urls": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10731694/; https://bmcgastroenterol.biomedcentral.com/articles/10.1186/s12876-023-03078-7",
        "ada_source_url_primary": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10731694/",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Pharmacokinetics and immunogenicity section: post-baseline antidrug antibodies were detected in 2 patients, but were transient and non-neutralizing.",
        "verify_note": "Corrected prior 1.0% value to 2/104 = 1.9% from retrieved source text.",
    },
    "Briakinumab": {
        "ada_value": "ADA incidence not stated in retrieved briakinumab public clinical publications",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "200 mg at weeks 0 and 4 followed by 100 mg at week 8 and every 4 weeks in a 52-week psoriasis trial",
        "dose_freq": "Every 4 weeks after induction doses",
        "route_curated": "Subcutaneous",
        "assay_platform": "Not stated in retrieved public text",
        "pk_efficacy_impact": "Retrieved NEJM, Wiley, and British Journal of Dermatology pages describe efficacy and safety but do not state ADA incidence or impact",
        "evidence_source": "NEJM 52-week briakinumab versus methotrexate psoriasis trial; Wiley pooled safety analysis; British Journal of Dermatology trial page",
        "citation_urls": "https://www.nejm.org/doi/full/10.1056/NEJMoa1010858; https://onlinelibrary.wiley.com/doi/10.1111/j.1468-3083.2012.04705.x; https://academic.oup.com/bjd/article-abstract/165/3/661/6644288",
        "ada_source_url_primary": "https://www.nejm.org/doi/full/10.1056/NEJMoa1010858",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Retrieved briakinumab clinical publications contain no explicit anti-drug antibody, immunogenicity percentage, or neutralizing-antibody incidence in the available text.",
        "verify_note": "Prior 1.2% value was not supported by retrieved briakinumab source text.",
    },
    "Epratuzumab": {
        "ada_value": "In an initial 14-patient SLE trial, HAHA analysis gave no evidence of immunogenicity; all post-treatment values were below the 50 ng/mL assay sensitivity or not increased from baseline",
        "ada_value_display": "0.0% (no HAHA evidence in 14-patient SLE trial)",
        "ada_first_pct": 0.0,
        "nab_pct": "Not applicable; no HAHA evidence detected",
        "dose_mg": "360 mg/m2 IV every 2 weeks for 4 doses in the initial SLE trial",
        "dose_freq": "Every 2 weeks for 4 doses",
        "route_curated": "Intravenous",
        "assay_platform": "Competitive ELISA HAHA assay using epratuzumab capture and anti-epratuzumab idiotype probe",
        "pk_efficacy_impact": "No evidence of immunogenicity; epratuzumab serum levels remained measurable in available post-treatment samples",
        "evidence_source": "Arthritis Research & Therapy/PMC initial epratuzumab SLE clinical trial",
        "citation_urls": "https://pmc.ncbi.nlm.nih.gov/articles/PMC1526638/; https://arthritis-research.biomedcentral.com/articles/10.1186/ar1942",
        "ada_source_url_primary": "https://pmc.ncbi.nlm.nih.gov/articles/PMC1526638/",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Pharmacokinetics and immunogenicity section: HAHA analysis gave no evidence of immunogenicity, with all post-treatment values below assay sensitivity or not increased from baseline.",
        "verify_note": "Source-confirmed qualitative zero/no-evidence entry retained with explicit HAHA assay text.",
    },
    "Inotuzumab ozogamicin": {
        "ada_value": "7/236 (3%) patients with relapsed or refractory ALL tested positive for ADA against inotuzumab ozogamicin; no patients tested positive for neutralizing antibodies",
        "ada_value_display": "3.0% (7/236 ADA-positive; 0 NAb)",
        "ada_first_pct": 3.0,
        "nab_pct": "0%",
        "dose_mg": "1.8 mg/m2 per cycle fractionated as 0.8 mg/m2 day 1, 0.5 mg/m2 day 8, and 0.5 mg/m2 day 15 in cycle 1; subsequent cycles per label",
        "dose_freq": "Days 1, 8, and 15 of each cycle",
        "route_curated": "Intravenous",
        "assay_platform": "Electrochemiluminescence-based immunoassay for ADA; cell-based assay for neutralizing antibodies in ADA-positive samples",
        "pk_efficacy_impact": "Positive ADA did not affect clearance; too few ADA-positive patients to assess efficacy/safety impact",
        "evidence_source": "Pfizer BESPONSA prescribing information",
        "citation_urls": "https://labeling.pfizer.com/ShowLabeling.aspx?id=12535; https://www.pfizermedical.com/besponsa/clinical-pharmacology",
        "ada_source_url_primary": "https://labeling.pfizer.com/ShowLabeling.aspx?id=12535",
        "ada_source_type_curated": "regulatory_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity section: 7/236 (3%) patients tested positive for ADA; no patients tested positive for NAb; ADA did not affect clearance.",
        "verify_note": "Source-confirmed 3.0% label value retained.",
    },
    "Loncastuximab tesirine": {
        "ada_value": "0/134 patients tested positive for antibodies against loncastuximab tesirine-lpyl after treatment in LOTIS-2",
        "ada_value_display": "0% (0/134)",
        "ada_first_pct": 0.0,
        "nab_pct": "Not applicable; no treatment-emergent antibodies detected",
        "dose_mg": "0.15 mg/kg every 3 weeks for 2 cycles followed by 0.075 mg/kg every 3 weeks",
        "dose_freq": "Every 3 weeks",
        "route_curated": "Intravenous",
        "assay_platform": "Antibody testing described in prescribing information; assay method details not stated in retrieved label text",
        "pk_efficacy_impact": "Potential ADA effect on PK, efficacy, or safety is unknown; no antibodies detected in LOTIS-2",
        "evidence_source": "DailyMed/FDA ZYNLONTA prescribing information",
        "citation_urls": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=af54af12-3edf-4301-8bc5-0446bc813c1d; https://www.zynlonta.com/zynlonta-pi/",
        "ada_source_url_primary": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=af54af12-3edf-4301-8bc5-0446bc813c1d",
        "ada_source_type_curated": "regulatory_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity section: In LOTIS-2, 0 of 134 patients tested positive for antibodies against loncastuximab tesirine-lpyl after treatment.",
        "verify_note": "Corrected prior inconsistent ada_first_pct 2.3 to source-confirmed 0.0%.",
    },
    "Ocrelizumab": {
        "ada_value": "12/1311 ocrelizumab-treated MS clinical-trial patients tested positive for ADAs; 2 patients tested positive for neutralizing antibodies",
        "ada_value_display": "approximately 1% (12/1311 ADA-positive; 2 NAb-positive)",
        "ada_first_pct": 1.0,
        "nab_pct": "2/1311 NAb-positive among ocrelizumab-treated patients",
        "dose_mg": "Initial 300 mg IV infusion followed two weeks later by 300 mg IV; subsequent 600 mg IV every 6 months",
        "dose_freq": "Every 6 months after initial split dosing",
        "route_curated": "Intravenous",
        "assay_platform": "Serum samples tested for anti-drug antibodies at multiple timepoints; neutralizing antibodies tested in ADA-positive samples",
        "pk_efficacy_impact": "Data not adequate to assess ADA impact on safety and efficacy",
        "evidence_source": "FDA OCREVUS prescribing information",
        "citation_urls": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2018/761053s012lbl.pdf; https://www.ema.europa.eu/en/documents/product-information/ocrevus-epar-product-information_en.pdf",
        "ada_source_url_primary": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2018/761053s012lbl.pdf",
        "ada_source_type_curated": "regulatory_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity section: out of 1311 patients treated with OCREVUS, 12 (~1%) tested positive for ADAs, of which 2 tested positive for neutralizing antibodies.",
        "verify_note": "Source-confirmed label value retained.",
    },
    "Ontamalimab": {
        "ada_value": "In the TURANDOT II open-label extension, the proportion of patients with ADAs was 6.3% at baseline (19/301); four of these 19 patients had neutralizing antibodies. ADA status had no impact on serum ontamalimab concentrations.",
        "ada_value_display": "6.3% at TURANDOT II baseline (19/301; 4 NAb-positive)",
        "ada_first_pct": 6.3,
        "nab_pct": "4/19 ADA-positive patients had NAbs at TURANDOT II baseline",
        "dose_mg": "75 mg or 225 mg SC every 4 weeks in TURANDOT II",
        "dose_freq": "Every 4 weeks",
        "route_curated": "Subcutaneous",
        "assay_platform": "ADA assay with high tolerance to soluble MAdCAM-1 and ontamalimab; ADA positive status summarized by log2 titer",
        "pk_efficacy_impact": "ADA status did not impact serum ontamalimab concentrations; no ADA-associated hypersensitivity reactions reported",
        "evidence_source": "Journal of Crohn's and Colitis/PMC TURANDOT II ontamalimab open-label extension study; PubMed PMID 33599720",
        "citation_urls": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8218706/; https://pubmed.ncbi.nlm.nih.gov/33599720/",
        "ada_source_url_primary": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8218706/",
        "ada_source_pmids": "33599720",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Safety, pharmacokinetics, and immunogenicity section: proportion of patients with ADAs was 6.3% at TURANDOT II baseline (19/301), four had NAbs, and ADA status had no impact on serum ontamalimab concentrations.",
        "verify_note": "Corrected prior unsupported 2.0% value to source-confirmed 19/301 = 6.3%.",
    },
    "Palivizumab": {
        "ada_value": "In Trial 1, anti-Synagis antibody after the fourth injection was 1.1% in placebo and 0.7% in the Synagis group; reactivity was transient and not associated with adverse events or altered serum concentrations",
        "ada_value_display": "0.7% (Synagis group); 1.1% placebo group",
        "ada_first_pct": 0.7,
        "nab_pct": "Not stated",
        "dose_mg": "15 mg/kg IM monthly during RSV season",
        "dose_freq": "Monthly",
        "route_curated": "Intramuscular",
        "assay_platform": "ELISA assay for anti-Synagis antibodies",
        "pk_efficacy_impact": "Anti-Synagis reactivity was transient and not associated with adverse events or alteration in serum concentrations",
        "evidence_source": "FDA Synagis label",
        "citation_urls": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2009/103770s5116lbl.pdf; https://www.ema.europa.eu/en/documents/product-information/synagis-epar-product-information_en.pdf",
        "ada_source_url_primary": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2009/103770s5116lbl.pdf",
        "ada_source_type_curated": "regulatory_label",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity section: incidence of anti-Synagis antibody following the fourth injection was 1.1% in placebo and 0.7% in Synagis group; results based on ELISA assay.",
        "verify_note": "Source-confirmed label value retained.",
    },
}

for col in set().union(*(entry.keys() for entry in updates.values())):
    if col not in df.columns:
        df[col] = pd.NA
    df[col] = df[col].astype("object")

for name, data in updates.items():
    mask = df["antibody_name"].fillna("").astype(str).str.casefold() == name.casefold()
    if mask.any():
        for col, val in data.items():
            df.loc[mask, col] = val
        print(f"Updated {name}")
    else:
        print(f"MISSING {name}")

df.to_csv(ada_path, index=False)
