import pandas as pd


ada_path = "data/immunogenicity_knowledge_base/master/ada_master_328_final_comprehensive.csv"
df = pd.read_csv(ada_path)

updates = {
    "Sirukumab": {
        "ada_value": "0/31 subjects with appropriate samples were classified as positive for antibodies to sirukumab through week 20 in the first-in-human healthy-volunteer study",
        "ada_value_display": "0.0% (0/31)",
        "ada_first_pct": 0.0,
        "nab_pct": "Not applicable; no antibodies to sirukumab detected",
        "dose_mg": "0.3, 1, 3, 6, or 10 mg/kg single IV infusion in first-in-human study; 50 mg SC every 4 weeks or 100 mg SC every 2 weeks in RA phase 3 studies",
        "dose_freq": "Single IV infusion in healthy-volunteer study; repeated SC dosing in RA studies",
        "route_curated": "Intravenous; Subcutaneous",
        "assay_platform": "Validated antigen bridging enzyme immunoassay for antibodies to sirukumab; serum sirukumab measured by electrochemiluminescent immunoassay",
        "pk_efficacy_impact": "No antibodies to sirukumab were detected in the first-in-human study; no ADA impact reported",
        "evidence_source": "British Journal of Clinical Pharmacology/PMC first-in-human sirukumab study; PubMed PMID 21392075; RMD Open SIRROUND-D study",
        "citation_urls": "https://pmc.ncbi.nlm.nih.gov/articles/PMC3162657/; https://pubmed.ncbi.nlm.nih.gov/21392075/; https://rmdopen.bmj.com/content/4/2/e000731",
        "ada_source_url_primary": "https://pmc.ncbi.nlm.nih.gov/articles/PMC3162657/",
        "ada_source_pmids": "21392075",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity section: antibodies to sirukumab were evaluated in all subjects at baseline and weeks 6 and 20; none of the 31 subjects with appropriate samples was classified as positive through week 20.",
        "verify_note": "Corrected prior unsourced 10.0% value to source-confirmed 0/31 in the retrieved first-in-human study.",
    },
    "Sonelokimab (M1095)": {
        "ada_value": "Clinical ADA incidence not stated in retrieved sonelokimab public trial and publication sources; registries list PK/immunogenicity assessment as an objective",
        "ada_value_display": "ADA assessed/planned; numeric not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "60 or 120 mg in PsA phase 2 ARGO study; 120 or 240 mg in HS phase 2 study",
        "dose_freq": "Subcutaneous induction at weeks 0, 2, 4, and 6 followed by every 4 weeks in PsA; repeated SC dosing through week 20 in HS registry",
        "route_curated": "Subcutaneous",
        "assay_platform": "Immunogenicity assessment planned or assessed; assay platform not stated in retrieved public text",
        "pk_efficacy_impact": "Retrieved PsA Nature Medicine article and trial registries describe efficacy, safety, PK, and immunogenicity objectives but do not state numeric ADA incidence or impact",
        "evidence_source": "Nature Medicine sonelokimab PsA phase 2 article; EudraCT 2021-005947-58; Research with human participants M1095-HS-201 record",
        "citation_urls": "https://nature.com/articles/s41591-025-03971-6; https://pubmed.ncbi.nlm.nih.gov/41053449/; https://www.clinicaltrialsregister.eu/ctr-search/trial/2021-005947-58/CZ; https://onderzoekmetmensen.nl/en/trial/51658",
        "ada_source_url_primary": "https://www.clinicaltrialsregister.eu/ctr-search/trial/2021-005947-58/CZ",
        "ada_source_pmids": "41053449",
        "ada_source_type_curated": "clinical_trial_registry",
        "ada_has_text_evidence": True,
        "ada_source_section": "EudraCT/HS registry secondary objective: assess pharmacokinetics and immunogenicity of sonelokimab; retrieved publication and registries do not report numeric anti-drug antibody incidence.",
        "verify_note": "Prior 50.0% value was not supported by retrieved sonelokimab source text.",
    },
    "Stamulumab": {
        "ada_value": "Clinical ADA incidence not stated in retrieved MYO-029/stamulumab phase I/II source; hypersensitivity skin reactions were reported at higher doses",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "1, 3, 10, or 30 mg/kg MYO-029",
        "dose_freq": "Intravenous administration every 2 weeks for 6 months, total 13 doses",
        "route_curated": "Intravenous",
        "assay_platform": "No ADA assay platform stated in retrieved clinical article",
        "pk_efficacy_impact": "Phase I/II trial reported cutaneous hypersensitivity at 10 and 30 mg/kg and limited dose escalation; no ADA incidence or PK impact stated",
        "evidence_source": "Annals of Neurology phase I/II MYO-029 muscular dystrophy trial PDF; DrugBank/Synapse drug pages",
        "citation_urls": "https://www.aica3.org/cms/wp-content/uploads/2013/09/A-Phase-III-trial-of-MYO-029-in-Adult-Subjects-with-Muscular-Dystrophy.pdf; https://go.drugbank.com/drugs/DB05915; https://synapse.patsnap.com/drug/8f6723bbd71844b2b02ccdda4781e855",
        "ada_source_url_primary": "https://www.aica3.org/cms/wp-content/uploads/2013/09/A-Phase-III-trial-of-MYO-029-in-Adult-Subjects-with-Muscular-Dystrophy.pdf",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Trial methods/results describe IV MYO-029 dosing and hypersensitivity skin reactions but do not report ADA, anti-MYO-029 antibody, or neutralizing-antibody incidence.",
        "verify_note": "Prior MSD/ECL 2.0% value was not supported by retrieved stamulumab/MYO-029 source text.",
    },
    "Suvratoxumab": {
        "ada_value": "Four MEDI4893-treated subjects tested positive for ADA at any time; three had baseline positivity and one 5000 mg subject was positive on day 151 only. All had low ADA titer <=1:30, none were positive at end of study, and transient ADA was not associated with safety or PK impact.",
        "ada_value_display": "1/26 post-baseline-only (3.8%); 4/26 ever ADA-positive",
        "ada_first_pct": 3.8,
        "nab_pct": "Not stated for ADA; anti-alpha-toxin neutralizing antibody activity was pharmacodynamic target engagement, not anti-drug NAb",
        "dose_mg": "225, 750, 2250, or 5000 mg single IV infusion in phase 1 healthy-adult study; phase 2 SAATELLITE protocol used single IV dose-ranging in mechanically ventilated ICU subjects",
        "dose_freq": "Single intravenous infusion",
        "route_curated": "Intravenous",
        "assay_platform": "Serum ADA testing reported in phase 1 study; protocol listed serum MEDI4893 ADA response through 90 days as a secondary endpoint",
        "pk_efficacy_impact": "Transient low-titer ADA was not associated with adverse events or impact on MEDI4893 pharmacokinetics",
        "evidence_source": "Antimicrobial Agents and Chemotherapy phase 1 MEDI4893 study; Clinical & Translational Immunology MEDI4893 analysis; SAATELLITE protocol",
        "citation_urls": "https://journals.asm.org/doi/10.1128/aac.01020-16; https://pmc.ncbi.nlm.nih.gov/articles/PMC5822409/; https://s3.amazonaws.com/ctr-med-7111/CD-ID-MEDI4893-1139/516e4676-ac10-48ef-8f1b-f2c3bacfc92f/dd5f4d36-44fe-420c-97fc-ba475e4c2a3a/CD-ID-MEDI4893-1139_Protocol_amendment_5_redacted_FINAL_APPROVED-v1.pdf",
        "ada_source_url_primary": "https://journals.asm.org/doi/10.1128/aac.01020-16",
        "ada_source_pmids": "29484186",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Phase 1 ADA result: four subjects tested positive for MEDI4893 ADA; one was baseline-only, two were baseline and day 151, one was day-151-only; all titers <=1:30, none positive at end of study, and transient ADA was not associated with safety or PK impact.",
        "verify_note": "Replaced prior pending/0.0% entry with route/source-specific ADA count; ada_first_pct records the post-baseline-only fraction (1/26).",
    },
    "Tacatuzumab": {
        "ada_value": "ADA/HAHA incidence not stated in retrieved tacatuzumab public drug/source pages",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "Not stated in retrieved public tacatuzumab sources",
        "dose_freq": "Not stated in retrieved public tacatuzumab sources",
        "route_curated": "Intravenous radiolabeled antibody conjugate",
        "assay_platform": "Not stated in retrieved public tacatuzumab sources",
        "pk_efficacy_impact": "Retrieved sources identify yttrium Y-90 tacatuzumab tetraxetan/HuAFP31/AFP-Cide as a humanized mouse IgG1 monoclonal antibody conjugate targeting AFP; no ADA or HAHA incidence reported",
        "evidence_source": "NCATS/Inxight Drugs yttrium Y-90 tacatuzumab tetraxetan page; ADC Review tacatuzumab tetraxetan drug map; CISMeF/NCI drug page search result",
        "citation_urls": "https://drugs.ncats.io/substance/GJ2416WK6Y; https://www.adcreview.com/drugmap/tacatuzumab-tetraxetan/; https://www.cismef.org/page/detail/en/NCI_CO_C48428",
        "ada_source_url_primary": "https://drugs.ncats.io/substance/GJ2416WK6Y",
        "ada_source_type_curated": "drug_database",
        "ada_has_text_evidence": True,
        "ada_source_section": "Retrieved tacatuzumab-specific sources identify the drug and antibody origin but do not report immunogenicity, ADA, HAHA, or neutralizing-antibody incidence.",
        "verify_note": "Prior MSD 15.0% value was not supported by retrieved tacatuzumab source text; clivatuzumab HAHA data were not assigned to tacatuzumab.",
    },
    "Tadocizumab": {
        "ada_value": "ADA incidence not stated in retrieved tadocizumab/YM-337 public clinical and drug sources",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "Not stated in retrieved public clinical summary; YM337 infusion studied with ASA/UFH in healthy volunteers",
        "dose_freq": "Not stated in retrieved public clinical summary",
        "route_curated": "Intravenous",
        "assay_platform": "Not stated in retrieved public sources",
        "pk_efficacy_impact": "Retrieved sources identify tadocizumab/YM-337 as a humanized monoclonal antibody against platelet GP IIb/IIIa used in antiplatelet pharmacodynamic studies; no ADA incidence or impact stated",
        "evidence_source": "KEGG DRUG D06649; Synapse tadocizumab page; TargetMol tadocizumab page; British Journal of Clinical Pharmacology YM337 pharmacodynamic study summary",
        "citation_urls": "https://www.kegg.jp/entry/D06649; https://synapse.patsnap.com/drug/0e0b85b8d21541cb8f44ad79d904db62; https://www.targetmol.com/compound/tadocizumab",
        "ada_source_url_primary": "https://www.kegg.jp/entry/D06649",
        "ada_source_type_curated": "drug_database",
        "ada_has_text_evidence": True,
        "ada_source_section": "Retrieved public pages describe tadocizumab/YM-337 identity, target, and clinical pharmacodynamic use but do not state ADA or immunogenicity incidence.",
        "verify_note": "Prior ELISA 8.0% value was not supported by retrieved tadocizumab source text.",
    },
    "Talizumab": {
        "ada_value": "ADA incidence not stated in retrieved talizumab/TNX-901 public clinical-review and drug sources",
        "ada_value_display": "Not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Not stated",
        "dose_mg": "150-450 mg once monthly subcutaneous talizumab in peanut allergy trial summary",
        "dose_freq": "Once monthly in retrieved food-allergy review summary",
        "route_curated": "Subcutaneous",
        "assay_platform": "Not stated in retrieved public sources",
        "pk_efficacy_impact": "Retrieved sources describe talizumab/TNX-901 as the first humanized anti-IgE antibody studied in food allergy and report peanut challenge efficacy, but no ADA incidence or impact",
        "evidence_source": "World Allergy Organization Journal ligelizumab/food allergy review; MedChemExpress talizumab product page; PubMed anti-IgE biologics review",
        "citation_urls": "https://boris-portal.unibe.ch/bitstreams/8814b701-8910-479f-8c65-6d438f5e2e6f/download; https://www.medchemexpress.com/talizumab.html; https://pubmed.ncbi.nlm.nih.gov/32249957/",
        "ada_source_url_primary": "https://boris-portal.unibe.ch/bitstreams/8814b701-8910-479f-8c65-6d438f5e2e6f/download",
        "ada_source_pmids": "32249957",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Retrieved review states talizumab/TNX-901 was studied in food allergy and 150-450 mg monthly SC dosing increased peanut reaction threshold; retrieved sources do not state ADA, anti-drug antibody, or immunogenicity incidence.",
        "verify_note": "Prior MSD 4.0% value was not supported by retrieved talizumab/TNX-901 source text; FDA TALTZ/ixekizumab label result was excluded as a wrong-antibody hit.",
    },
    "Tarextumab": {
        "ada_value": "ADA and neutralizing-antibody assessments were performed or planned in retrieved tarextumab sources; numeric ADA incidence was not stated in the retrieved phase 1 article or registry text",
        "ada_value_display": "ADA assessed; numeric not stated",
        "ada_first_pct": pd.NA,
        "nab_pct": "Neutralizing antibody assay planned for ADA-positive samples; numeric NAb incidence not stated",
        "dose_mg": "0.5, 1, 2.5, or 5 mg/kg weekly; 5, 7.5, or 10 mg/kg every other week; 7.5 mg/kg every 3 weeks",
        "dose_freq": "Weekly, every other week, or every 3 weeks depending on cohort",
        "route_curated": "Intravenous",
        "assay_platform": "Fully validated standard bridging format ELISA for ADA; fully validated standard binding format ELISA for NAb in ADA-positive samples",
        "pk_efficacy_impact": "Retrieved phase 1 article reports PK and immunogenicity methods but does not state numeric ADA or NAb incidence; ClinicalTrials.gov lists rate of neutralizing antibodies as an immunogenicity outcome",
        "evidence_source": "Invest New Drugs/PMC tarextumab phase 1 article; PubMed PMID 30591982; ClinicalTrials.gov NCT01277146",
        "citation_urls": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6647865/; https://pubmed.ncbi.nlm.nih.gov/30591982/; https://clinicaltrials.gov/study/NCT01277146",
        "ada_source_url_primary": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6647865/",
        "ada_source_pmids": "30591982",
        "ada_source_type_curated": "peer_reviewed_article",
        "ada_has_text_evidence": True,
        "ada_source_section": "Immunogenicity methods: serum samples were obtained at baseline, every 4 weeks, treatment termination, and follow-up; ADA tested by validated bridging ELISA and ADA-positive samples tested for NAb by binding ELISA. No numeric ADA result was stated in retrieved text.",
        "verify_note": "Prior MSD 15.0% value was not supported by retrieved tarextumab source text.",
    },
}

for col in set().union(*(entry.keys() for entry in updates.values())):
    if col not in df.columns:
        df[col] = pd.NA
    df[col] = df[col].astype("object")

for name, data in updates.items():
    mask = df["antibody_name"].fillna("").astype(str).str.casefold() == name.casefold()
    if mask.any():
        for col, val in data.items():
            df.loc[mask, col] = val
        print(f"Updated {name}")
    else:
        print(f"MISSING {name}")

df.to_csv(ada_path, index=False)
