"""
Step 4: Apply structural revisions to the frontiers_immunology full draft.

Rules identical to _revise_manuscript.py:
- New Introduction (5-para funnel matching expert cadence)
- Discussion: replace generic opener with strongest-finding-first
- Strip boilerplate transition phrases from all sections
- Abstract already has BMRC labels from generation — keep as-is
- All sentences are original; no content copied from any reference article

Input:  smoke/huNSG_QUAD_frontiers_20260527T043823Z.json  (or latest)
Output: smoke/huNSG_QUAD_frontiers_revised.json
        smoke/huNSG_QUAD_frontiers_revised.txt
"""

import json
import re
from pathlib import Path

SMOKE = Path(__file__).resolve().parent

# Pick latest frontiers draft
candidates = sorted(SMOKE.glob("huNSG_QUAD_frontiers_2*.json"), reverse=True)
if not candidates:
    raise FileNotFoundError("No huNSG_QUAD_frontiers_*.json found in smoke/")
SRC = candidates[0]
print(f"Source: {SRC.name}")

JOUT = SMOKE / "huNSG_QUAD_frontiers_revised.json"
TOUT = SMOKE / "huNSG_QUAD_frontiers_revised.txt"

d    = json.loads(SRC.read_text(encoding="utf-8"))
secs = {s["key"]: s for s in d["sections"]}
refs = d.get("merged_reference_list") or []
plan = d.get("plan") or {}

# ── 1. ABSTRACT — keep exactly as generated (BMRC labels present) ────────────
ABSTRACT = secs["abstract"]["text"]

# ── 2. INTRODUCTION  (5-paragraph funnel, original sentences) ────────────────
INTRODUCTION = """\
Innate immune cells are the first responders to infection and tissue damage, detecting \
conserved microbial and danger signals through pattern-recognition receptor families and \
initiating downstream signaling cascades that shape both local and systemic inflammation. \
Among the best-characterized of these are NF-κB-dependent transcription, which drives \
pro-inflammatory cytokine gene expression; type I interferon signaling, which coordinates \
antiviral and immunomodulatory programs; and NLRP3 inflammasome activation, which mediates \
post-translational processing of interleukin-1β and interleukin-18 [CITE: NLRP3 inflammasome]. \
Dysregulation of these pathways underlies sepsis, autoinflammatory syndromes, inflammatory \
bowel disease, and a growing spectrum of complex disorders [CITE: innate immunity inflammatory disease].

Despite extensive mechanistic work in mouse models, translating preclinical innate immunity \
research into effective human therapies has proven consistently difficult. The innate immune \
system exhibits striking species differences: human and murine Toll-like receptor repertoires, \
cytokine networks, and inflammasome compositions diverge at multiple levels, meaning that \
conclusions drawn from mouse experiments do not reliably predict human biology or clinical drug \
responses [CITE: mouse human immune differences]. Studying human-specific innate immune mechanisms \
therefore requires experimental systems that cannot be replicated in standard inbred mouse strains.

Humanized mouse models, generated by engrafting human hematopoietic stem and progenitor cells \
(HSPCs) into immunodeficient hosts, offer a partial solution. NOD-scid-Il2rγ−/− (NSG) mice \
support efficient HSPC engraftment and have enabled advances in human adaptive immunology; however, \
the absence of cross-reactive human myeloid growth factor signaling results in poor reconstitution \
of human monocytes, dendritic cells, and granulocytes in standard NSG mice [CITE: humanized mouse NSG myeloid]. \
This myeloid deficiency severely restricts the utility of conventional humanized mouse platforms \
for innate immunity research.

Transgenic expression of human myeloid growth factors can rescue this limitation. NSG-SGM3 mice, \
expressing human SCF, GM-CSF, and IL-3, markedly improve granulocyte and monocyte reconstitution, \
while NSG-CSF1 mice, expressing human CSF1, selectively enhance macrophage and monocyte development. \
NSG-QUAD mice combine all four transgenes—IL-3, GM-CSF, SCF, and CSF1—creating a host environment \
that simultaneously supports multiple branches of human myelopoiesis [CITE: NSG-QUAD transgenic myeloid]. \
Whether this expanded myeloid compartment translates into functional innate immune competence in vivo \
has not been systematically established.

Here we report that humanized NSG-QUAD mice reconstituted with human HSPCs develop a diversified \
human myeloid compartment across blood, spleen, and liver by 6 weeks post-engraftment and mount \
coordinated NF-κB, type I interferon, and NLRP3 inflammasome responses to both systemic and mucosal \
LPS challenge. Using the selective NLRP3 inhibitor MCC950, we demonstrate pathway-specific \
pharmacological modulation, establishing humanized NSG-QUAD mice as a tractable in vivo platform \
for studying human innate immunity and evaluating therapeutics that target these pathways.\
"""

# ── 3. METHODS — keep AI draft as-is ─────────────────────────────────────────
METHODS = secs["methods"]["text"]

# ── 4. RESULTS — strip boilerplate, keep data ────────────────────────────────
results_raw = secs["results"]["text"]

_BOILERPLATE = [
    r"These findings demonstrate that[^\.]+\.",
    r"Collectively,?\s+these results[^\.]+\.",
    r"Taken together,?[^\.]+\.",
    r"These results suggest that[^\.]+\.",
    r"These data indicate that[^\.]+\.",
    r"Together,?\s+these findings[^\.]+\.",
    r"Collectively,?\s+these data[^\.]+\.",
    r"In summary,?\s+these[^\.]+\.",
]

def _strip_boilerplate(text: str) -> str:
    for pat in _BOILERPLATE:
        text = re.sub(pat, "", text, flags=re.IGNORECASE)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()

RESULTS = _strip_boilerplate(results_raw)

# ── 5. DISCUSSION — replace generic opener; strip boilerplate chains ──────────
discussion_raw = secs["discussion"]["text"]

# Find and replace the first sentence (generic openers the model favors)
_OPENER_PAT = re.compile(
    r"^(The|In this|We |This |Humanized)[^\n]+?\.",
    re.MULTILINE,
)
STRONG_OPENER = (
    "The central finding of this study is that humanized NSG-QUAD mice mount coordinated, "
    "pharmacologically separable human innate immune responses in vivo—encompassing NF-κB-dependent "
    "cytokine production, type I interferon signaling, and NLRP3 inflammasome activation—across "
    "both systemic and mucosal compartments."
)
# Replace first matching opener only
discussion_text = _OPENER_PAT.sub(STRONG_OPENER, discussion_raw, count=1)
# Trim weak connectors at sentence start
for phrase in (r"\bFurthermore,\s*", r"\bMoreover,\s*", r"\bAdditionally,\s*", r"\bNotably,\s*"):
    discussion_text = re.sub(phrase, "", discussion_text)
discussion_text = _strip_boilerplate(discussion_text)

DISCUSSION = discussion_text

# ── Assemble ──────────────────────────────────────────────────────────────────
revised_sections = [
    {"key": "abstract",      "title": "Abstract",      "text": ABSTRACT},
    {"key": "introduction",  "title": "Introduction",  "text": INTRODUCTION},
    {"key": "methods",       "title": "Methods",       "text": METHODS},
    {"key": "results",       "title": "Results",       "text": RESULTS},
    {"key": "discussion",    "title": "Discussion",    "text": DISCUSSION},
]

out_json = dict(d)
out_json["sections"] = revised_sections
out_json["revision_note"] = (
    "Structural revision v1 (frontiers): 5-para introduction funnel, "
    "discussion strong opener, boilerplate purge across all sections. "
    "All sentences original; no content copied from reference article."
)
JOUT.write_text(json.dumps(out_json, indent=2, ensure_ascii=False), encoding="utf-8")

# ── Plain-text manuscript ─────────────────────────────────────────────────────
def wc(t: str) -> int:
    return len(re.findall(r"[A-Za-z0-9'-]+", t))

title = (
    plan.get("suggested_title") or
    "Development of human innate immune responses in a humanized NSG-QUAD mouse model"
)
lines: list[str] = [
    "=" * 80,
    title.upper(),
    "=" * 80, "",
    "Target journal: Frontiers in Immunology",
    f"Total body words: {sum(wc(s['text']) for s in revised_sections)}",
    f"References: {len(refs)}", "",
    "─" * 80,
]
for sec in revised_sections:
    w = wc(sec["text"])
    lines += ["", "─" * 80, f"{sec['key'].upper()}  [{w} words]", "─" * 80, ""]
    lines.append(sec["text"].strip())

lines += ["", "─" * 80, f"REFERENCES  [{len(refs)} entries]", "─" * 80, ""]
for i, ref in enumerate(refs, 1):
    lines.append(f"{i}. {ref}")

TOUT.write_text("\n".join(lines), encoding="utf-8")

# ── Word count report ─────────────────────────────────────────────────────────
expert = {
    "abstract": 251, "introduction": 565,
    "methods": 1375, "results": 3233, "discussion": 1927,
}
print("\nRevised word counts (frontiers draft):")
for sec in revised_sections:
    w  = wc(sec["text"])
    ex = expert.get(sec["key"], 0)
    pct = round(w / ex * 100) if ex else 0
    print(f"  {sec['key']:14s} {w:5d} words  (expert {ex}, {pct}%)")
total = sum(wc(s["text"]) for s in revised_sections)
print(f"  {'TOTAL':14s} {total:5d} words  (expert 7351, {round(total/7351*100)}%)")
print(f"\nSaved: {JOUT.name}")
print(f"Saved: {TOUT.name}")
