#!/usr/bin/env python3
"""
core/humanization/ctx_guard.py
=====================================================
Applies 9AA-CTX (Contextual Substitution Engine) veto/rollback logic
to sequences generated by DEEP-FR or other aggressive humanization methods.

This acts as a "guard", identifying positions where the aggressive method
changed a murine residue but 9AA-CTX would VETO or PROTECT it based on
clinical 9-mer context and structural rules.
"""
from __future__ import annotations

from typing import Dict, List, Tuple
from core.humanization.contextual_substitution_engine import (
    ContextualSubstitutionEngine,
    PositionDecision,
)


ALGORITHM_ID = "deepfr_ctx"
DISPLAY_NAME = "DeepFR-CTX"

SOFT_REASONS_RESCUABLE = {
    "lack_of_contextual_support",
    "no_layer2_evidence",
    "weak_clinical_signal",
}

HARD_REASONS_NEVER_RESCUE = {
    "pro_introduction_backbone_disrupt",
    "pro_removal_backbone_lock",
    "gly_removal_backbone_anchor",
    "introduces_free_cys",
    "creates_n_glyc_motif",
    "strong_charge_flip",
    "global_sanity",
}

def apply_ctx_guard(humanized_seq: str,
                    donor_seq: str,
                    chain: str,
                    germline: str = "") -> Tuple[str, List[Dict]]:
    """
    Applies 9AA-CTX rules to a humanized sequence (e.g., from DEEP-FR) to identify
    unsupported replacements and roll them back to the donor (murine) sequence.

    Args:
        humanized_seq: The full V-region sequence (e.g., DEEP-FR output)
        donor_seq: The original donor (e.g., murine) sequence
        chain: "VH" or "VK"
        germline: Optional germline ID for family-conditioned rules (e.g. "IGHV3-23")

    Returns:
        Tuple of (guarded_sequence, list_of_rollbacks)
    """
    if len(humanized_seq) != len(donor_seq):
        raise ValueError(f"Length mismatch: humanized ({len(humanized_seq)}) vs donor ({len(donor_seq)})")

    # Segment the donor sequence into FR/CDR regions.
    # Note: 9AA-CTX requires FR1, CDR1, FR2, CDR2, FR3.
    # We use Kabat numbering to segment the donor sequence.
    from core.humanization.kabat_utils import get_kabat_numbering, cdr_span, sorted_keys
    
    kd_donor = get_kabat_numbering(donor_seq)
    kd_hum = get_kabat_numbering(humanized_seq)
    
    if not kd_donor or not kd_hum:
         raise RuntimeError("Kabat numbering failed.")

    def fr4(kd: dict, c: str) -> str:
        if c == "VH":
            return "".join(kd[k] for k in sorted_keys(kd) if k[0] > 102)
        else:
            return "".join(kd[k] for k in sorted_keys(kd) if k[0] > 97)

    if chain == "VH":
        ranges = {
            "FR1": (1, 25), "CDR1": (26, 35), "FR2": (36, 49),
            "CDR2": (50, 65), "FR3": (66, 94), "CDR3": (95, 102)
        }
    else:
        ranges = {
            "FR1": (1, 23), "CDR1": (24, 34), "FR2": (35, 49),
            "CDR2": (50, 56), "FR3": (57, 88), "CDR3": (89, 97)
        }

    seg = {
        name: cdr_span(kd_donor, lo, hi)
        for name, (lo, hi) in ranges.items()
    }
    
    # We also need the humanized segments to compare
    seg_hum = {
        name: cdr_span(kd_hum, lo, hi)
        for name, (lo, hi) in ranges.items()
    }
    
    # 1. Run 9AA-CTX on the DONOR sequence
    engine = ContextualSubstitutionEngine()
    ctx_res = engine.humanize_fr(
        fr1=seg["FR1"], cdr1=seg["CDR1"],
        fr2=seg["FR2"], cdr2=seg["CDR2"],
        fr3=seg["FR3"],
        vh_germline=germline,
        chain=chain
    )
    
    # 2. Identify positions where DEEP-FR mutated, but 9AA-CTX would PROTECT or VETO.
    #    Since ContextualSubstitutionEngine operates on the concatenated FR1+CDR1+... sequence,
    #    we align the decisions to the full sequence.
    
    concat_donor = seg["FR1"] + seg["CDR1"] + seg["FR2"] + seg["CDR2"] + seg["FR3"]
    concat_hum   = seg_hum["FR1"] + seg_hum["CDR1"] + seg_hum["FR2"] + seg_hum["CDR2"] + seg_hum["FR3"]
    
    guarded_concat = list(concat_hum)
    rollbacks = []

    for decision in ctx_res.decisions:
        pos = decision.position
        donor_aa = concat_donor[pos]
        hum_aa = concat_hum[pos]
        
        # If DEEP-FR changed the residue
        if donor_aa != hum_aa:
            # If 9AA-CTX decided NOT to change it (either PROTECTED or VETOED, or no-data)
            # OR if 9AA-CTX decided to change it to something else (we might roll back or accept 9AA-CTX's choice)
            # For a pure "Guard", we roll back to donor if 9AA-CTX didn't explicitly endorse the humanized_aa.
            
            endorse = False
            if decision.decision == "REPLACED" and decision.proposed_aa == hum_aa:
                endorse = True
                
            if not endorse:
                guarded_concat[pos] = donor_aa
                rollbacks.append({
                    "segment": decision.fr_segment,
                    "pos": decision.fr_pos,
                    "donor_aa": donor_aa,
                    "humanized_aa": hum_aa,
                    "ctx_decision": decision.decision,
                    "ctx_proposed": decision.proposed_aa if decision.decision == "REPLACED" else None,
                    "reason": decision.evidence.get("reason") or decision.evidence.get("veto_reason") or "lack_of_contextual_support"
                })

    # 3. Apply global sanity check from 9AA-CTX on the new guarded sequence.
    # We construct pseudo-decisions for the remaining mutations to feed into the global check.
    pseudo_decisions = []
    for pos, (d_aa, g_aa) in enumerate(zip(concat_donor, guarded_concat)):
        if d_aa != g_aa:
             pseudo_decisions.append(PositionDecision(
                 position=pos, fr_segment="FR", fr_pos=0,
                 original_aa=d_aa, proposed_aa=g_aa,
                 decision="REPLACED", layer="deep-fr-kept",
                 evidence={"top_aa_votes": 1000} # Fake high votes so they are rolled back last if needed
             ))
             
    guarded_concat = engine._global_sanity_check(
        concat_donor, guarded_concat, pseudo_decisions
    )
    
    # Re-extract any new rollbacks from the global sanity check
    for p_dec in pseudo_decisions:
         if p_dec.decision == "VETOED":
             rollbacks.append({
                  "segment": p_dec.fr_segment,
                  "pos": p_dec.fr_pos,
                  "donor_aa": p_dec.original_aa,
                  "humanized_aa": p_dec.proposed_aa, # The aa that was rolled back
                  "ctx_decision": "VETOED_GLOBAL",
                  "ctx_proposed": p_dec.original_aa,
                  "reason": p_dec.evidence.get("veto_reason", "global_sanity")
             })
             
    # Reassemble with CDR3 and FR4 (using humanized versions of CDR3/FR4, though CDR3 should be identical)
    final_seq = "".join(guarded_concat) + seg_hum["CDR3"] + fr4(kd_hum, chain)
    
    return final_seq, rollbacks


def apply_ctx_guard_with_rescue(humanized_seq: str,
                                  donor_seq: str,
                                  chain: str,
                                  germline: str = "",
                                  rescue_min_oas_windows: int = 1) -> Tuple[str, List[Dict], List[Dict]]:
    """
    Upgraded Guard with Rescue logic.

    Pipeline:
        1. Run apply_ctx_guard to get baseline rollbacks.
        2. For each rollback marked as soft (lack_of_contextual_support),
           try to RESCUE by checking whether DEEP-FR's proposed human
           residue has any OAS-repertoire support at this 9-mer window.
           If yes AND not blocked by hard CMC veto -> keep DEEP-FR's residue.
        3. Hard structural/CMC vetoes (Pro/Gly/Cys/N-glyc/charge flip) are
           NEVER rescued - they always rollback to donor.

    Args:
        humanized_seq: DEEP-FR (or other aggressive) humanized full V-region.
        donor_seq:     Original donor (e.g. murine/rat) full V-region.
        chain:         "VH" or "VK"
        germline:      Optional germline ID (for family-conditioned voting)
        rescue_min_oas_windows: minimum # of OAS 9-mer windows endorsing the
            DEEP-FR residue for rescue to fire (default 1 = any OAS support).

    Returns:
        (rescued_sequence, final_rollback_list, rescue_log)
    """
    from core.humanization.kabat_utils import get_kabat_numbering, cdr_span, sorted_keys

    # Step 1: baseline guard rollbacks
    guarded_seq, rollbacks = apply_ctx_guard(humanized_seq, donor_seq, chain, germline)

    if not rollbacks:
        return guarded_seq, [], []

    # Step 2: re-segment guarded_seq to find positions for rescue
    kd_hum = get_kabat_numbering(humanized_seq)
    kd_donor = get_kabat_numbering(donor_seq)

    if chain == "VH":
        ranges = {
            "FR1": (1, 25), "CDR1": (26, 35), "FR2": (36, 49),
            "CDR2": (50, 65), "FR3": (66, 94)
        }
    else:
        ranges = {
            "FR1": (1, 23), "CDR1": (24, 34), "FR2": (35, 49),
            "CDR2": (50, 56), "FR3": (57, 88)
        }

    seg_hum = {name: cdr_span(kd_hum, lo, hi) for name, (lo, hi) in ranges.items()}
    seg_donor = {name: cdr_span(kd_donor, lo, hi) for name, (lo, hi) in ranges.items()}

    concat_donor = (seg_donor["FR1"] + seg_donor["CDR1"] + seg_donor["FR2"]
                    + seg_donor["CDR2"] + seg_donor["FR3"])
    concat_hum = (seg_hum["FR1"] + seg_hum["CDR1"] + seg_hum["FR2"]
                  + seg_hum["CDR2"] + seg_hum["FR3"])

    # Compute concatenated start positions for each segment for absolute mapping
    seg_offsets = {}
    cur = 0
    for name in ["FR1", "CDR1", "FR2", "CDR2", "FR3"]:
        seg_offsets[name] = cur
        cur += len(seg_donor[name])

    # Step 3: build rescued sequence starting from guarded
    rescued_concat = list(concat_donor)  # will fill in
    # Re-derive from guarded_seq
    guarded_concat_part = guarded_seq[:len(concat_donor)]
    for i, ch in enumerate(guarded_concat_part):
        rescued_concat[i] = ch

    engine = ContextualSubstitutionEngine()
    rescue_log: List[Dict] = []
    final_rollbacks: List[Dict] = []

    for rb in rollbacks:
        seg = rb["segment"]
        rel_pos = rb["pos"]
        donor_aa = rb["donor_aa"]
        deepfr_aa = rb["humanized_aa"]
        reason = rb.get("reason", "")

        # absolute position in concat
        if seg not in seg_offsets:
            final_rollbacks.append(rb)
            continue
        abs_pos = seg_offsets[seg] + rel_pos

        # Hard reasons: never rescue
        hard_block = any(hard_reason in reason for hard_reason in HARD_REASONS_NEVER_RESCUE)
        soft_eligible = (reason in SOFT_REASONS_RESCUABLE) or (
            reason and not hard_block
        )

        if hard_block or not soft_eligible:
            final_rollbacks.append(rb)
            continue

        # Try rescue: check if DEEP-FR residue has OAS support at this 9-mer window
        # We score against a sequence where DEEP-FR residue is in place.
        candidate_seq = list(concat_donor)
        candidate_seq[abs_pos] = deepfr_aa
        candidate_seq_str = "".join(candidate_seq)

        oas_scores = engine._score_with_oas(candidate_seq_str, abs_pos)
        oas_support = oas_scores.get(deepfr_aa, 0)

        # Re-check Layer-4 CMC veto for the DEEP-FR residue (as a safety net)
        vetoed, veto_reason = engine._layer4_cmc_veto(
            original_seq=concat_donor,
            mutated_seq=candidate_seq_str,
            pos=abs_pos,
            original_aa=donor_aa,
            proposed_aa=deepfr_aa,
        )

        if vetoed:
            final_rollbacks.append({**rb, "rescue_attempt": "vetoed_by_cmc",
                                    "rescue_oas_support": oas_support,
                                    "rescue_veto_reason": veto_reason})
            continue

        if oas_support >= rescue_min_oas_windows:
            # RESCUE: restore DEEP-FR's residue
            rescued_concat[abs_pos] = deepfr_aa
            rescue_log.append({
                "segment": seg,
                "pos": rel_pos,
                "donor_aa": donor_aa,
                "deepfr_aa": deepfr_aa,
                "oas_support_windows": oas_support,
                "decision": "RESCUED_KEEP_DEEPFR",
                "reason": "oas_repertoire_supports_deepfr_choice"
            })
        else:
            final_rollbacks.append({**rb, "rescue_attempt": "no_oas_support",
                                    "rescue_oas_support": oas_support})

    # Reassemble final sequence (CDR3 + FR4 from humanized seq)
    def fr4(kd: dict, c: str) -> str:
        if c == "VH":
            return "".join(kd[k] for k in sorted_keys(kd) if k[0] > 102)
        else:
            return "".join(kd[k] for k in sorted_keys(kd) if k[0] > 97)

    cdr3_seg = (cdr_span(kd_hum, 95, 102) if chain == "VH"
                else cdr_span(kd_hum, 89, 97))
    final_seq = "".join(rescued_concat) + cdr3_seg + fr4(kd_hum, chain)
    return final_seq, final_rollbacks, rescue_log


def apply_deepfr_ctx(deepfr_seq: str,
                     donor_seq: str,
                     chain: str,
                     germline: str = "") -> Tuple[str, List[Dict], List[Dict]]:
    """
    Formal DeepFR-CTX entry point.

    DeepFR-CTX = DeepFR framework-humanization proposal followed by
    9AA contextual clinical/OAS guard-and-rescue filtering. Soft contextual
    rollbacks may be rescued when OAS supports the DeepFR residue; hard
    CMC/structure vetoes always roll back to the donor residue.
    """
    return apply_ctx_guard_with_rescue(
        humanized_seq=deepfr_seq,
        donor_seq=donor_seq,
        chain=chain,
        germline=germline,
    )
