"""
kabat_utils.py — InSynBio AbEngineCore
=======================================
Canonical Kabat numbering utilities with CORRECT insertion-code handling.

BUG HISTORY (never repeat):
    Previous code stored Kabat positions as plain integers:
        d[pos] = aa          # WRONG — (52,"A") overwrites (52,"")→Y is lost

    This silently drops all insertion-code residues:
        Kabat 52A (CDR-H2)  → lost → CDR-H2 one residue shorter
        Kabat 82A/82B/82C (FR3) → lost → FR3 loop truncated
        Kabat 30A-F (CDR-L1)    → lost → long L1 loops truncated

Correct approach (this module):
    Keys are (int_pos, ins_code) tuples: (52,""), (52,"A"), (82,"A") …
    Sort order preserves Kabat canonical order: integer first, then "" < "A" < "B" …
    CDR range check uses integer part only (as per Kabat convention).
"""

from __future__ import annotations
from typing import Dict, List, Optional, Tuple

# --------------------------------------------------------------------------- #
# Type alias
# --------------------------------------------------------------------------- #
# KabatKey = (integer_position, insertion_code_string)
# insertion_code_string is "" for non-insertion residues, "A"/"B"/… for insertions
KabatKey  = Tuple[int, str]
KabatDict = Dict[KabatKey, str]      # {(52,"A"): "P", (52,""): "Y", …}

# --------------------------------------------------------------------------- #
# Kabat ↔ IMGT position correspondence for Vernier zone residues
# --------------------------------------------------------------------------- #
# Generated by ANARCII dual-scheme run on:
#   VH: IGHV1-69*01 (most common therapeutic VH, 72% clinical frequency Tier-1)
#   VL: IGKV1-39*01 (most common therapeutic VK, 74% clinical frequency Tier-1)
# Method: number same sequence in Kabat + IMGT → align by sequence index.
#
# IMPORTANT SCHEME DIFFERENCES:
#   Kabat VH 27-30 → IMGT 28-35  : Kabat calls these FR1; IMGT calls them CDR-H1
#   Kabat VH 93-94 → IMGT 105/117: Kabat calls these FR3; IMGT calls them CDR-H3
#   All other VH Vernier positions: IMGT number is higher due to IMGT's wider CDRs
#
# The offset is NOT uniform — exact mapping depends on V-gene family and CDR lengths.
# Use kabat_to_imgt_vernier() for programmatic lookup; for other genes use
# get_dual_numbering() which re-runs ANARCII in both schemes.

VERNIER_KABAT_TO_IMGT_VH: dict[int, int] = {
    # Kabat → IMGT  | Kabat region | IMGT region
    2:   2,          # FR1         | FR1
    27:  28,         # FR1         | CDR-H1 (IMGT definition)
    28:  29,         # FR1         | CDR-H1
    29:  30,         # FR1         | CDR-H1
    30:  35,         # FR1         | CDR-H1
    47:  55,         # FR2         | FR2 (VH/VL interface anchor)
    48:  53,         # FR2         | FR2
    49:  54,         # FR2         | FR2
    67:  76,         # FR3         | FR3
    69:  78,         # FR3         | FR3
    71:  80,         # FR3         | FR3
    73:  82,         # FR3         | FR3
    78:  87,         # FR3         | FR3
    93:  105,        # FR3         | CDR-H3 (IMGT definition)
    94:  117,        # FR3         | CDR-H3
}

VERNIER_KABAT_TO_IMGT_VL: dict[int, int] = {
    # Kabat → IMGT  | Kabat region | IMGT region
    2:   2,          # FR1         | FR1
    4:   4,          # FR1         | FR1
    36:  42,         # FR2         | FR2
    46:  52,         # FR2         | FR2
    49:  55,         # FR2         | FR2
    69:  85,         # FR3         | FR3
    71:  87,         # FR3         | FR3
    98:  118,        # FR4         | FR4
}

# Reverse maps (IMGT → Kabat)
VERNIER_IMGT_TO_KABAT_VH: dict[int, int] = {
    v: k for k, v in VERNIER_KABAT_TO_IMGT_VH.items()
}
VERNIER_IMGT_TO_KABAT_VL: dict[int, int] = {
    v: k for k, v in VERNIER_KABAT_TO_IMGT_VL.items()
}

# Human-readable region labels for reporting
_VH_KABAT_REGION = {
    2: "FR1", 27: "FR1*", 28: "FR1*", 29: "FR1*", 30: "FR1*",
    47: "FR2", 48: "FR2", 49: "FR2",
    67: "FR3", 69: "FR3", 71: "FR3", 73: "FR3", 78: "FR3",
    93: "FR3†", 94: "FR3†",
}
_VH_IMGT_REGION = {
    2: "FR1", 28: "CDR-H1", 29: "CDR-H1", 30: "CDR-H1", 35: "CDR-H1",
    53: "FR2", 54: "FR2", 55: "FR2",
    76: "FR3", 78: "FR3", 80: "FR3", 82: "FR3", 87: "FR3",
    105: "CDR-H3", 117: "CDR-H3",
}
_VL_KABAT_REGION = {
    2: "FR1", 4: "FR1",
    36: "FR2", 46: "FR2", 49: "FR2",
    69: "FR3", 71: "FR3",
    98: "FR4",
}
_VL_IMGT_REGION = {
    2: "FR1", 4: "FR1",
    42: "FR2", 52: "FR2", 55: "FR2",
    85: "FR3", 87: "FR3",
    118: "FR4",
}
# * Kabat FR1 positions 27-30 are labeled CDR-H1 in IMGT
# † Kabat FR3 positions 93-94 are labeled CDR-H3 in IMGT


def kabat_to_imgt(kabat_pos: int, chain: str) -> Optional[int]:
    """Return IMGT position for a Kabat Vernier zone position, or None if not in table."""
    if chain == "VH":
        return VERNIER_KABAT_TO_IMGT_VH.get(kabat_pos)
    return VERNIER_KABAT_TO_IMGT_VL.get(kabat_pos)


def imgt_to_kabat(imgt_pos: int, chain: str) -> Optional[int]:
    """Return Kabat position for an IMGT Vernier zone position, or None if not in table."""
    if chain == "VH":
        return VERNIER_IMGT_TO_KABAT_VH.get(imgt_pos)
    return VERNIER_IMGT_TO_KABAT_VL.get(imgt_pos)


def vernier_dual_numbering_table(chain: str) -> list[dict]:
    """
    Return the full Vernier zone dual-numbering table as a list of dicts for reporting.

    Each dict has keys: kabat, imgt, aa_ref, kabat_region, imgt_region.
    aa_ref is from the reference germline (IGHV1-69 / IGKV1-39).
    """
    k2i = VERNIER_KABAT_TO_IMGT_VH if chain == "VH" else VERNIER_KABAT_TO_IMGT_VL
    kr  = _VH_KABAT_REGION         if chain == "VH" else _VL_KABAT_REGION
    ir  = _VH_IMGT_REGION          if chain == "VH" else _VL_IMGT_REGION
    rows = []
    for kpos, ipos in sorted(k2i.items()):
        rows.append({
            "chain":        chain,
            "kabat":        kpos,
            "imgt":         ipos,
            "kabat_region": kr.get(kpos, "?"),
            "imgt_region":  ir.get(ipos, "?"),
            "note": (
                "Kabat=FR1, IMGT=CDR-H1 (scheme boundary differs)" if chain == "VH" and kpos in (27,28,29,30)
                else "Kabat=FR3, IMGT=CDR-H3 (scheme boundary differs)" if chain == "VH" and kpos in (93,94)
                else ""
            ),
        })
    return rows


# --------------------------------------------------------------------------- #
# Canonical CDR ranges — V5.1.0 Union (Kabat ∪ Chothia ∪ AbM)
# --------------------------------------------------------------------------- #
# SSOT: config/vh_vl_humanization_v490.json `_meta.version: 5.1.0`,
#       `cdr_definitions.regions` (VH H1=26-35, H2=50-65, H3=95-102;
#                                   VL L1=24-34, L2=50-56, L3=89-97).
# These three lists MUST match `_CDR_POS` in core/humanization/engine.py
# (`_phase4_real`) and `cdr_definitions.regions` in the SSOT JSON.
# Trigger for the V5.1.0 widening: R5-307 / Wemol H4-L4 cross-comparison
# (2026-05-01) — strict Chothia 26-32/52-56 silently humanized
# paratope-adjacent residues 33-35, 50-51, 57-65. See EVOLUTION_LOG 2026-05-01.
CDR_RANGES_VH: List[Tuple[int, int]] = [(26, 35), (50, 65), (95, 102)]
CDR_RANGES_VL: List[Tuple[int, int]] = [(24, 34), (50, 56), (89,  97)]

# FR4 is NOT part of the V-gene; assembly appends it separately.
MAX_V_POS_VH = 94   # last FR3 integer position before CDR-H3 (95+)
MAX_CDR3_VH  = 102  # Kabat CDR-H3 end
MAX_V_POS_VL = 88   # last FR3 integer position before CDR-L3 (89+)
MAX_CDR3_VL  = 97   # Kabat CDR-L3 end

# --------------------------------------------------------------------------- #
# Utilities
# --------------------------------------------------------------------------- #

def sort_key(k: KabatKey) -> Tuple[int, str]:
    """Kabat canonical sort: integer ascending, then insertion code "" < "A" < "B" …"""
    pos, ins = k
    # map "" → comes before "A" in ASCII, so plain string sort works
    return (pos, ins)


def is_in_cdr(pos: int, chain: str) -> bool:
    """Return True if integer Kabat position is within any CDR of the given chain."""
    ranges = CDR_RANGES_VH if chain == "VH" else CDR_RANGES_VL
    return any(lo <= pos <= hi for lo, hi in ranges)


def kabat_from_anarcii(anarcii_numbering: List[Tuple[Tuple[int, str], str]]) -> KabatDict:
    """
    Convert Anarcii `.numbering` list to a KabatDict.

    CORRECT key format: (int_pos, ins_str)
    Drops only gap characters ("-") and None residues.

    NORMALIZATION RULE (must not change):
        ANARCII encodes non-insertion positions as (pos, ' ') — a space character,
        NOT (pos, '').  We normalize all whitespace-only insertion codes to ""
        so that callers can safely use (pos, "") as the key for base positions.

        Examples:
            (52, ' ')  → (52, '')   ← base position Y
            (52, 'A')  → (52, 'A')  ← insertion position P
            (82, 'B')  → (82, 'B')  ← insertion position

    Args:
        anarcii_numbering:  entry["numbering"] from Anarcii output after
                            `engine.to_scheme("kabat")`

    Returns:
        KabatDict — {(pos, ins_normalized): aa}
    """
    d: KabatDict = {}
    for (pos, ins), aa in anarcii_numbering:
        if aa and aa != "-":
            ins_str = ins.strip() if ins else ""   # ' ' → '', 'A' → 'A'
            d[(pos, ins_str)] = aa
    return d


def sorted_keys(kd: KabatDict) -> List[KabatKey]:
    """Return keys in canonical Kabat order."""
    return sorted(kd.keys(), key=sort_key)


def cdr_span(kd: KabatDict, lo: int, hi: int) -> str:
    """
    Extract CDR sequence from KabatDict for Kabat range [lo, hi].
    Includes insertion-code residues (e.g., 52A) within the integer range.
    """
    residues = [
        kd[k] for k in sorted_keys(kd)
        if lo <= k[0] <= hi
    ]
    return "".join(r for r in residues if r)


def assemble_humanized_v(
    chain: str,
    mouse_num:  KabatDict,
    germ_num:   KabatDict,
    bm_map:     Dict[int, str],   # {kabat_int_pos: mouse_aa}  ← back-mutations
    fr4:        str,
) -> str:
    """
    Assemble a humanized variable-domain sequence.

    Rules (per Kabat position):
      1. If position (integer part) is in a CDR range → use mouse residue
      2. If integer position is in bm_map             → use back-mutated (mouse) residue
      3. Otherwise                                     → use germline residue

    Insertion-code positions follow the same rules based on their integer part.

    The V-region ends at:
      VH: Kabat 102 (CDR-H3 end, before FR4 starts at ~103)
      VL: Kabat 97  (CDR-L3 end, before FR4 starts at ~98)

    FR4 is appended directly as a raw string (J-gene sequence).
    """
    cdr_ranges = CDR_RANGES_VH if chain == "VH" else CDR_RANGES_VL
    max_v_end  = MAX_CDR3_VH   if chain == "VH" else MAX_CDR3_VL

    def _src(pos: int, ins: str) -> Optional[str]:
        """Return amino acid for a given (pos, ins) according to assembly rules."""
        in_cdr = any(lo <= pos <= hi for lo, hi in cdr_ranges)
        if in_cdr:
            # STRICT CDR GRAFTING: Only use residues present in the donor (mouse/chim)
            # Do NOT fallback to base position if insertion code is missing in donor,
            # and do NOT use germline residues for CDR positions.
            return mouse_num.get((pos, ins))
        elif pos in bm_map:
            return bm_map[pos]
        else:
            # FRAMEWORK: Use germline residues
            return germ_num.get((pos, ins)) or germ_num.get((pos, ""))

    # Build the keys for the assembled sequence
    # 1. For CDRs: Use ONLY keys present in mouse_num within CDR ranges
    # 2. For FRs: Use keys from germ_num (and bm_map)
    all_keys: set[KabatKey] = set()
    
    # Add all germline keys (Framework)
    for k in germ_num:
        if k[0] <= max_v_end and not is_in_cdr(k[0], chain):
            all_keys.add(k)
            
    # Add all donor keys (CDRs)
    for k in mouse_num:
        if k[0] <= max_v_end and is_in_cdr(k[0], chain):
            all_keys.add(k)
            
    # Add back-mutation keys (might be in FR but not in germ_num if insertion)
    for pos in bm_map:
        if pos <= max_v_end:
            all_keys.add((pos, ""))

    seq_parts: List[str] = []
    for k in sorted(all_keys, key=sort_key):
        pos, ins = k
        aa = _src(pos, ins)
        if aa:
            seq_parts.append(aa)

    return "".join(seq_parts) + fr4


def verify_cdr_preservation(
    humanized_num: KabatDict,
    mouse_num:     KabatDict,
    chain:         str,
) -> List[str]:
    """
    Verify all CDR positions match between humanized and mouse sequences.
    Returns list of mismatch descriptions (empty = all good).
    """
    cdr_ranges = CDR_RANGES_VH if chain == "VH" else CDR_RANGES_VL
    cdr_names  = (["H1","H2","H3"] if chain == "VH" else ["L1","L2","L3"])

    errors: List[str] = []
    for name, (lo, hi) in zip(cdr_names, cdr_ranges):
        m_cdr = cdr_span(mouse_num, lo, hi)
        h_cdr = cdr_span(humanized_num, lo, hi)
        if m_cdr != h_cdr:
            errors.append(
                f"{chain} {name} (Kabat {lo}-{hi}): "
                f"Mouse={m_cdr!r} ≠ Humanized={h_cdr!r}"
            )
    return errors


def self_check_humanization(
    chain: str,
    donor_seq: str,
    humanized_seq: str,
    donor_num: KabatDict,
    humanized_num: KabatDict
) -> Dict[str, Any]:
    """
    Perform automatic self-check of humanization/caninization results.
    Checks: Total length, CDR lengths, FR lengths, and CDR sequence identity.
    """
    cdr_ranges = CDR_RANGES_VH if chain == "VH" else CDR_RANGES_VL
    cdr_names = ["CDR1", "CDR2", "CDR3"]
    
    results = {
        "pass": True,
        "errors": [],
        "metrics": {}
    }
    
    # 1. Total Length Check
    if len(donor_seq) != len(humanized_seq):
        results["pass"] = False
        results["errors"].append(f"Total length mismatch: Donor={len(donor_seq)}, Humanized={len(humanized_seq)}")
    
    # 2. CDR Checks (Length and Sequence)
    for name, (lo, hi) in zip(cdr_names, cdr_ranges):
        d_cdr = cdr_span(donor_num, lo, hi)
        h_cdr = cdr_span(humanized_num, lo, hi)
        
        if len(d_cdr) != len(h_cdr):
            results["pass"] = False
            results["errors"].append(f"{name} length mismatch: Donor={len(d_cdr)}, Humanized={len(h_cdr)}")
        
        if d_cdr != h_cdr:
            results["pass"] = False
            results["errors"].append(f"{name} sequence mismatch: Donor={d_cdr}, Humanized={h_cdr}")
            
        results["metrics"][f"{name}_len"] = len(h_cdr)

    # 3. FR Checks (Length)
    # FR1: start to CDR1_start
    # FR2: CDR1_end to CDR2_start
    # FR3: CDR2_end to CDR3_start
    # FR4: CDR3_end to end
    
    fr_ranges = []
    if chain == "VH":
        fr_ranges = [(1, 25), (36, 49), (66, 94), (103, 113)] # Approximate Kabat
    else:
        fr_ranges = [(1, 23), (35, 49), (57, 88), (98, 107)]
        
    for i, (lo, hi) in enumerate(fr_ranges):
        name = f"FR{i+1}"
        d_fr = cdr_span(donor_num, lo, hi)
        h_fr = cdr_span(humanized_num, lo, hi)
        
        if len(d_fr) != len(h_fr):
            # We record FR length changes but sometimes they are expected if scaffold differs
            # However, per user request "FR", we flag it.
            results["pass"] = False
            results["errors"].append(f"{name} length mismatch: Donor={len(d_fr)}, Humanized={len(h_fr)}")
        
        results["metrics"][f"{name}_len"] = len(h_fr)

    return results


def get_kabat_numbering(seq: str, anarcii_engine=None) -> KabatDict:
    """
    Convenience: run Anarcii on a sequence and return a KabatDict.
    If anarcii_engine is None, creates a new Anarcii instance.
    """
    if anarcii_engine is None:
        from anarcii import Anarcii
        anarcii_engine = Anarcii()

    result = anarcii_engine.number([("seq", seq)])
    try:
        result = anarcii_engine.to_scheme("kabat")
    except Exception:
        pass

    entry = result.get("seq", {})
    if not entry or not entry.get("numbering"):
        return {}

    return kabat_from_anarcii(entry["numbering"])
