"""Quick family hint detection for CD3 samples."""
seqs = {
  'OKT3':          'QVQLVQSGAEVKKPGASVKVSCKASGYTFTRYTMHWVRQAPGQGLEWIGYINPSRGYTNYNQKFKDRVTMTRDTSTSTVYMELSSLRSEDTAVYYCARYYDDHYCLDYWGQGTLVTVSS',
  'Teplizumab':    'QVQLVQSGGGVVQPGRSLRLSCKASGYTFTRYTMHWVRQAPGKGLEWIGYINPSRGYTNYNQKVKDRFTISRDNSKNTAFLQMDSLRPEDTGVYFCARYYDDHYCLDYWGQGTPVTVSS',
  'SP34':          'DIKLQSGAELARPGASVKMSCKTSGYTFTRYTMHWVKQRPGQGLEWIGYINPSRGYTNYNQKFKDKATLTTDKSSSTAYMQLSSLTSEDSAVYYCARYYDDHYCLDYWGQGTTLTVSS',
  'Visilizumab':   'QVQLVQSGAEVKKPGASVKVSCKASGYTFISYTMHWVRQAPGQGLEWMGYINPRSGYTHYNQKLKDKATLTADKSASTAYMELSSLRSEDTAVYYCARSAYYDYDGFAYWGQGTLVTVSS',
  'Otelixizumab':  'EVQLLESGGGLVQPGGSLRLSCAASGFTFSSFPMAWVRQAPGKGLEWVSTISTSGGRTYYRDSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAKFRQYSGGFDYWGQGTLVTVSS',
  'Foralumab':     'QVQLVESGGGVVQPGRSLRLSCAASGFKFSGYGMHWVRQAPGKGLEWVAVIWYDGSKKYYVDSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCARQMGYWHFDLWGRGTLVTVSS',
}
print(f'{"sample":<14} {"len":<4} {"N-term 14":<16} family hint')
for name, s in seqs.items():
    h = s[:14]
    if h.startswith('QVQLVQSGAEVK') or h.startswith('DIKLQSGAELA'):
        fam = 'IGHV1-like (KKPGAS/ARPGAS)'
    elif 'SGGGVVQ' in s[:25] or 'SGGGLVQ' in s[:25]:
        fam = 'IGHV3 (canonical)'
    else:
        fam = 'unknown'
    print(f'{name:<14} {len(s):<4} {h:<16} {fam}')
