#!/usr/bin/env python3
"""Build full-granularity InSynBio English whitepaper HTML from Therasik CN template."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "therasik-web-source" / "whitepaper_therasik_cn.html"
OUT = ROOT / "Web_Projects" / "insynbio_com" / "insynbio_product_whitepaper_en.html"
PRICING_S5 = ROOT / "Web_Projects" / "insynbio_com" / "snippets" / "pricing_s5_en.html"

# Order matters: longer / more specific strings first.
REPLACEMENTS: list[tuple[str, str]] = [
    ('<html lang="zh-CN">', '<html lang="en">'),
    (
        "<title>Therasik 药物 AI 设计平台 · 服务白皮书 2026</title>",
        "<title>InSynBio Clinical Drug AI Design Platform · Product Whitepaper 2026</title>",
    ),
    (
        "font-family:'PingFang SC','Hiragino Sans GB','Microsoft YaHei',\n        -apple-system,BlinkMacSystemFont,sans-serif;",
        "font-family:Inter,'Segoe UI',Arial,-apple-system,BlinkMacSystemFont,sans-serif;",
    ),
    # Brand & URLs
    ("Thera<b>sik</b>", "In<b>Syn</b>Bio"),
    ("Therasik", "InSynBio"),
    ("www.therasik.com", "www.insynbio.com"),
    ("https://www.therasik.com", "https://www.insynbio.com"),
    ("console.therasik.com", "console.insynbio.com"),
    ("https://console.therasik.com", "https://console.insynbio.com"),
    ("contact@therasik.com", "contact@insynbio.com"),
    (" · 客服微信 rockyhj", ""),
    # ── S0 Cover ──
    (
        "药物 AI 设计平台 · 服务白皮书 2026",
        "Clinical Drug AI Design Platform · Product Whitepaper 2026",
    ),
    (
        "<h1 style=\"font-size:28px;margin-bottom:8px;\">药物 AI 设计平台<br><em>基于临床抗体机器学习的 AI 设计</em></h1>",
        "<h1 style=\"font-size:28px;margin-bottom:8px;\">Clinical Drug AI Design Platform<br><em>Machine learning on clinical antibodies for AI-driven design</em></h1>",
    ),
    (
        "InSynBio 不替代湿实验，而是<strong style=\"color:var(--t7);\">让实验不再盲目</strong>——通过对临床上市抗体的系统性机器学习，把抗体工程、双特异、CAR-T、CMC 评估的设计与决策前置到分子合成之前，<strong style=\"color:var(--t7);\">显著降低试错规模、提高研发效率与临床前成功率</strong>。",
        "InSynBio does not replace wet-lab work. It <strong style=\"color:var(--t7);\">makes experiments purposeful</strong>—by learning systematically from clinically advanced antibodies, antibody engineering, bispecific assembly, CAR design, and CMC assessment are moved <strong style=\"color:var(--t7);\">before synthesis</strong>, reducing blind screening and improving preclinical readiness.",
    ),
    ("线上自助 · 分钟级", "Online self-service · minutes"),
    ("线下深度 · 专家驻场", "Offline depth · expert engagement"),
    ("AI 设计助手 · 全程伴随", "AI design assistant · always on"),
    ("减少实验盲目性", "Reduce blind screening"),
    (
        "在分子合成之前先在计算上完成方向筛选与风险定位，把湿实验预算花在已经过 AI 筛选的方案上，而不是大规模随机试错。",
        "Screen direction and risk in silico before synthesis; spend wet-lab budget on AI-prioritized designs, not random libraries.",
    ),
    ("先 AI 筛 · 再 CRO 验", "AI first · CRO validates"),
    ("提升研发效率", "Improve R&D efficiency"),
    (
        "从临床上市抗体中学规律，再迁移到新分子；人源化输出收敛到唯一候选，多特异稳定性提前预判，把抗体工程的\"猜与试\"变为\"知与选\"。",
        "Transfer patterns from clinical antibodies to new molecules; converge humanization to focused candidates; pre-judge multispecific stability—move from guess-and-test to know-and-select.",
    ),
    ("从经验试错 · 到知识驱动", "From trial-and-error · to knowledge-driven"),
    ("提高临床前成功率", "Strengthen preclinical readiness"),
    (
        "以近千级临床抗体的 30+ 可开发性指标作为标尺，提前评估人源化候选的 CMC、免疫原性与稳定性边界，并接入智能优化系统，降低后期推倒重来的概率。",
        "Benchmark humanized candidates against <strong>30+ developability indices</strong> from a near-thousand-scale clinical antibody collection; surface CMC, immunogenicity, and stability risks early via intelligent optimization.",
    ),
    ("早暴露 · 早修复 · 早收敛", "Expose early · fix early · converge"),
    (
        "<strong style=\"color:var(--t7);\">平台核心立场：</strong>AI 不替代实验，但能把\"必须做的实验\"和\"可以不做的实验\"分开。以临床抗体的机器学习为底座，输出结构化、可审计、可执行的设计方案——<strong style=\"color:var(--t7);\">让每一次湿实验，都是带着目的去做的。</strong>",
        "<strong style=\"color:var(--t7);\">Platform stance:</strong> AI does not replace experiments—it separates experiments you must run from those you can skip. Clinical antibody ML underpins structured, auditable, actionable design outputs—<strong style=\"color:var(--t7);\">so every wet-lab step has a rationale.</strong>",
    ),
    ("关于 Therasik 团队", "About InSynBio"),
    (
        "团队来自<strong style=\"color:var(--g9);\">中国科学院、哥伦比亚大学与洛克菲勒大学</strong>，免疫学专业背景，拥有逾十年免疫药物开发经验。平台设计原则：<strong style=\"color:var(--g9);\">不卖工具，卖结果；不替代实验，让实验有方向</strong>——把临床抗体的成药规律转化为可被工程师直接使用的 AI 设计能力。",
        "The team brings backgrounds from <strong style=\"color:var(--g9);\">Chinese Academy of Sciences, Columbia University, and Rockefeller University</strong>, with immunology training and a decade-plus in immunotherapeutic development. Design principle: <strong style=\"color:var(--g9);\">deliver outcomes, not tools; complement experiments with direction</strong>—turn clinical antibody learnings into engineer-ready AI design capability.",
    ),
    ("中国科学院", "CAS"),
    ("哥伦比亚大学", "Columbia University"),
    ("洛克菲勒大学", "Rockefeller University"),
    ("免疫学专业", "Immunology"),
    ("10+ 年免疫药物开发", "10+ years immunotherapy R&D"),
    ("AI 工程", "AI engineering"),
    ("结构相似度人源化", "Structure-similarity humanization"),
    ("结构相似度选源（非序列相似度）", "Structure-similarity donor selection (not sequence similarity)"),
    ("结构相似度人源化，链间夹角自然", "Structure-similarity humanization; natural pairing angles"),
    ("结构相似度选源", "Structure-similarity donor selection"),
    ("不是序列<br>相似的人源化", "humanization—not<br>sequence similarity"),
    ("一案一候选设计", "Focused-candidate design"),
    ("一案一候选，减少后续筛选规模", "Few focused candidates; less downstream screening"),
    ("<strong>一案一候选</strong>：输出少量高置信人源候选", "<strong>Few focused candidates</strong>: high-confidence humanized outputs"),
    ("减少筛选<br>节省实验规模", "few candidates<br>less screening"),
    ("临床标尺", "Clinical ruler"),
    ("30+ 指标<br>智能优化", "30+ indices<br>smart optimize"),
    ("专业知识<br>安全问答", "expert knowledge<br>safe Q&A"),
    ("VH/VL 人源化", "VH/VL humanization"),
    ("VHH 人源化", "VHH humanization"),
    ("三维结构预测", "3D structure prediction"),
    ("VH→VHH 小型化", "VH→VHH miniaturization"),
    ("双特异组装", "Bispecific assembly"),
    ("CMC 可开发性", "CMC developability"),
    ("结构预测", "Structure prediction"),
    ("cDNA 优化", "cDNA optimization"),
    ("亲和力成熟（线下）", "Affinity maturation (offline)"),
    ("CDR 从头设计（线下）", "De novo CDR (offline)"),
    ("湿实验对接（线下）", "Wet-lab bridge (offline)"),
    ("AI 设计助手", "AI design assistant"),
    # ── S1 Architecture ──
    ("01 · 平台架构", "01 · Platform architecture"),
    (
        "基于临床抗体机器学习的<em>AI 设计五层流水线</em>",
        "<em>Five-layer AI design workflow</em> grounded in clinical antibodies",
    ),
    (
        "InSynBio 不是单点 AI 工具，而是<strong>把临床上市抗体的成药规律学进去、把序列设计输出来</strong>的多层流水线：每层负责一种判断，结果上下游自动衔接，最终由免疫学专家审核交付。<strong>同一条流水线，既支撑线上自助快跑，也支撑线下专家深度精修。</strong>",
        "InSynBio is not a single-point AI tool. It is a <strong>multi-layer pipeline that learns from clinically advanced antibodies and outputs design-ready sequences</strong>—each layer makes one class of judgment, results chain automatically, and immunology experts review deliverables. <strong>The same pipeline powers fast online self-service and deep offline expert engagement.</strong>",
    ),
    ("临床抗体规律学习底座", "Clinical antibody pattern learning"),
    (
        "以已上市与临床在研抗体为学习样本，按格式（VH/VL · VHH · 双特异 · ADC · CAR）分群——把\"能进临床的抗体长什么样\"沉淀为可迁移到新分子上的设计经验。",
        "Approved and clinical-stage antibodies grouped by format (VH/VL · VHH · bispecific · ADC · CAR)—encoding what clinic-ready antibodies look like into transferable design knowledge.",
    ),
    ("临床冻结队列", "Clinical cohort"),
    ("格式分群", "Format clusters"),
    ("ADA 证据", "ADA evidence"),
    ("结构与构象判断层", "Structure & conformation judgement"),
    (
        "区域划分（FR / CDR / Hallmark）→ 三维结构预测 → 链间夹角、CDR 长度、疏水分布、自然配对度的结构指纹提取——这是\"结构相似度人源化\"取代\"序列相似度人源化\"的基础。",
        "Region mapping (FR / CDR / hallmark) → 3D structure → inter-chain angle, CDR length, hydrophobicity, natural pairing fingerprints—the basis for structure-similarity humanization over sequence similarity.",
    ),
    ("链间夹角", "Inter-chain angle"),
    ("自然配对", "Natural pairing"),
    ("CDR 构象", "CDR conformation"),
    ("设计与决策收敛层", "Design & convergence"),
    (
        "对鼠抗 / 兔抗 / VHH 等候选输入：人源化设计输出少量高置信候选，VH→VHH 小型化按结构兼容性生成方案，多特异 / Smart-CAR-T / CAR-M 按靶点和疾病场景进行构型建议——<strong>把\"筛大库\"变成\"先定方向\"</strong>。",
        "For murine, rabbit, or VHH inputs: humanization yields few high-confidence candidates; VH→VHH miniaturization follows structural compatibility; multispecific and Smart CAR designs are scenario-driven—<strong>replace library screening with direction first</strong>.",
    ),
    ("小型化", "Miniaturization"),
    ("构型建议", "Format guidance"),
    ("CMC 与免疫原性平衡诊断层", "CMC & immunogenicity balance"),
    (
        "以近千级临床抗体的 30+ 可开发性指标作为人源化候选标尺，综合诊断 pI、疏水、电荷、聚集、脱酰胺、异构化、糖基化、免疫原性热区等风险——指标之间存在冲突时给出<strong>权衡建议而非单一打分</strong>，并通过智能优化系统优先给出<strong>FR-only 优化</strong>方向，保留结合活性。",
        "Benchmark humanized candidates with <strong>30+ developability indices</strong> from a near-thousand-scale clinical collection—pI, hydrophobicity, charge, aggregation, deamidation, isomerization, glycosylation, immunogenic hotspots. Conflicting metrics receive <strong>trade-off guidance, not one score</strong>; intelligent optimization prioritizes <strong>framework-only (FR-only)</strong> fixes to preserve binding.",
    ),
    ("临床标尺", "Clinical ruler"),
    ("30+ 指标", "30+ indices"),
    ("免疫原性热区", "Immuno hotspots"),
    ("智能优化", "Smart optimization"),
    ("专家审核 · AI 助手 · 结构化输出", "Expert review · AI assistant · structured output"),
    (
        "免疫学专家审核计算结果 → 控制台 AI 助手实时解读与答疑 → 中英双语 · 可审计报告 → 可直接进入客户沟通、IND 前评估与 CRO 委托",
        "Immunology experts review outputs → console AI assistant interprets reports → bilingual auditable deliverables → ready for client review, IND prep, and CRO handoff",
    ),
    ("专家审核", "Expert review"),
    ("AI 助手伴随", "AI assistant"),
    ("中英双语", "Bilingual EN/CN"),
    ("▸ 与其他选项的本质区别", "▸ How we differ from alternatives"),
    ("公开 AI 平台", "Public AI platforms"),
    ("单点工具 · 静态评分", "Point tools · static scores"),
    ("基于临床抗体 ML 的 AI 设计平台", "Clinical-antibody ML design platform"),
    ("传统 CRO", "Traditional CRO"),
    ("湿实验外包", "Wet-lab outsourcing"),
    ("工具运行速度快", "Fast tool execution"),
    ("临床抗体机器学习底座", "Clinical antibody ML foundation"),
    ("湿实验直接验证", "Direct wet-lab validation"),
    ("序列相似度匹配，构象失真", "Sequence-similarity matching; distorted conformations"),
    ("结构相似度人源化，链间夹角自然", "Structure-similarity humanization; natural pairing angles"),
    ("GMP / 法规支持", "GMP / regulatory support"),
    ("输出大量候选需自行筛选", "Large candidate lists; client screens alone"),
    ("一案一候选，减少后续筛选规模", "Few focused candidates; less downstream screening"),
    ("无计算层预筛，试错成本高", "No in silico pre-screen; high trial cost"),
    ("无 VH→VHH 小型化路径", "No VH→VHH miniaturization path"),
    ("VH→VHH 独家技术，桥接多特异/CAR-T", "VH→VHH pathway bridging bispecific / CAR-T"),
    ("周期数周至数月", "Weeks to months lead time"),
    ("单点 CMC 打分", "Single-score CMC"),
    ("临床抗体可开发性标尺 + 智能优化", "Clinical developability ruler + smart optimization"),
    ("费用是计算分析的 10–100×", "10–100× cost vs. computation"),
    ("无 AI 对话助手 / IDE 工作台", "No AI assistant / IDE workspace"),
    ("AI 设计助手 + IDE 风格工作台", "AI assistant + IDE-style workspace"),
    ("无 IND 前 CMC 风险识别", "No pre-IND CMC risk surfacing"),
    ("只能线上，无线下精修", "Online only; no expert depth"),
    ("线上自助 + 线下专家驻场双轨", "Online self-service + offline expert dual track"),
    ("不提供计算层方向判断", "No computational direction layer"),
    (
        "<strong>核心立场</strong>：AI 设计不能替代实验，但能把\"必须做的实验\"和\"可以不做的实验\"分开——先在 AI 上把方向、风险、边界看清楚，再把湿实验预算精准花在已经过计算筛选的方案上。",
        "<strong>Core stance</strong>: AI design cannot replace experiments—it separates must-run from optional experiments. Clarify direction, risk, and boundaries in silico first; then spend wet-lab budget on computationally prioritized designs.",
    ),
    # ── S2 Services ──
    ("02 · 服务模块", "02 · Service modules"),
    ("线上自助 + 线下精修 — <em>覆盖抗体设计全周期</em>", "Online self-service + offline depth — <em>full antibody design lifecycle</em>"),
    (
        "线上模块通过 <strong>console.insynbio.com</strong> 自助调用，分钟到小时级返回报告；线下模块由免疫学专家驻场完成，包含湿实验对接与亲和力验证。两侧共享同一套设计标准与报告体系。",
        "Online modules run at <strong>console.insynbio.com</strong> with minute- to hour-scale reports; offline modules are led by immunology experts with wet-lab bridging and affinity validation. Both share the same design standards and reporting system.",
    ),
    ("▸ 线上模块 · 抗体工程（Online · Antibody Engineering）", "▸ Online · Antibody engineering"),
    ("结构相似度选源（非序列相似度）", "Structure-similarity donor selection (not sequence similarity)"),
    ("链间夹角 / 自然配对 / Vernier 校验", "Inter-chain angle / natural pairing / Vernier checks"),
    ("<strong>一案一候选</strong>：输出少量高置信人源候选", "<strong>Few focused candidates</strong>: high-confidence humanized outputs"),
    ("VHH 纳米抗体人源化", "VHH nanobody humanization"),
    ("从临床 VHH 中学规律", "Learn from clinical VHH patterns"),
    ("<strong>自动感知</strong>：疏水分布 · CDR 长度 · 人源化程度", "<strong>Structure-aware</strong>: hydrophobicity · CDR length · humanization depth"),
    ("保留结合活性同时提升成药性", "Preserve binding while improving developability"),
    ("多指标综合诊断（不是单一打分）", "Multi-metric diagnosis (not one score)"),
    ("格式专属对标：VH/VL · VHH · 双抗", "Format-specific benchmarks: VH/VL · VHH · bispecific"),
    ("<strong>FR-only 优化</strong>，平衡冲突指标", "<strong>FR-only optimization</strong> balancing conflicting metrics"),
    ("VH → VHH 小型化", "VH → VHH miniaturization"),
    ("VH-to-VHH Conversion · 独家", "VH-to-VHH · exclusive path"),
    ("<strong>抗体小型化的独家路径</strong>", "<strong>Exclusive antibody miniaturization path</strong>"),
    ("为多特异、CAR-T 提供更紧凑的结合域", "Compact binders for bispecific and CAR-T formats"),
    ("结构兼容性 + Hallmark 自动设计", "Structural compatibility + hallmark-aware design"),
    ("三维结构预测", "3D structure prediction"),
    ("VH+VL / VHH 三维构象", "VH+VL / VHH 3D conformations"),
    ("pLDDT 局部置信度 · CDR 柔性分析", "Local confidence · CDR flexibility analysis"),
    ("可下载 PDB · 接入下游 CMC / 对接", "Downloadable PDB · downstream CMC / docking"),
    ("cDNA 密码子优化", "cDNA codon optimization"),
    ("组装全长 IgG / VHH 链（含信号肽 / Fc）", "Full-length IgG / VHH assembly (signal peptide / Fc)"),
    ("表达系统偏好优化（HEK293 / CHO / E.coli）", "Expression-system optimization (HEK293 / CHO / E. coli)"),
    ("输出可直接交付的合成序列", "Synthesis-ready deliverable sequences"),
    ("▸ 线上模块 · 模态设计（Online · Modality Design）", "▸ Online · Modality design"),
    ("双特异抗体组装", "Bispecific antibody assembly"),
    ("IgG-like 与串联格式两类支持", "IgG-like and tandem formats"),
    ("<strong>基于结构</strong>分析配对稳定性", "<strong>Structure-based</strong> pairing stability"),
    ("Linker 智能选择 + 错配预警", "Linker selection + mispairing alerts"),
    ("Smart-CAR-T / CAR-M 构型设计", "Smart CAR-T / CAR-M design"),
    ("<strong>按靶点与疾病场景</strong>推荐构型方向", "<strong>Target- and scenario-driven</strong> CAR format guidance"),
    ("覆盖 CAR-T / CAR-M · 肿瘤 / 感染 / 自免", "CAR-T / CAR-M · oncology / infection / autoimmunity"),
    ("结合域 → 铰链 → TM → 共刺激域 → 安全控制", "Binder → hinge → TM → costim → safety controls"),
    ("控制台右侧常驻，上下文感知", "Console sidebar; context-aware"),
    ("简答（5 积分）· 详答（20 积分，深度推理）", "Quick answers · deep reasoning (credit-based)"),
    ("调用安全知识库，解读报告 · 答疑术语 · 草拟验证路线", "Safe knowledge base: report interpretation · terminology · validation outlines"),
    ("▸ 线下模块 · 专家驻场深度服务（Offline · Expert Engagement）", "▸ Offline · Expert engagement"),
    ("虚拟亲和力成熟", "Virtual affinity maturation"),
    ("多模型共识 ΔΔG 突变筛选", "Multi-model consensus ΔΔG mutation screening"),
    ("上位性双突变 · 协同位点发现", "Epistatic double mutants · synergistic sites"),
    ("专家解读 + 推荐变体清单", "Expert interpretation + recommended variant shortlist"),
    ("CDR 从头设计", "De novo CDR design"),
    ("规避专利空间（FTO 重设计）", "Patent-space redesign (FTO)"),
    ("CDR 多样性生成 + 多门控筛选", "CDR diversity + multi-gate filtering"),
    ("结构验证 + 亲和力再优化", "Structure validation + affinity refinement"),
    ("湿实验对接", "Wet-lab bridge"),
    ("对接合作 CRO 完成 DNA 合成 · 克隆 · 表达 · 纯化", "Partner CRO: DNA synthesis · cloning · expression · purification"),
    ("SPR / BLI / Octet 亲和力验证", "SPR / BLI / Octet affinity validation"),
    ("实验报价凭单可<strong>赠送 AI 设计积分</strong>", "CRO orders may <strong>earn AI design credits</strong>"),
    ("线下报价", "Offline quote"),
    ("线上自助", "Online self-service"),
    ("线下深度", "Offline depth"),
    ("线上模块", "Online modules"),
    ("线下模块", "Offline modules"),
    ("人源化", "humanization"),
    ("人源候选", "humanized candidates"),
    ("VH → VHH 小型化（独家）", "VH → VHH miniaturization (exclusive)"),
    ("<strong>抗体小型化的独家路径</strong>", "<strong>Exclusive antibody miniaturization path</strong>"),
    ("鼠 / 大鼠 / 兔", "mouse / rat / rabbit"),
    # ── S3 Differentiators ──
    ("03 · 独家能力", "03 · Differentiators"),
    ("与其他 AI 药物设计平台的 <em>8 大本质差异</em>", "<em>8 essential differences</em> vs. other AI drug-design platforms"),
    (
        "我们不与公开 AI 工具比\"工具数量\"，而是比\"对临床抗体规律的迁移能力\"。以下 8 项能力强调客户可见价值，平台后台细节与逐步判断过程不在白皮书中披露。",
        "We compete on transfer of clinical antibody learnings—not tool count. These eight capabilities emphasize customer-visible value; internal pipeline details are not disclosed in this whitepaper.",
    ),
    ("结构相似度人源化", "Structure-similarity humanization"),
    (
        "取代传统\"序列相似度\"人源化——以链间夹角、自然配对、CDR 构象为指标，结果更接近临床上市抗体的真实构型。",
        "Replaces sequence-similarity humanization—inter-chain angle, natural pairing, and CDR conformation align outputs with clinic-ready antibody geometry.",
    ),
    ("一案一候选设计", "Focused-candidate design"),
    (
        "面向具体项目输出少量高置信候选，不把大量低置信备选列表交给客户自行筛选——<strong>把筛选规模前置压缩</strong>。",
        "Few high-confidence candidates per project—not long low-confidence lists for clients to screen—<strong>compress screening upstream</strong>.",
    ),
    ("VHH 三维感知人源化", "Structure-aware VHH humanization"),
    (
        "基于临床 VHH 的机器学习，<strong>自动感知</strong>疏水分布、CDR 长度与人源化程度——不是套模板，是按结构特征做精修。",
        "Clinical VHH ML with <strong>automatic awareness</strong> of hydrophobicity, CDR length, and humanization depth—structure-driven refinement, not templates.",
    ),
    ("VH → VHH 小型化（独家）", "VH → VHH miniaturization (exclusive)"),
    (
        "把传统 VH/VL 抗体转换为纳米抗体格式，桥接多特异抗体与 CAR-T 设计场景——公开 AI 平台均不具备此能力。",
        "Convert conventional VH/VL antibodies to nanobody format—bridging bispecific and CAR-T design; uncommon on public AI platforms.",
    ),
    ("基于结构的多特异稳定性", "Structure-based multispecific stability"),
    (
        "双特异 / 多特异格式不靠经验拼装，而是基于三维结构预判配对稳定性、链错配风险、Linker 兼容性——把\"试制能否成\"前置到设计阶段。",
        "Bispecific formats judged by 3D structure—pairing stability, chain mispairing, linker fit—before build-test cycles.",
    ),
    ("临床抗体可开发性标尺", "Clinical developability ruler"),
    (
        "以近千级临床抗体的 30+ 可开发性指标作为人源化候选标尺，不打单一 CMC 总分，而是给出多维<strong>权衡报告</strong>，并由智能优化系统优先推荐 FR 区域优化方向，尽量保留结合活性。",
        "Near-thousand-scale clinical antibodies · <strong>30+ developability indices</strong> as the ruler—multi-dimensional <strong>trade-off reports</strong> and intelligent optimization favoring framework fixes to preserve binding.",
    ),
    (
        "根据靶点、疾病场景、效应细胞与安全边界推荐 CAR 构型方向——支持 CAR-T / CAR-M 在肿瘤、感染与免疫调节场景中的早期方案判断。",
        "CAR format guidance by target, disease, effector cell, and safety—early CAR-T / CAR-M decisions in oncology, infection, and immune modulation.",
    ),
    ("线上 + 线下双轨", "Online + offline dual track"),
    (
        "线上自助快跑（人源化 / CMC / 拼装），线下专家驻场精修（VAM / 从头设计 / 湿实验对接）——<strong>同一标准、同一报告体系</strong>。",
        "Fast online humanization / CMC / assembly; offline expert depth (VAM / de novo / wet-lab)—<strong>one standard, one reporting system</strong>.",
    ),
    ("▸ 平台体验：IDE 工作台 + AI 助手伴随 + 可审计输出", "▸ Platform UX: IDE workspace + AI assistant + auditable output"),
    ("IDE 风格工作台", "IDE-style workspace"),
    (
        "左侧模块导航 · 中部工作区 · 右侧 AI 助手 / 账户 · 底部状态栏——多模块串联，结果上下游自动衔接，像写代码一样切换服务。",
        "Module nav · workspace · AI assistant / account · status bar—chain services with IDE-like flow.",
    ),
    (
        "Agent 被赋予抗体结构生物学、CMC、多特异抗体与 Smart-CAR-T/CAR-M 的客户安全知识，可辅助解释风险、形成设计思路和实验验证路线。",
        "Agents carry customer-safe knowledge for antibody structural biology, CMC, bispecifics, and Smart CAR—risk explanation, design ideas, validation outlines.",
    ),
    ("中英双语 · 可审计报告", "Bilingual · auditable reports"),
    (
        "每份报告含版本水印与质控审计段；客户可见内容呈现工程结论、风险类别与推荐动作，不展示平台后台细节、数据来源细节或逐步判断过程。",
        "Versioned reports with QA audit blocks—engineering conclusions, risk classes, recommended actions; no internal pipeline or step-by-step logic in client views.",
    ),
    ("序列数据安全", "Sequence data security"),
    (
        "序列内存内处理，任务完成即清除，<strong>不入库、不参与模型训练、不向第三方披露</strong>。企业版支持私有节点部署。",
        "In-memory processing; cleared after tasks—<strong>not stored, not used for training, not disclosed to third parties</strong>. Enterprise private nodes available.",
    ),
    ("客户安全输出边界", "Customer-safe output boundary"),
    (
        "Agent 可调用平台安全知识库辅助问答与方案初筛，但只输出结论、风险解释、建议动作与实验验证路线；不复述后台工程规则、数据来源细节或逐步判断过程。",
        "Agents use a safe knowledge base for Q&A and screening—outputs are conclusions, risks, actions, validation routes only; no internal rules or step-by-step logic.",
    ),
    # ── S4 Cases ──
    ("04 · 平台案例", "04 · Platform cases"),
    ("9 个案例 — <em>跨模态 AI 设计实证</em>", "9 cases — <em>cross-modality AI design evidence</em>"),
    (
        "涵盖人源化、CMC 评估、VHH 转化、亲和力成熟、CDR 重设计、双特异、CAR-M 与半抗原应用——演示\"AI 设计 → 减少试错 → 精准实验\"的全链路价值（客户项目已脱敏，受 NDA 保护）。",
        "Humanization, CMC, VHH conversion, affinity maturation, CDR redesign, bispecific, CAR-M, hapten VAM—demonstrating AI design → less blind screening → focused experiments (client data anonymized under NDA).",
    ),
    ("人源化", "Humanization"),
    ("muMAb4D5 → 赫赛汀前体人源化", "muMAb4D5 → trastuzumab-precursor humanization"),
    ("结构保护 · CDR 100% 保留", "Structure protection · CDR 100% preserved"),
    (
        "对全球临床验证最充分的抗体进行重新人源化——以结构相似度选源，保留关键结合构象，CMC 全维度达标。",
        "Re-humanization of a globally validated antibody—structure-similarity donor, preserved binding geometry, full developability pass.",
    ),
    ("避免错误框架进入合成，节省 2–4 周返工与重新委托成本", "Avoid wrong frameworks in synthesis; save 2–4 weeks rework and re-ordering"),
    ("muMAb4D5 CMC 多指标平衡诊断", "muMAb4D5 CMC multi-metric balance"),
    ("全指标通过 · 优于参照", "All metrics pass · vs. reference"),
    (
        "基于近千级临床抗体可开发性标尺的 CMC 多指标平衡诊断——所有维度均通过，并由智能优化系统给出优先级明确的可开发性修正建议。",
        "CMC balance against near-thousand clinical ruler—all dimensions pass; intelligent optimization ranks framework fixes.",
    ),
    ("临床前确认候选分子可开发性，降低一期免疫原性风险", "Preclinical developability confirmed; lower Phase I immunogenicity risk"),
    ("muMAb4D5 VH → 人源化 HER2 VHH", "muMAb4D5 VH → humanized HER2 VHH"),
    ("CDR 全保留 · 表面重塑", "CDR preserved · surface remodeling"),
    (
        "将 IgG 格式 VH 小型化为 HER2 纳米抗体——CDR 全保留，结构感知的表面重塑，关键 CMC 指标超越临床参照分子。",
        "IgG VH miniaturized to HER2 VHH—CDRs preserved, structure-aware surface remodeling, key CMC metrics vs. clinical reference.",
    ),
    ("为多特异 / CAR-T 提供更紧凑结合域，亲和力与热稳定性兼顾", "Compact binder for bispecific / CAR-T; affinity and stability balanced"),
    ("亲和力成熟（线下）", "Affinity maturation (offline)"),
    ("HER2 VHH 亲和力成熟", "HER2 VHH affinity maturation"),
    ("发现上位性协同突变", "Epistatic synergistic mutations"),
    (
        "多维度筛选 + 共识模型，定位上位性双突变——结合能显著提升，界面接触面积增加，主链构象保持稳定。",
        "Multi-dimensional screening + consensus models locate epistatic pairs—binding energy up, interface contact up, backbone stable.",
    ),
    ("计算预筛替代随机突变库筛选，节省 60–80% 合成与表达成本", "In silico pre-screen vs. random libraries; 60–80% synthesis/expression savings"),
    ("CDR 从头设计（线下）", "De novo CDR (offline)"),
    ("CDR 重设计与专利规避", "CDR redesign & patent-space expansion"),
    ("拓展专利空间 · 亲和力恢复", "Expanded patent space · affinity restored"),
    (
        "以冠军候选为起点，结构指导生成式 AI 重构 CDR2/CDR3，再经极性定向再成熟将亲和力恢复至个位数 nM。",
        "Champion-led structural redesign of CDR2/CDR3; polarity-directed maturation restored single-digit nM affinity.",
    ),
    ("多样化候选序列，规避序列同质化与专利侵权风险", "Diverse sequences; reduced homology and FTO risk"),
    ("双特异性 VHH", "Bispecific VHH"),
    ("高表达双特异性抗冠状病毒纳米抗体工程", "High-expression bispecific anti-coronavirus VHH engineering"),
    ("等电点 (pI) 工程 · 臂交换", "pI engineering · arm exchange"),
    (
        "SmartLink™ + VirtualCMC 解决了双冠状病毒 VHH-GS-VHH 融合蛋白在酵母中分泌量低的问题。",
        "SmartLink™ + VirtualCMC improved low yeast secretion of dual-coronavirus VHH-GS-VHH fusions.",
    ),
    ("通过模块化纳米抗体组装和表达调优，快速响应病毒突变", "Modular VHH assembly and expression tuning for variant response"),
    ("Smart-CAR-M 设计", "Smart CAR-M design"),
    ("针对恶性疟原虫的抗 CIDRα1 CAR-巨噬细胞", "Anti-CIDRα1 CAR-macrophage for malaria"),
    ("感染场景迁移 · 双结合域构型", "Infection scenario · dual-binder CAR"),
    (
        "围绕恶性疟原虫感染场景，形成双结合域 CAR-M 构型方向，并给出递送方式、效应细胞与临床前验证路径建议。",
        "Dual-binder CAR-M concept for malaria with delivery, effector, and preclinical validation guidance.",
    ),
    ("展示 Smart-CAR-M 规律可迁移到传染病与免疫调节场景", "Smart CAR-M patterns transferable to infection and immune modulation"),
    ("半抗原亲和力成熟", "Hapten affinity maturation"),
    ("抗芬太尼抗体的半抗原 VAM", "Anti-fentanyl hapten VAM"),
    ("多阶段筛选 · 推荐少量变体", "Multi-stage screen · few recommended variants"),
    (
        "针对小分子半抗原结合口袋进行多阶段筛选，识别出少量兼顾亲和力与可开发性的推荐变体。",
        "Multi-stage screening of hapten pockets—few variants balancing affinity and developability.",
    ),
    ("协同突变对发现，节省 60–80% 湿实验合成与表达成本", "Synergistic pairs found; 60–80% wet-lab savings"),
    ("抗 PD-L1 双克隆的表位分层与机制定位", "Anti–PD-L1 dual-clone epitope stratification"),
    ("Side-binding vs. Top blocking", "Side-binding vs. top blocking"),
    (
        "结合结构建模、界面统计和热点映射，区分 side-binding / ADC 导向克隆与顶部 blocking clone，并形成 human / cyno PD-L1 的评估框架。",
        "Structure modeling and hotspot mapping separate side-binding / ADC-oriented clones from top-blocking clones; human / cyno PD-L1 evaluation framework.",
    ),
    ("提前 3–6 个月暴露短板，在 IND 前完成修复，避免被动临床前淘汰", "Surface weaknesses 3–6 months earlier; fix before IND; avoid late preclinical drop-out"),
    (
        "完整报告可在 NDA 保护下按需提供 · 客户项目数据已脱敏",
        "Full reports available under NDA · client project data anonymized",
    ),
    # ── S5 Pricing ──
    ("05 · 接入与定价", "05 · Access & pricing"),
    ("<em>注册即送积分</em>，先评估再付费", "<em>Free credits on signup</em> — evaluate before you pay"),
    (
        "线上服务通过 <strong style=\"color:var(--t7);\">console.insynbio.com</strong> 自助调用，<strong style=\"color:var(--t7);\">新用户注册即赠送积分</strong>，覆盖完整人源化试运行 — 无需先付款即可评估平台。线下深度服务由专家驻场对接，全程 NDA 保护。",
        "Online services at <strong style=\"color:var(--t7);\">console.insynbio.com</strong>. <strong style=\"color:var(--t7);\">New users receive starter credits</strong> covering a full humanization trial—evaluate before purchase. Offline depth is expert-led under NDA.",
    ),
    ("线上自助 · console.insynbio.com", "Online self-service · console.insynbio.com"),
    ("注册即送积分 + 优惠码额外赠送", "Signup credits + promo-code bonuses"),
    ("分钟级响应，自助调用全部线上模块", "Minute-scale turnaround; all online modules"),
    ("AI 助手 + Demo 数据前 10 次免费", "AI assistant + first 10 demo runs free"),
    ("序列内存内处理 · 不入库 · 不训练", "In-memory sequences · not stored · not trained"),
    ("线下深度 · 专家驻场", "Offline depth · expert engagement"),
    ("VAM / CDR 从头设计 / 湿实验对接", "VAM / de novo CDR / wet-lab bridge"),
    ("免疫学专家全程审核 + AI 助手协同", "Immunology expert review + AI assistant"),
    ("NDA 保护 · 里程碑计费", "NDA · milestone billing"),
    ("定制报价，按项目规模与复杂度", "Custom quotes by scope and complexity"),
    ("▸ 线上方案 · ¥1 = 50 积分基准（可累加套餐折扣）", "▸ Online plans · ¥1 = 50 credits baseline (bundle discounts)"),
    ("注册赠送", "Signup bonus"),
    ("免费", "Free"),
    (
        "注册即送积分；填优惠码可额外加赠。覆盖一次完整人源化试运行。",
        "Credits on registration; promo codes add more. Covers one full humanization trial.",
    ),
    ("按量付费 / PAYG", "Pay-as-you-go / PAYG"),
    ("永久不过期，单次任务最经济入口。", "Credits never expire; most economical per task."),
    ("科研月卡 / Starter", "Research monthly / Starter"),
    ("<strong>1元=70 积分（7折）</strong> · 约 3.5 次人源化 · 月末清零。", "<strong>¥1 = 70 credits (30% off)</strong> · ~3.5 humanizations · monthly reset."),
    ("科研年卡 / Standard", "Research annual / Standard"),
    ("<strong>1元=84 积分（6折）</strong> · 约 42 次人源化 · 12 个月有效。", "<strong>¥1 = 84 credits (40% off)</strong> · ~42 humanizations · 12-month validity."),
    ("推荐", "Recommended"),
    ("科研专业 / Pro", "Research Pro"),
    ("<strong>1元=100 积分（5折）</strong> · 约 300 次人源化 · 优先队列 · 专属支持。", "<strong>¥1 = 100 credits (50% off)</strong> · ~300 humanizations · priority queue · dedicated support."),
    ("实验室年包 / Lab", "Lab annual pack"),
    ("<strong>1元=120 积分（4折）</strong> · 5 账号共享 · 统一费用统计。", "<strong>¥1 = 120 credits (60% off)</strong> · 5 shared seats · unified billing."),
    ("企业版 / Enterprise", "Enterprise"),
    ("¥300,000 / 年 起 · 含线下湿实验对接", "From ¥300,000 / year · includes offline wet-lab bridge"),
    ("专属私有计算节点 · SLA 商业级保障 · API 接入 · 适合药企 / CRO", "Private compute · commercial SLA · API access · pharma / CRO"),
    ("联系开通", "Contact sales"),
    ("学术优惠", "Academic bonus"),
    (
        "使用高校 / 科研院所邮箱（.edu / .edu.cn）注册，月卡 / 年卡方案自动享受 <strong>额外 20% 积分赠送</strong>。",
        "Register with .edu / academic email for <strong>extra 20% credits</strong> on monthly/annual plans.",
    ),
    ("下游实验互通", "Downstream experiment bridge"),
    (
        "通过平台对接合作 CRO 完成 <strong>DNA 合成 / 抗体表达 / 纯化</strong>，凭订单可获赠 <strong>AI 设计积分</strong>，规模灵活。",
        "Partner CRO for <strong>DNA synthesis / expression / purification</strong>—orders may earn <strong>AI design credits</strong>.",
    ),
    ("▸ 付款与发票", "▸ Payment & invoicing"),
    ("扫码支付（小额）", "QR payment (small amounts)"),
    ("· 微信扫码支付，10 分钟内到账", "· WeChat QR; credits within ~10 minutes"),
    ("· 支付后将截图发送客服微信 <strong>rockyhj</strong>", "· Email payment confirmation to contact@insynbio.com"),
    ("· 超出套餐部分按 ¥1 = 50 积分续费", "· Overage at ¥1 = 50 credits"),
    ("对公转账（¥5,000+）", "Wire transfer (¥5,000+)"),
    ("· 大额转账请联系客服获取对公账户", "· Contact sales for corporate account details"),
    ("· 支持 <strong>6% 增值税专用发票</strong>", "· <strong>6% VAT special invoice</strong> available (China)"),
    ("· 普票 1% · 电子发票 3–5 工作日", "· Standard invoice · e-invoice 3–5 business days"),
    ("客服微信 · 快速响应", "Email · fast response"),
    ("rockyhj", "contact@insynbio.com"),
    ("搜索添加，注明项目背景", "Include project context in subject line"),
    ("邮箱 · NDA / 正式合作", "Email · NDA / formal engagement"),
    ("委托 / 询价 / NDA 签署", "Engagement / quote / NDA"),
    ("官方网站 · 服务与案例", "Website · services & cases"),
    ("服务详情 · 团队 · 案例展示", "Services · team · case studies"),
    ("在线控制台 · 即刻体验", "Console · start now"),
    ("注册即送积分 · 立即评估", "Signup credits · evaluate today"),
    (
        "本文件介绍 Therasik 药物 AI 设计平台的服务范围与定价方案。AI 设计输出仅用于研发规划与方向筛选，<strong>不替代湿实验、临床试验或注册评估</strong>。© 2026 Therasik / InSynBio",
        "This document describes InSynBio clinical drug AI design services and pricing. AI outputs support R&D planning and directional screening—<strong>they do not replace wet-lab work, clinical trials, or regulatory assessment</strong>. © 2026 InSynBio",
    ),
]

FIXUPS: list[tuple[str, str]] = [
    ("关于 InSynBio 团队", "About InSynBio"),
    ("     S1 · 平台 AI 设计架构", "     S1 · Platform AI design architecture"),
    ("     S2 · 服务模块 (Online + Offline)", "     S2 · Service modules (online + offline)"),
    ("     S3 · Exclusive能力（8 大差异化）", "     S3 · Differentiators (8 essentials)"),
    ("03 · Exclusive能力", "03 · Differentiators"),
    ("     S4 · 平台案例", "     S4 · Platform cases"),
    ("     S5 · 接入与定价", "     S5 · Access & pricing"),
    ("     COVER — 深青花纹底，信息丰富", "     COVER"),
    (
        "区域划分（FR / CDR / Hallmark）→ 三维Structure prediction → Inter-chain angle、CDR 长度、疏水分布、Natural pairing度的结构指纹提取——这是\"Structure-first度Humanization\"取代\"序列相似度Humanization\"的基础。",
        "Region mapping (FR / CDR / hallmark) → 3D structure → inter-chain angle, CDR length, hydrophobicity, natural-pairing fingerprints—the basis for structure-similarity humanization over sequence similarity.",
    ),
    (
        "对鼠抗 / 兔抗 / VHH 等候选输入：Humanization设计输出少量高置信候选，VH→VHH miniaturization按结构兼容性生成方案，多特异 / Smart-CAR-T / CAR-M 按靶点和疾病场景进行Format guidance——<strong>把\"筛大库\"变成\"先定方向\"</strong>。",
        "For murine, rabbit, or VHH inputs: humanization yields few high-confidence candidates; VH→VHH miniaturization follows structural compatibility; multispecific and Smart CAR designs are scenario-driven—<strong>replace library screening with direction first</strong>.",
    ),
    ("Structure-first度Humanization，Inter-chain angle自然", "Structure-similarity humanization; natural pairing angles"),
    ("Structure-first度Humanization", "Structure-similarity humanization"),
    ("Structure-first度选源（非序列相似度）", "Structure-similarity donor selection (not sequence similarity)"),
    ("Structure-first度选源", "Structure-similarity donor selection"),
    ("无 VH→VHH miniaturization路径", "No VH→VHH miniaturization path"),
    ("One case，减少后续筛选规模", "Few focused candidates; less downstream screening"),
    ("<strong>One case</strong>：输出少量高置信humanized candidates", "<strong>Few focused candidates</strong>: high-confidence humanized outputs"),
    ("Inter-chain angle / Natural pairing / Vernier 校验", "Inter-chain angle / natural pairing / Vernier checks"),
    ("<strong>抗体Miniaturization的Exclusive路径</strong>", "<strong>Exclusive antibody miniaturization path</strong>"),
    ("三维Structure prediction", "3D structure prediction"),
    ("Smart CAR Design · 靶点 / 场景驱动", "Smart CAR · scenario-led design"),
    ("克隆表达", "Cloning & expression"),
    ("亲和力验证", "Affinity validation"),
    (
        "取代传统\"序列相似度\"Humanization——以Inter-chain angle、Natural pairing、CDR conformation为指标，结果更接近临床上市抗体的真实构型。",
        "Replaces sequence-similarity humanization—inter-chain angle, natural pairing, and CDR conformation align outputs with clinic-ready antibody geometry.",
    ),
    ("One case设计", "Focused-candidate design"),
    (
        "把传统 VH/VL 抗体转换为纳米抗体格式，桥接多特异抗体与 CAR-T 设计场景——Public AI platforms均不具备此能力。",
        "Convert conventional VH/VL antibodies to nanobody format—bridging bispecific and CAR-T design; uncommon on public AI platforms.",
    ),
    (
        "以近千级临床抗体的 30+ 可开发性指标作为Humanization候选标尺，不打单一 CMC 总分，而是给出多维<strong>权衡报告</strong>，并由Smart optimization系统优先Recommended FR 区域优化方向，尽量保留结合活性。",
        "Near-thousand-scale clinical antibodies · <strong>30+ developability indices</strong> as the ruler—multi-dimensional <strong>trade-off reports</strong> and intelligent optimization favoring framework fixes to preserve binding.",
    ),
    ("Online + Offline双轨", "Online + offline dual track"),
    (
        "Online自助快跑（Humanization / CMC / 拼装），Offline专家驻场精修（VAM / 从头设计 / Wet-lab bridge）——<strong>同一标准、同一报告体系</strong>。",
        "Fast online humanization / CMC / assembly; offline expert depth (VAM / de novo / wet-lab)—<strong>one standard, one reporting system</strong>.",
    ),
    ("▸ 平台体验：IDE 工作台 + AI assistant + 可审计输出", "▸ Platform UX: IDE workspace + AI assistant + auditable output"),
    ("AI Agent Skills · 专业知识注入", "AI Agent Skills · expert knowledge injection"),
    ("Bilingual EN/CN · 可审计报告", "Bilingual EN/CN · auditable reports"),
    ("muMAb4D5 → 赫赛汀前体Humanization", "muMAb4D5 → trastuzumab-precursor humanization"),
    (
        "对全球临床验证最充分的抗体进行重新Humanization——以Structure-first度选源，保留关键结合构象，CMC 全维度达标。",
        "Re-humanization of a globally validated antibody—structure-similarity donor, preserved binding geometry, full developability pass.",
    ),
    (
        "基于近千级Clinical developability ruler的 CMC 多指标平衡诊断——所有维度均通过，并由Smart optimization系统给出优先级明确的可开发性修正建议。",
        "CMC balance against near-thousand clinical ruler—all dimensions pass; intelligent optimization ranks framework fixes.",
    ),
    (
        "将 IgG 格式 VH Miniaturization为 HER2 纳米抗体——CDR 全保留，结构感知的表面重塑，关键 CMC 指标超越临床参照分子。",
        "IgG VH miniaturized to HER2 VHH—CDRs preserved, structure-aware surface remodeling, key CMC metrics vs. clinical reference.",
    ),
    (
        "Online服务通过 <strong style=\"color:var(--t7);\">console.insynbio.com</strong> 自助调用，<strong style=\"color:var(--t7);\">新用户注册即赠送积分</strong>，覆盖完整Humanization试运行 — 无需先付款即可评估平台。Offline深度服务由专家驻场对接，全程 NDA 保护。",
        "Online services at <strong style=\"color:var(--t7);\">console.insynbio.com</strong>. <strong style=\"color:var(--t7);\">New users receive starter credits</strong> covering a full humanization trial—evaluate before purchase. Offline depth is expert-led under NDA.",
    ),
    ("Online自助 · console.insynbio.com", "Online self-service · console.insynbio.com"),
    ("分钟级响应，自助调用全部Online模块", "Minute-scale turnaround; all online modules"),
    ("▸ Online方案 · ¥1 = 50 积分基准（可累加套餐折扣）", "▸ Online plans · ¥1 = 50 credits baseline (bundle discounts)"),
    ("注册即送积分；填优惠码可额外加赠。覆盖一次完整Humanization试运行。", "Credits on registration; promo codes add more. Covers one full humanization trial."),
    ("/ 50 积分", "/ 50 credits"),
    ("<strong>1元=70 积分（7折）</strong> · 约 3.5 次Humanization · 月末清零。", "<strong>¥1 = 70 credits (30% off)</strong> · ~3.5 humanizations · monthly reset."),
    ("<strong>1元=84 积分（6折）</strong> · 约 42 次Humanization · 12 个月有效。", "<strong>¥1 = 84 credits (40% off)</strong> · ~42 humanizations · 12-month validity."),
    ("<strong>1元=100 积分（5折）</strong> · 约 300 次Humanization · 优先队列 · 专属支持。", "<strong>¥1 = 100 credits (50% off)</strong> · ~300 humanizations · priority queue · dedicated support."),
    ("¥300,000 / 年 起 · 含OfflineWet-lab bridge", "From ¥300,000 / year · includes offline wet-lab bridge"),
    (
        "本文件介绍 InSynBio 药物 AI 设计平台的服务范围与定价方案。AI 设计输出仅用于研发规划与方向筛选，<strong>不替代湿实验、临床试验或注册评估</strong>。© 2026 InSynBio / InSynBio",
        "This document describes InSynBio clinical drug AI design services and pricing. AI outputs support R&D planning and directional screening—<strong>they do not replace wet-lab work, clinical trials, or regulatory assessment</strong>. © 2026 InSynBio",
    ),
    ('<span class="cv-sn" style="font-size:14px;line-height:1.2;">结构相似</span>', '<span class="cv-sn" style="font-size:14px;line-height:1.2;">Structure-first</span>'),
    ('<span class="cv-sn" style="font-size:14px;line-height:1.2;">一案一候选</span>', '<span class="cv-sn" style="font-size:14px;line-height:1.2;">Focused candidates</span>'),
    ("线上 + 线下", "Online + offline"),
    ("线上</span>", "Online</span>"),
    ("线下</span>", "Offline</span>"),
    ("独家</div>", "Exclusive</div>"),
    ("（独家）", "(exclusive)"),
    ("     S2 · 服务模块 (线上 + 线下)", "     S2 · Service modules (online + offline)"),
    ("     S3 · 独家能力（8 大差异化）", "     S3 · Differentiators (8 essentials)"),
    (
        "区域划分（FR / CDR / Hallmark）→ 3D structure prediction → Inter-chain angle、CDR 长度、疏水分布、Natural pairing度的结构指纹提取——这是\"Structure-similarity humanization\"取代\"序列相似度humanization\"的基础。",
        "Region mapping (FR / CDR / hallmark) → 3D structure → inter-chain angle, CDR length, hydrophobicity, natural-pairing fingerprints—the basis for structure-similarity humanization over sequence similarity.",
    ),
    (
        "对鼠抗 / 兔抗 / VHH 等候选输入：humanization设计输出少量高置信候选，VH→VHH miniaturization按结构兼容性生成方案，多特异 / Smart-CAR-T / CAR-M 按靶点和疾病场景进行Format guidance——<strong>把\"筛大库\"变成\"先定方向\"</strong>。",
        "For murine, rabbit, or VHH inputs: humanization yields few high-confidence candidates; VH→VHH miniaturization follows structural compatibility; multispecific and Smart CAR designs are scenario-driven—<strong>replace library screening with direction first</strong>.",
    ),
    ('<span style="font-size:9px;background:#d97706;color:#fff;border-radius:5px;padding:1px 7px;font-weight:800;">一案一候选</span>', '<span style="font-size:9px;background:#d97706;color:#fff;border-radius:5px;padding:1px 7px;font-weight:800;">Focused candidates</span>'),
    ("Structure-similarity humanization，Inter-chain angle自然", "Structure-similarity humanization; natural pairing angles"),
    ("<strong>抗体Miniaturization的独家路径</strong>", "<strong>Exclusive antibody miniaturization path</strong>"),
    (
        "取代传统\"序列相似度\"humanization——以Inter-chain angle、Natural pairing、CDR conformation为指标，结果更接近临床上市抗体的真实构型。",
        "Replaces sequence-similarity humanization—inter-chain angle, natural pairing, and CDR conformation align outputs with clinic-ready antibody geometry.",
    ),
    ("VHH 三维感知humanization", "Structure-aware VHH humanization"),
    (
        "基于临床 VHH 的机器学习，<strong>自动感知</strong>疏水分布、CDR 长度与humanization程度——不是套模板，是按结构特征做精修。",
        "Clinical VHH ML with <strong>automatic awareness</strong> of hydrophobicity, CDR length, and humanization depth—structure-driven refinement, not templates.",
    ),
    (
        "以近千级临床抗体的 30+ 可开发性指标作为humanization候选标尺，不打单一 CMC 总分，而是给出多维<strong>权衡报告</strong>，并由Smart optimization系统优先Recommended FR 区域优化方向，尽量保留结合活性。",
        "Near-thousand-scale clinical antibodies · <strong>30+ developability indices</strong> as the ruler—multi-dimensional <strong>trade-off reports</strong> and intelligent optimization favoring framework fixes to preserve binding.",
    ),
    (
        "Online self-service快跑（humanization / CMC / 拼装），线下专家驻场精修（VAM / 从头设计 / Wet-lab bridge）——<strong>同一标准、同一报告体系</strong>。",
        "Fast online humanization / CMC / assembly; offline expert depth (VAM / de novo / wet-lab)—<strong>one standard, one reporting system</strong>.",
    ),
    (
        "涵盖humanization、CMC 评估、VHH 转化、亲和力成熟、CDR 重设计、双特异、CAR-M 与半抗原应用——演示\"AI 设计 → 减少试错 → 精准实验\"的全链路价值（客户项目已脱敏，受 NDA 保护）。",
        "Humanization, CMC, VHH conversion, affinity maturation, CDR redesign, bispecific, CAR-M, hapten VAM—demonstrating AI design → less blind screening → focused experiments (client data anonymized under NDA).",
    ),
    ("muMAb4D5 → 赫赛汀前体humanization", "muMAb4D5 → trastuzumab-precursor humanization"),
    (
        "对全球临床验证最充分的抗体进行重新humanization——以Structure-similarity donor selection，保留关键结合构象，CMC 全维度达标。",
        "Re-humanization of a globally validated antibody—structure-similarity donor, preserved binding geometry, full developability pass.",
    ),
    (
        "线上服务通过 <strong style=\"color:var(--t7);\">console.insynbio.com</strong> 自助调用，<strong style=\"color:var(--t7);\">新用户注册即赠送积分</strong>，覆盖完整humanization试运行 — 无需先付款即可评估平台。Offline depth服务由专家驻场对接，全程 NDA 保护。",
        "Online services at <strong style=\"color:var(--t7);\">console.insynbio.com</strong>. <strong style=\"color:var(--t7);\">New users receive starter credits</strong> covering a full humanization trial—evaluate before purchase. Offline depth is expert-led under NDA.",
    ),
    ("分钟级响应，自助调用全部Online modules", "Minute-scale turnaround; all online modules"),
    ("注册即送积分；填优惠码可额外加赠。覆盖一次完整humanization试运行。", "Credits on registration; promo codes add more. Covers one full humanization trial."),
    ("<strong>1元=70 积分（7折）</strong> · 约 3.5 次humanization · 月末清零。", "<strong>¥1 = 70 credits (30% off)</strong> · ~3.5 humanizations · monthly reset."),
    ("<strong>1元=84 积分（6折）</strong> · 约 42 次humanization · 12 个月有效。", "<strong>¥1 = 84 credits (40% off)</strong> · ~42 humanizations · 12-month validity."),
    ("<strong>1元=100 积分（5折）</strong> · 约 300 次humanization · 优先队列 · 专属支持。", "<strong>¥1 = 100 credits (50% off)</strong> · ~300 humanizations · priority queue · dedicated support."),
    ("¥300,000 / 年 起 · 含线下Wet-lab bridge", "From ¥300,000 / year · includes offline wet-lab bridge"),
    ("     S2 · 服务模块 (Online + offline)", "     S2 · Service modules (online + offline)"),
    (">/ 月</span>", ">/ mo</span>"),
    (">/ 年</span>", ">/ yr</span>"),
]


def patch_insynbio_pricing_s5(html: str) -> str:
    """Replace Therasik RMB §5 with console.insynbio.com USD pricing (api/static/pricing.html)."""
    snippet = PRICING_S5.read_text(encoding="utf-8").strip()
    start = html.find('<div id="s5" class="pg pg-cta">')
    end_marker = "\n</div><!-- /doc -->"
    end = html.find(end_marker)
    if start < 0 or end < 0:
        raise RuntimeError("Failed to inject InSynBio pricing §5 — s5 or doc footer not found.")
    last_close = html.rfind("</div>", start, end)
    if last_close < 0:
        raise RuntimeError("Failed to inject InSynBio pricing §5 — s5 closing tag not found.")
    inner_end = last_close + len("</div>")
    return html[:start] + snippet + "\n\n" + html[inner_end:]


def main() -> None:
    text = SRC.read_text(encoding="utf-8")
    for old, new in REPLACEMENTS:
        text = text.replace(old, new)
    for old, new in FIXUPS:
        text = text.replace(old, new)
    text = patch_insynbio_pricing_s5(text)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT} ({len(text):,} bytes)")


if __name__ == "__main__":
    main()
