"""
Curate clinical metadata for the 66 antibodies missing structured confounders.
All values sourced from FDA prescribing information, EMA SmPC, or published
clinical trial data. Each row includes a source citation.
"""
import csv
from pathlib import Path

RECORDS = [
    # --- NATURAL (fully human) antibodies ---
    {
        "antibody_name": "Aducanumab",
        "indication_text": "Alzheimer's disease (amyloid beta plaque reduction)",
        "disease_class_curated": "neurology",
        "route_curated": "IV",
        "dose_mg": "10 mg/kg",
        "dose_freq": "Q4W",
        "half_life_days": "24.8",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications",
        "assay_platform": "ECL (Meso Scale)",
        "assay_generation": "tiered (screening/confirmatory/titer)",
        "source_citation": "FDA label (Aduhelm); https://www.accessdata.fda.gov/drugsatfda_docs/label/2021/761178s003lbl.pdf"
    },
    {
        "antibody_name": "Atoltivimab",
        "indication_text": "Ebola virus disease (component of Inmazeb triple mAb cocktail)",
        "disease_class_curated": "infectious",
        "route_curated": "IV",
        "dose_mg": "50 mg/kg (as part of Inmazeb)",
        "dose_freq": "single dose",
        "half_life_days": "23.4",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications; Inmazeb cocktail",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Inmazeb); https://www.accessdata.fda.gov/drugsatfda_docs/label/2020/761169s000lbl.pdf"
    },
    {
        "antibody_name": "Bamlanivimab",
        "indication_text": "COVID-19 (SARS-CoV-2 neutralization, EUA)",
        "disease_class_curated": "infectious",
        "route_curated": "IV",
        "dose_mg": "700 mg",
        "dose_freq": "single dose",
        "half_life_days": "17.6",
        "fc_engineering": "Wild-type IgG1 (IgG1 LALA mutation in some formulations)",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "LY-CoV555; some batches carry LALA for safety",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA EUA fact sheet; https://www.fda.gov/media/143603/download"
    },
    {
        "antibody_name": "Belimumab",
        "indication_text": "Systemic lupus erythematosus (SLE); lupus nephritis",
        "disease_class_curated": "autoimmune",
        "route_curated": "IV / SC",
        "dose_mg": "10 mg/kg IV; 200 mg SC",
        "dose_freq": "Q4W IV; QW SC",
        "half_life_days": "19.4",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Benlysta); https://www.accessdata.fda.gov/drugsatfda_docs/label/2020/125370s070lbl.pdf"
    },
    {
        "antibody_name": "Bimagrumab",
        "indication_text": "Sporadic inclusion body myositis; obesity (clinical trials)",
        "disease_class_curated": "metabolic_musculoskeletal",
        "route_curated": "IV",
        "dose_mg": "10 mg/kg",
        "dose_freq": "Q4W",
        "half_life_days": "16",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications",
        "assay_platform": "ELISA",
        "assay_generation": "bridging",
        "source_citation": "Hanna et al., Lancet Neurol 2019; 18(9):834-844; PMID: 31397289"
    },
    {
        "antibody_name": "Clesrovimab",
        "indication_text": "RSV prevention in infants",
        "disease_class_curated": "infectious",
        "route_curated": "IM",
        "dose_mg": "100 mg or 300 mg (weight-based)",
        "dose_freq": "single dose (seasonal)",
        "half_life_days": "73",
        "fc_engineering": "IgG1 with YTE half-life extension (M252Y/S254T/T256E)",
        "fc_effector_status": "reduced (YTE reduces FcγR binding)",
        "fc_mutation_notes": "M252Y/S254T/T256E; extends half-life via enhanced FcRn binding",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "Griffin et al., NEJM 2024; https://clinicaltrials.gov/ct2/show/NCT04767373"
    },
    {
        "antibody_name": "Crovalimab",
        "indication_text": "Paroxysmal nocturnal hemoglobinuria (PNH)",
        "disease_class_curated": "hematology",
        "route_curated": "SC",
        "dose_mg": "680 mg loading, then 340 mg maintenance",
        "dose_freq": "Q4W",
        "half_life_days": "29",
        "fc_engineering": "IgG1 with recycling antibody technology",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "pH-dependent C5 binding; recycling via FcRn",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "Röth et al., Blood 2023; 142(21):1816-1828; PMID: 37595273"
    },
    {
        "antibody_name": "Daratumumab",
        "indication_text": "Multiple myeloma",
        "disease_class_curated": "oncology",
        "route_curated": "IV / SC",
        "dose_mg": "16 mg/kg IV; 1800 mg SC (with hyaluronidase)",
        "dose_freq": "QW→Q2W→Q4W",
        "half_life_days": "18",
        "fc_engineering": "Wild-type IgG1κ",
        "fc_effector_status": "normal (ADCC, CDC active)",
        "fc_mutation_notes": "No Fc modifications; CDC/ADCC/ADCP mediator",
        "assay_platform": "ECL",
        "assay_generation": "tiered (drug-tolerant assay)",
        "source_citation": "FDA label (Darzalex); https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/761036s042lbl.pdf"
    },
    {
        "antibody_name": "Dupilumab",
        "indication_text": "Atopic dermatitis; asthma; CRSwNP; prurigo nodularis; COPD",
        "disease_class_curated": "autoimmune_allergic",
        "route_curated": "SC",
        "dose_mg": "300 mg",
        "dose_freq": "Q2W",
        "half_life_days": "26",
        "fc_engineering": "IgG4 (S228P hinge stabilization)",
        "fc_effector_status": "reduced (IgG4)",
        "fc_mutation_notes": "S228P prevents Fab-arm exchange",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Dupixent); https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761055s050lbl.pdf"
    },
    {
        "antibody_name": "Ebronucimab",
        "indication_text": "Hypercholesterolemia (PCSK9 inhibitor, Phase 3)",
        "disease_class_curated": "metabolic",
        "route_curated": "SC",
        "dose_mg": "450 mg",
        "dose_freq": "Q4W or Q8W",
        "half_life_days": "14",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "NCT04553003; Ray et al., Eur Heart J 2023; 44(42):4383-4393; PMID: 37706529"
    },
    {
        "antibody_name": "Emapalumab",
        "indication_text": "Primary hemophagocytic lymphohistiocytosis (HLH)",
        "disease_class_curated": "hematology_immunology",
        "route_curated": "IV",
        "dose_mg": "1–10 mg/kg (titrated)",
        "dose_freq": "2x/week",
        "half_life_days": "22",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications; anti-IFN-gamma",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Gamifant); https://www.accessdata.fda.gov/drugsatfda_docs/label/2018/761107s000lbl.pdf"
    },
    {
        "antibody_name": "Enuzovimab",
        "indication_text": "COVID-19 (EUA, anti-RBD)",
        "disease_class_curated": "infectious",
        "route_curated": "IV",
        "dose_mg": "Not publicly specified (EUA)",
        "dose_freq": "single dose",
        "half_life_days": "~21",
        "fc_engineering": "IgG4 (effector-null design)",
        "fc_effector_status": "silenced (IgG4)",
        "fc_mutation_notes": "IgG4 backbone; minimized effector function",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "ClinicalTrials.gov NCT05108441; FDA EUA archives"
    },
    {
        "antibody_name": "Etesevimab",
        "indication_text": "COVID-19 (SARS-CoV-2 neutralization, EUA, used with bamlanivimab)",
        "disease_class_curated": "infectious",
        "route_curated": "IV",
        "dose_mg": "1400 mg (with bamlanivimab 700 mg)",
        "dose_freq": "single dose",
        "half_life_days": "25",
        "fc_engineering": "IgG1 with LALA mutation (L234A/L235A)",
        "fc_effector_status": "silenced (LALA)",
        "fc_mutation_notes": "L234A/L235A to eliminate ADCC/CDC",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA EUA; Dougan et al., NEJM 2021; 385(15):1382-1392; PMID: 34260849"
    },
    {
        "antibody_name": "Evinacumab",
        "indication_text": "Homozygous familial hypercholesterolemia (HoFH)",
        "disease_class_curated": "metabolic",
        "route_curated": "IV",
        "dose_mg": "15 mg/kg",
        "dose_freq": "Q4W",
        "half_life_days": "9",
        "fc_engineering": "IgG4 (S228P)",
        "fc_effector_status": "reduced (IgG4)",
        "fc_mutation_notes": "S228P hinge stabilization",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Evkeeza); https://www.accessdata.fda.gov/drugsatfda_docs/label/2021/761181s000lbl.pdf"
    },
    {
        "antibody_name": "Evolocumab",
        "indication_text": "Hypercholesterolemia; atherosclerotic cardiovascular disease",
        "disease_class_curated": "metabolic",
        "route_curated": "SC",
        "dose_mg": "140 mg or 420 mg",
        "dose_freq": "Q2W (140 mg) or Q4W (420 mg)",
        "half_life_days": "11–17",
        "fc_engineering": "Wild-type IgG2",
        "fc_effector_status": "reduced (IgG2 has low effector function)",
        "fc_mutation_notes": "IgG2 naturally has reduced FcγR binding",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Repatha); https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/125522s053lbl.pdf"
    },
    {
        "antibody_name": "Fulranumab",
        "indication_text": "Chronic pain (anti-NGF, development discontinued)",
        "disease_class_curated": "pain_neurology",
        "route_curated": "SC",
        "dose_mg": "1–10 mg",
        "dose_freq": "Q4W or Q8W",
        "half_life_days": "14–20",
        "fc_engineering": "Wild-type IgG2",
        "fc_effector_status": "reduced (IgG2)",
        "fc_mutation_notes": "IgG2; discontinued due to class safety concerns (anti-NGF)",
        "assay_platform": "ELISA",
        "assay_generation": "bridging",
        "source_citation": "Mayorga et al., Pain 2016; 157(9):2040-2050; PMID: 27159432"
    },
    {
        "antibody_name": "Garadacimab",
        "indication_text": "Hereditary angioedema (anti-FXIIa)",
        "disease_class_curated": "hematology_immunology",
        "route_curated": "SC",
        "dose_mg": "200 mg",
        "dose_freq": "Q4W",
        "half_life_days": "30",
        "fc_engineering": "IgG4",
        "fc_effector_status": "reduced (IgG4)",
        "fc_mutation_notes": "No Fc modifications reported",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "Maetzel et al., NEJM 2024; 390(1):21-31; PMID: 38169490"
    },
    {
        "antibody_name": "Nivolumab",
        "indication_text": "Multiple cancers (melanoma, NSCLC, RCC, HL, etc.)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "240 mg or 480 mg",
        "dose_freq": "Q2W (240 mg) or Q4W (480 mg)",
        "half_life_days": "25",
        "fc_engineering": "IgG4 (S228P)",
        "fc_effector_status": "reduced (IgG4, no ADCC intended)",
        "fc_mutation_notes": "S228P hinge stabilization; checkpoint inhibitor",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Opdivo); https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/125554s119lbl.pdf"
    },
    {
        "antibody_name": "Olaratumab",
        "indication_text": "Soft tissue sarcoma (withdrawn after Phase 3 failure)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "15 mg/kg",
        "dose_freq": "Day 1 & 8 of each 21-day cycle",
        "half_life_days": "11",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications; marketing authorization withdrawn",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Lartruvo, withdrawn); Tap et al., Lancet 2016; 388(10043):488-497; PMID: 27291997"
    },
    {
        "antibody_name": "Pemivibart",
        "indication_text": "COVID-19 pre-exposure prophylaxis (immunocompromised)",
        "disease_class_curated": "infectious",
        "route_curated": "IM",
        "dose_mg": "300 mg",
        "dose_freq": "single dose (seasonal re-dosing)",
        "half_life_days": "~80",
        "fc_engineering": "IgG1 with YTE half-life extension (M252Y/S254T/T256E)",
        "fc_effector_status": "reduced (YTE reduces FcγR binding)",
        "fc_mutation_notes": "M252Y/S254T/T256E for extended half-life",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA EUA (Pemgarda); https://www.fda.gov/media/177066/download"
    },
    {
        "antibody_name": "Ramucirumab",
        "indication_text": "Gastric cancer, NSCLC, CRC, HCC",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "8 mg/kg",
        "dose_freq": "Q2W",
        "half_life_days": "14",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Cyramza); https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/125477s039lbl.pdf"
    },
    {
        "antibody_name": "Regdanvimab",
        "indication_text": "COVID-19 treatment (anti-RBD neutralizing antibody)",
        "disease_class_curated": "infectious",
        "route_curated": "IV",
        "dose_mg": "40 mg/kg",
        "dose_freq": "single dose",
        "half_life_days": "25",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "EMA conditional marketing authorization; Kim et al., PNAS 2021; 118(36):e2107249118; PMID: 34385315"
    },
    {
        "antibody_name": "Relatlimab",
        "indication_text": "Melanoma (anti-LAG-3, co-formulated with nivolumab as Opdualag)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "160 mg (with nivolumab 480 mg)",
        "dose_freq": "Q4W",
        "half_life_days": "27",
        "fc_engineering": "IgG4 (S228P)",
        "fc_effector_status": "reduced (IgG4)",
        "fc_mutation_notes": "S228P hinge stabilization; anti-LAG-3 checkpoint",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Opdualag); https://www.accessdata.fda.gov/drugsatfda_docs/label/2022/761234s000lbl.pdf"
    },
    {
        "antibody_name": "Secukinumab",
        "indication_text": "Plaque psoriasis, psoriatic arthritis, ankylosing spondylitis",
        "disease_class_curated": "autoimmune",
        "route_curated": "SC",
        "dose_mg": "150–300 mg",
        "dose_freq": "Q4W (after loading)",
        "half_life_days": "27",
        "fc_engineering": "Wild-type IgG1κ",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications",
        "assay_platform": "ECL",
        "assay_generation": "tiered (drug-tolerant)",
        "source_citation": "FDA label (Cosentyx); https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/125504s057lbl.pdf"
    },
    {
        "antibody_name": "Sintilimab",
        "indication_text": "NSCLC, HCC, classical Hodgkin lymphoma (NMPA-approved)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "200 mg",
        "dose_freq": "Q3W",
        "half_life_days": "25",
        "fc_engineering": "IgG4 (S228P)",
        "fc_effector_status": "reduced (IgG4)",
        "fc_mutation_notes": "S228P; innovated by Innovent Biologics/Lilly",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "Shi et al., Lancet Oncol 2021; 22(4):510-517; PMID: 33676601"
    },
    {
        "antibody_name": "Tafolecimab",
        "indication_text": "Hypercholesterolemia (anti-PCSK9, China Phase 3)",
        "disease_class_curated": "metabolic",
        "route_curated": "SC",
        "dose_mg": "300 mg",
        "dose_freq": "Q4W",
        "half_life_days": "~15",
        "fc_engineering": "Wild-type IgG2",
        "fc_effector_status": "reduced (IgG2)",
        "fc_mutation_notes": "IgG2; Innovent Biologics China development",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "Han et al., JACC 2024; 83(4):388-399; NCT04982172"
    },
    {
        "antibody_name": "Tezepelumab",
        "indication_text": "Severe asthma (anti-TSLP, add-on maintenance)",
        "disease_class_curated": "autoimmune_allergic",
        "route_curated": "SC",
        "dose_mg": "210 mg",
        "dose_freq": "Q4W",
        "half_life_days": "26",
        "fc_engineering": "Wild-type IgG2λ",
        "fc_effector_status": "reduced (IgG2)",
        "fc_mutation_notes": "IgG2; anti-TSLP",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Tezspire); https://www.accessdata.fda.gov/drugsatfda_docs/label/2022/761224s000lbl.pdf"
    },
    {
        "antibody_name": "Tremelimumab",
        "indication_text": "Hepatocellular carcinoma, NSCLC (with durvalumab)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "300 mg (single priming dose) or 75 mg (regular dosing)",
        "dose_freq": "single dose (STRIDE regimen) or Q4W",
        "half_life_days": "22",
        "fc_engineering": "Wild-type IgG2",
        "fc_effector_status": "reduced (IgG2)",
        "fc_mutation_notes": "IgG2; anti-CTLA-4 checkpoint",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Imjudo); https://www.accessdata.fda.gov/drugsatfda_docs/label/2022/761270s000lbl.pdf"
    },
    # --- ENGINEERED (humanized) antibodies ---
    {
        "antibody_name": "Axatilimab",
        "indication_text": "Chronic graft-versus-host disease (cGVHD, anti-CSF1R)",
        "disease_class_curated": "hematology_immunology",
        "route_curated": "IV",
        "dose_mg": "0.15–1 mg/kg",
        "dose_freq": "Q2W",
        "half_life_days": "15",
        "fc_engineering": "IgG4",
        "fc_effector_status": "reduced (IgG4)",
        "fc_mutation_notes": "No specific Fc mutations reported; anti-CSF1R",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "Wolff et al., NEJM 2024; 390(18):1681-1693; PMID: 38718365"
    },
    {
        "antibody_name": "Belantamab",
        "indication_text": "Relapsed/refractory multiple myeloma (anti-BCMA ADC)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "2.5 mg/kg",
        "dose_freq": "Q3W",
        "half_life_days": "12",
        "fc_engineering": "Afucosylated IgG1 (ADCC-enhanced)",
        "fc_effector_status": "enhanced (afucosylation → enhanced ADCC)",
        "fc_mutation_notes": "Afucosylated via POTELLIGENT technology; ADC with MMAF",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Blenrep); https://www.accessdata.fda.gov/drugsatfda_docs/label/2022/761158s006lbl.pdf"
    },
    {
        "antibody_name": "Budigalimab",
        "indication_text": "Advanced solid tumors, SCLC (anti-PD-1, Phase 2/3)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "500 mg",
        "dose_freq": "Q4W",
        "half_life_days": "20",
        "fc_engineering": "IgG1 with effector-null mutations",
        "fc_effector_status": "silenced (effector-null IgG1)",
        "fc_mutation_notes": "Engineered Fc-silent IgG1; Abbvie development",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "Patel et al., Clin Cancer Res 2023; 29(6):1103-1112; NCT03000257"
    },
    {
        "antibody_name": "Crizanlizumab",
        "indication_text": "Sickle cell disease (VOC reduction, anti-P-selectin)",
        "disease_class_curated": "hematology",
        "route_curated": "IV",
        "dose_mg": "5 mg/kg",
        "dose_freq": "Q4W (after loading doses at weeks 0 and 2)",
        "half_life_days": "14.4",
        "fc_engineering": "Wild-type IgG2κ",
        "fc_effector_status": "reduced (IgG2)",
        "fc_mutation_notes": "IgG2; anti-P-selectin",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Adakveo); https://www.accessdata.fda.gov/drugsatfda_docs/label/2019/761128s000lbl.pdf"
    },
    {
        "antibody_name": "Depemokimab",
        "indication_text": "Severe eosinophilic asthma (anti-IL-5, ultra-long acting)",
        "disease_class_curated": "autoimmune_allergic",
        "route_curated": "SC",
        "dose_mg": "100 mg",
        "dose_freq": "Q6M (every 6 months)",
        "half_life_days": "56",
        "fc_engineering": "IgG1 with YTE half-life extension (M252Y/S254T/T256E)",
        "fc_effector_status": "reduced (YTE)",
        "fc_mutation_notes": "M252Y/S254T/T256E; extended dosing interval via YTE",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "Jackson et al., NEJM 2025; GSK prescribing info; NCT04718103"
    },
    {
        "antibody_name": "Domvanalimab",
        "indication_text": "NSCLC (anti-TIGIT, Phase 3 with zimberelimab)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "1200 mg",
        "dose_freq": "Q4W",
        "half_life_days": "17",
        "fc_engineering": "IgG1 with silenced Fc (Fc-dead)",
        "fc_effector_status": "silenced",
        "fc_mutation_notes": "Engineered Fc-null; avoids Treg depletion via anti-TIGIT",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "Johnson et al., NEJM 2024; 391(19):1775-1787; NCT04736173"
    },
    {
        "antibody_name": "Eculizumab",
        "indication_text": "PNH, aHUS, myasthenia gravis, NMOSD",
        "disease_class_curated": "hematology_immunology",
        "route_curated": "IV",
        "dose_mg": "900 mg (loading), 1200 mg (maintenance)",
        "dose_freq": "Q2W",
        "half_life_days": "11.3",
        "fc_engineering": "IgG2/4 hybrid Fc (reduced complement fixation)",
        "fc_effector_status": "silenced (IgG2/4 hybrid eliminates CDC)",
        "fc_mutation_notes": "CH1+hinge from IgG2, CH2+CH3 from IgG4; minimizes complement activation",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Soliris); https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/125166s445lbl.pdf"
    },
    {
        "antibody_name": "Elezanumab",
        "indication_text": "Acute spinal cord injury (anti-RGMa, Phase 2 discontinued)",
        "disease_class_curated": "neurology",
        "route_curated": "IV",
        "dose_mg": "1800 mg",
        "dose_freq": "Q4W",
        "half_life_days": "16",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications; AbbVie development",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "NCT04295538; Bhatt et al., JAMA Neurol 2024"
    },
    {
        "antibody_name": "Elotuzumab",
        "indication_text": "Multiple myeloma (anti-SLAMF7, with lenalidomide)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "10 mg/kg",
        "dose_freq": "QW for 2 cycles, then Q2W",
        "half_life_days": "20",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal (ADCC active via dual mechanism)",
        "fc_mutation_notes": "No Fc modifications; dual ADCC + direct NK activation",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Empliciti); https://www.accessdata.fda.gov/drugsatfda_docs/label/2022/761035s013lbl.pdf"
    },
    {
        "antibody_name": "Etaracizumab",
        "indication_text": "Advanced solid tumors (anti-αvβ3 integrin, Phase 2 discontinued)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "8 mg/kg",
        "dose_freq": "QW",
        "half_life_days": "10",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications; development discontinued",
        "assay_platform": "ELISA",
        "assay_generation": "bridging",
        "source_citation": "Delbaldo et al., Invest New Drugs 2008; 26(5):447-453; PMID: 18528635"
    },
    {
        "antibody_name": "Exidavnemab",
        "indication_text": "Parkinson's disease (anti-α-synuclein, Phase 2)",
        "disease_class_curated": "neurology",
        "route_curated": "IV",
        "dose_mg": "4500 mg",
        "dose_freq": "Q4W",
        "half_life_days": "~30",
        "fc_engineering": "IgG4 (effector-null)",
        "fc_effector_status": "reduced (IgG4)",
        "fc_mutation_notes": "IgG4; designed to avoid effector function in CNS target",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "Bhatt et al., Nature Med 2024; NCT04127695"
    },
    {
        "antibody_name": "Favezelimab",
        "indication_text": "Advanced solid tumors, DLBCL (anti-LAG-3, Phase 2 with pembrolizumab)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "800 mg",
        "dose_freq": "Q3W",
        "half_life_days": "19",
        "fc_engineering": "IgG4 (S228P)",
        "fc_effector_status": "reduced (IgG4)",
        "fc_mutation_notes": "S228P; anti-LAG-3 checkpoint; Merck development",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "Lakhani et al., JAMA Oncol 2023; NCT03598608"
    },
    {
        "antibody_name": "Gemtuzumab",
        "indication_text": "Acute myeloid leukemia (anti-CD33 ADC)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "3 mg/m²",
        "dose_freq": "Day 1, 4, 7 of cycle",
        "half_life_days": "2.6",
        "fc_engineering": "IgG4",
        "fc_effector_status": "reduced (IgG4, ADC payload-driven)",
        "fc_mutation_notes": "IgG4 ADC with calicheamicin payload; activity via ADC, not ADCC",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Mylotarg); https://www.accessdata.fda.gov/drugsatfda_docs/label/2020/761060s004lbl.pdf"
    },
    {
        "antibody_name": "Ibalizumab",
        "indication_text": "Multidrug-resistant HIV-1 infection",
        "disease_class_curated": "infectious",
        "route_curated": "IV",
        "dose_mg": "2000 mg loading, 800 mg maintenance",
        "dose_freq": "Q2W",
        "half_life_days": "25",
        "fc_engineering": "IgG4 (humanized)",
        "fc_effector_status": "reduced (IgG4)",
        "fc_mutation_notes": "IgG4; non-immunosuppressive CD4 blocker",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Trogarzo); https://www.accessdata.fda.gov/drugsatfda_docs/label/2018/761065s000lbl.pdf"
    },
    {
        "antibody_name": "Inebilizumab",
        "indication_text": "Neuromyelitis optica spectrum disorder (NMOSD, anti-CD19)",
        "disease_class_curated": "neurology_autoimmune",
        "route_curated": "IV",
        "dose_mg": "300 mg",
        "dose_freq": "Day 1 + Day 15, then Q6M",
        "half_life_days": "18",
        "fc_engineering": "Afucosylated IgG1 (ADCC-enhanced)",
        "fc_effector_status": "enhanced (afucosylated → enhanced CD19+ B-cell depletion)",
        "fc_mutation_notes": "Afucosylated; enhanced ADCC for B-cell depletion",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Uplizna); https://www.accessdata.fda.gov/drugsatfda_docs/label/2020/761142s000lbl.pdf"
    },
    {
        "antibody_name": "Lebrikizumab",
        "indication_text": "Moderate-to-severe atopic dermatitis (anti-IL-13)",
        "disease_class_curated": "autoimmune_allergic",
        "route_curated": "SC",
        "dose_mg": "250 mg",
        "dose_freq": "Q2W (after loading), then Q4W",
        "half_life_days": "25",
        "fc_engineering": "IgG4 (S228P)",
        "fc_effector_status": "reduced (IgG4)",
        "fc_mutation_notes": "S228P hinge stabilization; anti-IL-13 (not IL-4/13 dual)",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "EMA SmPC (Ebglyss); https://www.ema.europa.eu/en/documents/product-information/ebglyss-epar-product-information_en.pdf"
    },
    {
        "antibody_name": "Leronlimab",
        "indication_text": "HIV-1, triple-negative breast cancer, COVID-19 (anti-CCR5, Phase 2/3)",
        "disease_class_curated": "infectious_oncology",
        "route_curated": "SC",
        "dose_mg": "700 mg",
        "dose_freq": "QW",
        "half_life_days": "10",
        "fc_engineering": "IgG4",
        "fc_effector_status": "reduced (IgG4)",
        "fc_mutation_notes": "IgG4; CytoDyn development; multiple indications attempted",
        "assay_platform": "ELISA",
        "assay_generation": "bridging",
        "source_citation": "NCT02175680; Dhody et al., PLoS One 2018; 13(6):e0198090; PMID: 29856795"
    },
    {
        "antibody_name": "Levilimab",
        "indication_text": "Rheumatoid arthritis; COVID-19 severe (anti-IL-6R)",
        "disease_class_curated": "autoimmune",
        "route_curated": "SC",
        "dose_mg": "162 mg",
        "dose_freq": "QW or Q2W",
        "half_life_days": "14",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications; Biocad (Russia) development",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "Lomakin et al., Lancet Rheumatol 2021; 3(4):e272-e280; NCT05093972"
    },
    {
        "antibody_name": "Mirikizumab",
        "indication_text": "Ulcerative colitis; Crohn's disease (anti-IL-23p19)",
        "disease_class_curated": "autoimmune",
        "route_curated": "IV (induction) then SC (maintenance)",
        "dose_mg": "300 mg IV induction, 200 mg SC maintenance",
        "dose_freq": "Q4W IV x3, then Q4W SC",
        "half_life_days": "9.3",
        "fc_engineering": "IgG4 (S228P)",
        "fc_effector_status": "reduced (IgG4)",
        "fc_mutation_notes": "S228P; Lilly development",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Omvoh); https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/761202s000lbl.pdf"
    },
    {
        "antibody_name": "Mogamulizumab",
        "indication_text": "Cutaneous T-cell lymphoma (Mycosis fungoides/Sézary, anti-CCR4)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "1 mg/kg",
        "dose_freq": "QW for 4 weeks, then Q2W",
        "half_life_days": "17",
        "fc_engineering": "Defucosylated IgG1 (POTELLIGENT, enhanced ADCC)",
        "fc_effector_status": "enhanced (defucosylated → 100x enhanced ADCC)",
        "fc_mutation_notes": "Defucosylated via POTELLIGENT technology; Kyowa Kirin",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Poteligeo); https://www.accessdata.fda.gov/drugsatfda_docs/label/2018/761051s000lbl.pdf"
    },
    {
        "antibody_name": "Nemolizumab",
        "indication_text": "Prurigo nodularis; atopic dermatitis (anti-IL-31RA)",
        "disease_class_curated": "autoimmune_allergic",
        "route_curated": "SC",
        "dose_mg": "30 mg",
        "dose_freq": "Q4W",
        "half_life_days": "15",
        "fc_engineering": "Wild-type IgG2κ",
        "fc_effector_status": "reduced (IgG2)",
        "fc_mutation_notes": "IgG2; Galderma development",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Nemluvio); https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761346s000lbl.pdf"
    },
    {
        "antibody_name": "Nimotuzumab",
        "indication_text": "Glioma, head & neck cancer, EGFR+ tumors (approved in Asia/LatAm)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "200 mg",
        "dose_freq": "QW",
        "half_life_days": "~7",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications; intermediate EGFR affinity (avidity-dependent binding)",
        "assay_platform": "ELISA",
        "assay_generation": "bridging",
        "source_citation": "Crombet et al., J Clin Oncol 2004; 22(22):4587-4594; PMID: 15542810"
    },
    {
        "antibody_name": "Obinutuzumab",
        "indication_text": "CLL, follicular lymphoma (anti-CD20, glycoengineered)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "1000 mg",
        "dose_freq": "Q4W",
        "half_life_days": "28",
        "fc_engineering": "Glycoengineered IgG1 (GlycoMAb, bisected afucosylated)",
        "fc_effector_status": "enhanced (enhanced ADCC, reduced CDC vs rituximab)",
        "fc_mutation_notes": "GlycoMAb technology; bisected non-fucosylated Fc glycans → enhanced FcγRIIIa binding",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Gazyva); https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/125486s033lbl.pdf"
    },
    {
        "antibody_name": "Ocrelizumab",
        "indication_text": "Multiple sclerosis (RRMS and PPMS, anti-CD20)",
        "disease_class_curated": "neurology_autoimmune",
        "route_curated": "IV",
        "dose_mg": "600 mg",
        "dose_freq": "Q6M",
        "half_life_days": "26",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal (ADCC/CDC for B-cell depletion)",
        "fc_mutation_notes": "No Fc modifications; humanized from same parent as rituximab (2H7)",
        "assay_platform": "ECL",
        "assay_generation": "tiered (drug-tolerant)",
        "source_citation": "FDA label (Ocrevus); https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/761053s022lbl.pdf"
    },
    {
        "antibody_name": "Olokizumab",
        "indication_text": "Rheumatoid arthritis (anti-IL-6, Russia/China approved)",
        "disease_class_curated": "autoimmune",
        "route_curated": "SC",
        "dose_mg": "64 mg",
        "dose_freq": "Q4W",
        "half_life_days": "~30",
        "fc_engineering": "IgG4 (S228P)",
        "fc_effector_status": "reduced (IgG4)",
        "fc_mutation_notes": "S228P; R-Pharm development; approved Russia 2020",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "Nasonov et al., Ann Rheum Dis 2022; 81(4):469-479; PMID: 35131878"
    },
    {
        "antibody_name": "Palivizumab",
        "indication_text": "RSV prevention in high-risk infants (anti-RSV F protein)",
        "disease_class_curated": "infectious",
        "route_curated": "IM",
        "dose_mg": "15 mg/kg",
        "dose_freq": "Q4W (monthly, RSV season)",
        "half_life_days": "20",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications; first-generation RSV prophylactic mAb",
        "assay_platform": "ELISA",
        "assay_generation": "bridging",
        "source_citation": "FDA label (Synagis); https://www.accessdata.fda.gov/drugsatfda_docs/label/2014/103770s5175lbl.pdf"
    },
    {
        "antibody_name": "Penpulimab",
        "indication_text": "Classical Hodgkin lymphoma (anti-PD-1, NMPA-approved)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "200 mg",
        "dose_freq": "Q3W",
        "half_life_days": "18",
        "fc_engineering": "IgG1 with Fc engineered for reduced FcγR binding",
        "fc_effector_status": "silenced (Fc-engineered IgG1)",
        "fc_mutation_notes": "Fc engineered to minimize ADCC/CDC; Akeso Inc (China)",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "Song et al., Lancet Haematol 2022; 9(5):e366-e375; PMID: 35512730"
    },
    {
        "antibody_name": "Pertuzumab",
        "indication_text": "HER2+ breast cancer (with trastuzumab, anti-HER2 domain II)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "840 mg loading, 420 mg maintenance",
        "dose_freq": "Q3W",
        "half_life_days": "18",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal (ADCC active)",
        "fc_mutation_notes": "No Fc modifications; binds HER2 domain II (complementary to trastuzumab)",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Perjeta); https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/125409s134lbl.pdf"
    },
    {
        "antibody_name": "Polatuzumab",
        "indication_text": "Diffuse large B-cell lymphoma (anti-CD79b ADC, with R-CHP)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "1.8 mg/kg",
        "dose_freq": "Q3W",
        "half_life_days": "12",
        "fc_engineering": "Wild-type IgG1 (ADC with MMAE payload)",
        "fc_effector_status": "normal (effector function + ADC payload)",
        "fc_mutation_notes": "ADC via MC-vc-PAB-MMAE linker-payload; IgG1 Fc intact",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Polivy); https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/761121s016lbl.pdf"
    },
    {
        "antibody_name": "Recaticimab",
        "indication_text": "Hypercholesterolemia (anti-PCSK9, Phase 3 China)",
        "disease_class_curated": "metabolic",
        "route_curated": "SC",
        "dose_mg": "300 mg or 450 mg",
        "dose_freq": "Q4W or Q8W",
        "half_life_days": "~15",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications; Jiangsu Hengrui development",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "NCT04777175; He et al., JAMA Cardiol 2024"
    },
    {
        "antibody_name": "Rozanolixizumab",
        "indication_text": "Generalized myasthenia gravis (anti-FcRn)",
        "disease_class_curated": "neurology_autoimmune",
        "route_curated": "SC",
        "dose_mg": "420 mg or 630 mg (weight-based)",
        "dose_freq": "QW for 6 weeks per cycle",
        "half_life_days": "10",
        "fc_engineering": "IgG4 (S228P)",
        "fc_effector_status": "reduced (IgG4)",
        "fc_mutation_notes": "S228P; anti-FcRn blocks IgG recycling → IgG catabolism",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Rystiggo); https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/761335s000lbl.pdf"
    },
    {
        "antibody_name": "Satralizumab",
        "indication_text": "Neuromyelitis optica spectrum disorder (NMOSD, anti-IL-6R recycling Ab)",
        "disease_class_curated": "neurology_autoimmune",
        "route_curated": "SC",
        "dose_mg": "120 mg",
        "dose_freq": "Q2W x3 loading, then Q4W",
        "half_life_days": "30",
        "fc_engineering": "IgG2 with recycling antibody technology",
        "fc_effector_status": "reduced (IgG2)",
        "fc_mutation_notes": "pH-dependent IL-6R binding; recycling via FcRn (SA237 technology)",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Enspryng); https://www.accessdata.fda.gov/drugsatfda_docs/label/2020/761149s000lbl.pdf"
    },
    {
        "antibody_name": "Spesolimab",
        "indication_text": "Generalized pustular psoriasis (GPP) flares (anti-IL-36R)",
        "disease_class_curated": "autoimmune",
        "route_curated": "IV (flare) / SC (maintenance)",
        "dose_mg": "900 mg IV (flare), 300 mg SC (maintenance)",
        "dose_freq": "Single IV dose (flare); Q4W SC",
        "half_life_days": "25.5",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Spevigo); https://www.accessdata.fda.gov/drugsatfda_docs/label/2022/761244s000lbl.pdf"
    },
    {
        "antibody_name": "Sutimlimab",
        "indication_text": "Cold agglutinin disease (anti-C1s complement inhibitor)",
        "disease_class_curated": "hematology",
        "route_curated": "IV",
        "dose_mg": "6500 mg or 7500 mg (weight-based)",
        "dose_freq": "Q2W",
        "half_life_days": "24",
        "fc_engineering": "IgG4 (S228P, reduced effector)",
        "fc_effector_status": "reduced (IgG4)",
        "fc_mutation_notes": "S228P hinge stabilization; classical complement pathway inhibitor",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Enjaymo); https://www.accessdata.fda.gov/drugsatfda_docs/label/2022/761164s000lbl.pdf"
    },
    {
        "antibody_name": "Tafasitamab",
        "indication_text": "DLBCL (anti-CD19, Fc-enhanced, with lenalidomide)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "12 mg/kg",
        "dose_freq": "QW for cycles 1-3, then Q2W",
        "half_life_days": "17",
        "fc_engineering": "Fc-enhanced IgG1 (S239D/I332E for enhanced ADCC/ADCP)",
        "fc_effector_status": "enhanced (Fc point mutations → enhanced FcγRIIIa binding)",
        "fc_mutation_notes": "S239D/I332E Fc mutations; XmAb5574 platform; enhanced ADCC/ADCP",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "FDA label (Monjuvi); https://www.accessdata.fda.gov/drugsatfda_docs/label/2021/761163s003lbl.pdf"
    },
    {
        "antibody_name": "Tagitanlimab",
        "indication_text": "Solid tumors (anti-PD-L1, China Phase 3)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "1200 mg",
        "dose_freq": "Q3W",
        "half_life_days": "~18",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications reported; Kelun-Biotech development",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "NCT04056247; Yang et al., Lancet Oncol 2024"
    },
    {
        "antibody_name": "Timigutuzumab",
        "indication_text": "Breast cancer (anti-HER2, biparatopic, Phase 1/2)",
        "disease_class_curated": "oncology",
        "route_curated": "IV",
        "dose_mg": "10–30 mg/kg (dose-escalation)",
        "dose_freq": "Q3W",
        "half_life_days": "~14",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications; biparatopic anti-HER2; early clinical",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "NCT03602079; Desai et al., J Clin Oncol 2020; 38(15_suppl):1010"
    },
    {
        "antibody_name": "Vunakizumab",
        "indication_text": "Psoriasis, psoriatic arthritis (anti-IL-17A, Phase 3 China)",
        "disease_class_curated": "autoimmune",
        "route_curated": "SC",
        "dose_mg": "80 mg or 160 mg",
        "dose_freq": "Q4W (after loading)",
        "half_life_days": "~25",
        "fc_engineering": "Wild-type IgG1",
        "fc_effector_status": "normal",
        "fc_mutation_notes": "No Fc modifications; CStone/Pfizer development",
        "assay_platform": "ECL",
        "assay_generation": "tiered",
        "source_citation": "NCT05003297; Zhang et al., Br J Dermatol 2024"
    },
]

OUT = Path("data/curated_66_clinical_metadata.csv")
fields = list(RECORDS[0].keys())

with open(OUT, "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=fields)
    w.writeheader()
    w.writerows(RECORDS)

print("Wrote {} records to {}".format(len(RECORDS), OUT))
print("Fields: {}".format(fields))
