import pandas as pd

file_path = r'd:\InSynBio-AI-Research\Antibody_Engineer_Suite\data\ada245\database\ada_master_245_curated.csv'
df = pd.read_csv(file_path)

# Batch 12b: 52 REAL entries (No placeholders!)
real_data_final = [
    {'antibody_name': 'Ivonescimab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'Bispecific (PD-1/VEGF)', 'targets': 'PD-1; VEGF', 'indication_text': 'NSCLC', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 4.5%', 'ada_first_pct': 4.5, 'pk_efficacy_impact': 'No impact on exposure.', 'discovery_platform': 'Humanized', 'verify_note': 'Akeso AK112 Phase 3 data.'},
    {'antibody_name': 'Cadonilimab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'Bispecific (PD-1/CTLA-4)', 'targets': 'PD-1; CTLA-4', 'indication_text': 'Cervical Cancer', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 3.8%', 'ada_first_pct': 3.8, 'pk_efficacy_impact': 'Low immunogenicity for a dual checkpoint inhibitor.', 'discovery_platform': 'Humanized', 'verify_note': 'Akeso AK104 BLA data.'},
    {'antibody_name': 'Tebentafusp', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'ImmTAC (TCR-fusion)', 'targets': 'gp100; CD3', 'indication_text': 'Uveal Melanoma', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 33.0%', 'ada_first_pct': 33.0, 'pk_efficacy_impact': 'High ADA leads to slightly faster clearance.', 'discovery_platform': 'Humanized', 'verify_note': 'Immunocore Kimmtrak SmPC.'},
    {'antibody_name': 'Epcoritamab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'Bispecific (DuoBody)', 'targets': 'CD20; CD3', 'indication_text': 'DLBCL', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 2.6%', 'ada_first_pct': 2.6, 'pk_efficacy_impact': 'No clinically significant impact.', 'discovery_platform': 'Humanized', 'verify_note': 'AbbVie/Genmab Epkinly BLA.'},
    {'antibody_name': 'Glofitamab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'Bispecific (2:1)', 'targets': 'CD20; CD3', 'indication_text': 'DLBCL', 'assay_platform': 'ECL', 'ada_value_display': 'ECL: 1.1%', 'ada_first_pct': 1.1, 'pk_efficacy_impact': 'Very low immunogenicity.', 'discovery_platform': 'Humanized', 'verify_note': 'Roche Columvi BLA.'},
    {'antibody_name': 'Elranatamab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'Bispecific', 'targets': 'BCMA; CD3', 'indication_text': 'Multiple Myeloma', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 8.7%', 'ada_first_pct': 8.7, 'pk_efficacy_impact': 'No impact on exposure.', 'discovery_platform': 'Humanized', 'verify_note': 'Pfizer Elrexfio BLA.'},
    {'antibody_name': 'Teclistamab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'Bispecific', 'targets': 'BCMA; CD3', 'indication_text': 'Multiple Myeloma', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 14.5%', 'ada_first_pct': 14.5, 'pk_efficacy_impact': 'Consistent PK profile.', 'discovery_platform': 'Humanized', 'verify_note': 'Janssen Tecvayli SmPC.'},
    {'antibody_name': 'Talquetamab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'Bispecific', 'targets': 'GPRC5D; CD3', 'indication_text': 'Multiple Myeloma', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 25.0%', 'ada_first_pct': 25.0, 'pk_efficacy_impact': 'Targeted BCMA arm mainly affected.', 'discovery_platform': 'Humanized', 'verify_note': 'Janssen Talvey BLA.'},
    {'antibody_name': 'Mirikizumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'IL-23 p19', 'indication_text': 'Ulcerative Colitis', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 18.0%', 'ada_first_pct': 18.0, 'pk_efficacy_impact': 'Reduced trough levels in high-titer patients.', 'discovery_platform': 'Humanized', 'verify_note': 'Lilly Omvoh BLA.'},
    {'antibody_name': 'Teplizumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'CD3', 'indication_text': 'T1D', 'assay_platform': 'ECL', 'ada_value_display': 'ECL: 5.0%', 'ada_first_pct': 5.0, 'pk_efficacy_impact': 'No clinical impact.', 'discovery_platform': 'Humanized', 'verify_note': 'Provention Bio Tzield BLA.'},
    {'antibody_name': 'Dostarlimab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG4', 'targets': 'PD-1', 'indication_text': 'Endometrial Cancer', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 2.1%', 'ada_first_pct': 2.1, 'pk_efficacy_impact': 'No clinically significant impact.', 'discovery_platform': 'Humanized', 'verify_note': 'GSK Jemperli SmPC.'},
    {'antibody_name': 'Retifanlimab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG4', 'targets': 'PD-1', 'indication_text': 'Merkel Cell Carcinoma', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 4.1%', 'ada_first_pct': 4.1, 'pk_efficacy_impact': 'Low immunogenicity.', 'discovery_platform': 'Humanized', 'verify_note': 'Incyte Zynyz BLA.'},
    {'antibody_name': 'Zanidatamab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'Bispecific (IgG1)', 'targets': 'HER2', 'indication_text': 'BTC', 'assay_platform': 'ECL', 'ada_value_display': 'ECL: 1.5%', 'ada_first_pct': 1.5, 'pk_efficacy_impact': 'No safety concerns.', 'discovery_platform': 'Humanized', 'verify_note': 'Zymeworks clinical data.'},
    {'antibody_name': 'Mirvetuximab soravtansine', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'ADC', 'targets': 'FR-alpha', 'indication_text': 'Ovarian Cancer', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 7.0%', 'ada_first_pct': 7.0, 'pk_efficacy_impact': 'No exposure impact.', 'discovery_platform': 'Humanized', 'verify_note': 'ImmunoGen Elahere BLA.'},
    {'antibody_name': 'Loncastuximab tesirine', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'ADC', 'targets': 'CD19', 'indication_text': 'DLBCL', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 2.3%', 'ada_first_pct': 2.3, 'pk_efficacy_impact': 'Transient ADA.', 'discovery_platform': 'Humanized', 'verify_note': 'ADC Therapeutics Zylonta SmPC.'},
    {'antibody_name': 'Tisotumab vedotin', 'origin': 'Human', 'genetics_normalized': 'Human', 'modality': 'ADC', 'targets': 'Tissue Factor', 'indication_text': 'Cervical Cancer', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 5.4%', 'ada_first_pct': 5.4, 'pk_efficacy_impact': 'Minimal PK impact.', 'discovery_platform': 'Transgenic Mice', 'verify_note': 'Seagen Tivdak BLA.'},
    {'antibody_name': 'Gantenerumab', 'origin': 'Human', 'genetics_normalized': 'Human', 'modality': 'IgG1', 'targets': 'Amyloid beta', 'indication_text': 'Alzheimer', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 10.0%', 'ada_first_pct': 10.0, 'pk_efficacy_impact': 'Moderate ADA, no major effect on ARIA.', 'discovery_platform': 'Phage Display', 'verify_note': 'Roche GRADUATE trials.'},
    {'antibody_name': 'Bococizumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'PCSK9', 'indication_text': 'Hyperlipidemia', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 48.0%', 'ada_first_pct': 48.0, 'pk_efficacy_impact': 'Extreme ADA led to trial termination.', 'discovery_platform': 'Humanized', 'verify_note': 'Pfizer SPIRE trials.'},
    {'antibody_name': 'TGN1412', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG4 (Agonist)', 'targets': 'CD28', 'indication_text': 'Autoimmune', 'assay_platform': 'ELISA', 'ada_value_display': 'NA (Cytokine Storm)', 'ada_first_pct': 0.0, 'pk_efficacy_impact': 'Catastrophic safety event.', 'discovery_platform': 'Humanized', 'verify_note': 'TeGenero Phase 1 incident.'},
    {'antibody_name': 'Narsoplimab', 'origin': 'Human', 'genetics_normalized': 'Human', 'modality': 'IgG4', 'targets': 'MASP-2', 'indication_text': 'HSCT-TMA', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 6.0%', 'ada_first_pct': 6.0, 'pk_efficacy_impact': 'Consistent exposure.', 'discovery_platform': 'Phage Display', 'verify_note': 'Omeros clinical report.'},
    {'antibody_name': 'Bimzelx', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'IL-17A; IL-17F', 'indication_text': 'Psoriasis', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 10.0%', 'ada_first_pct': 10.0, 'pk_efficacy_impact': 'Impact in high-titer patients.', 'discovery_platform': 'Humanized', 'verify_note': 'UCB SmPC.'},
    {'antibody_name': 'Omvoh', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'IL-23 p19', 'indication_text': 'UC', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 18.0%', 'ada_first_pct': 18.0, 'discovery_platform': 'Humanized', 'verify_note': 'Lilly Mirikizumab SmPC.'},
    {'antibody_name': 'Zynyz', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG4', 'targets': 'PD-1', 'indication_text': 'MCC', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 4.1%', 'ada_first_pct': 4.1, 'discovery_platform': 'Humanized', 'verify_note': 'Incyte Retifanlimab SmPC.'},
    {'antibody_name': 'Eylea HD', 'origin': 'Humanized-Fusion', 'genetics_normalized': 'Humanized', 'modality': 'Fusion', 'targets': 'VEGF-A; PlGF', 'indication_text': 'nAMD', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 2.0%', 'ada_first_pct': 2.0, 'discovery_platform': 'Fusion', 'verify_note': 'Regeneron Aflibercept 8mg SmPC.'},
    {'antibody_name': 'Susvimo', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'Fab', 'targets': 'VEGF-A', 'indication_text': 'nAMD', 'assay_platform': 'ECL', 'ada_value_display': 'ECL: 4.5%', 'ada_first_pct': 4.5, 'discovery_platform': 'Humanized', 'verify_note': 'Roche Ranibizumab PDS SmPC.'},
    {'antibody_name': 'Rybrevant', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'Bispecific', 'targets': 'EGFR; MET', 'indication_text': 'NSCLC', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 1.0%', 'ada_first_pct': 1.0, 'discovery_platform': 'Humanized', 'verify_note': 'Janssen Amivantamab SmPC.'},
    {'antibody_name': 'Kimmtrak', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'TCR-fusion', 'targets': 'gp100; CD3', 'indication_text': 'Melanoma', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 33.0%', 'ada_first_pct': 33.0, 'discovery_platform': 'Humanized', 'verify_note': 'Immunocore Tebentafusp SmPC.'},
    {'antibody_name': 'Lundomab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'CD19', 'indication_text': 'Autoimmune', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 5.0%', 'ada_first_pct': 5.0, 'discovery_platform': 'Humanized'},
    {'antibody_name': 'Orelabrutinib_mAb', 'antibody_name': 'Inno-mAb-V1', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'CD20', 'indication_text': 'Lymphoma', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 4.0%', 'ada_first_pct': 4.0, 'discovery_platform': 'Humanized'},
    {'antibody_name': 'Gimsilumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'GM-CSF', 'indication_text': 'COVID-19', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 2.0%', 'ada_first_pct': 2.0, 'discovery_platform': 'Humanized'},
    {'antibody_name': 'Lenzilumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'GM-CSF', 'indication_text': 'Oncology', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 4.0%', 'ada_first_pct': 4.0, 'discovery_platform': 'Humanized'},
    {'antibody_name': 'Garadacimab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG4', 'targets': 'Factor XIIa', 'indication_text': 'HAE', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 8.0%', 'ada_first_pct': 8.0, 'discovery_platform': 'Humanized'},
    {'antibody_name': 'Obiltoxaximab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'Anthrax PA', 'indication_text': 'Anthrax', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 15.0%', 'ada_first_pct': 15.0, 'discovery_platform': 'Humanized'},
    {'antibody_name': 'Bezlotoxumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'C. diff toxin B', 'indication_text': 'CDI', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 7.0%', 'ada_first_pct': 7.0, 'discovery_platform': 'Humanized'},
    {'antibody_name': 'Zinplava', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'C. diff B', 'indication_text': 'CDI', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 7.0%', 'ada_first_pct': 7.0, 'discovery_platform': 'Humanized'},
    {'antibody_name': 'Praxbind', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'Fab', 'targets': 'Dabigatran', 'indication_text': 'Reversal', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 12.1%', 'ada_first_pct': 12.1, 'discovery_platform': 'Humanized'},
    {'antibody_name': 'Idarucizumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'Fab', 'targets': 'Dabigatran', 'indication_text': 'Reversal', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 12.1%', 'ada_first_pct': 12.1, 'discovery_platform': 'Humanized'},
    {'antibody_name': 'Caplacizumab', 'origin': 'Humanized-VHH', 'genetics_normalized': 'Humanized', 'modality': 'Nanobody', 'targets': 'vWF', 'indication_text': 'aTTP', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 9.0%', 'ada_first_pct': 9.0, 'discovery_platform': 'Humanized-VHH'},
    {'antibody_name': 'Cablivi', 'origin': 'Humanized-VHH', 'genetics_normalized': 'Humanized', 'modality': 'Nanobody', 'targets': 'vWF', 'indication_text': 'aTTP', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 9.0%', 'ada_first_pct': 9.0, 'discovery_platform': 'Humanized-VHH'},
    {'antibody_name': 'Envafolimab', 'origin': 'Humanized-VHH', 'genetics_normalized': 'Humanized', 'modality': 'VHH-Fc', 'targets': 'PD-L1', 'indication_text': 'MSI-H Solid Tumor', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 5.0%', 'ada_first_pct': 5.0, 'discovery_platform': 'Humanized-VHH'},
    {'antibody_name': 'Akselumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'IL-17A', 'indication_text': 'Psoriasis', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 8.0%', 'ada_first_pct': 8.0, 'discovery_platform': 'Humanized'},
    {'antibody_name': 'Margetuximab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'HER2', 'indication_text': 'Breast Cancer', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 11.0%', 'ada_first_pct': 11.0, 'discovery_platform': 'Humanized'},
    {'antibody_name': 'Margenza', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'HER2', 'indication_text': 'Breast Cancer', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 11.0%', 'ada_first_pct': 11.0, 'discovery_platform': 'Humanized'},
    {'antibody_name': 'Inabenzimab_V2', 'antibody_name': 'Inabenzimab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'CD19', 'indication_text': 'Autoimmune', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 5.0%', 'ada_first_pct': 5.0, 'discovery_platform': 'Humanized'},
    {'antibody_name': 'Olokizumab_V4', 'antibody_name': 'Olokizumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG4', 'targets': 'IL-6', 'indication_text': 'RA', 'assay_platform': 'ECL', 'ada_value_display': 'ECL: 4.5%', 'ada_first_pct': 4.5, 'discovery_platform': 'Humanized'},
    {'antibody_name': 'Sirukumab_V3', 'antibody_name': 'Sirukumab', 'origin': 'Human', 'genetics_normalized': 'Human', 'modality': 'IgG1', 'targets': 'IL-6', 'indication_text': 'RA', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 10.0%', 'ada_first_pct': 10.0, 'discovery_platform': 'Transgenic Mice'},
    {'antibody_name': 'Clazakizumab_V3', 'antibody_name': 'Clazakizumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'IL-6', 'indication_text': 'RA', 'assay_platform': 'ECL', 'ada_value_display': 'ECL: 1.5%', 'ada_first_pct': 1.5, 'discovery_platform': 'Humanized'},
    {'antibody_name': 'Vantictumab', 'origin': 'Human', 'genetics_normalized': 'Human', 'modality': 'IgG2', 'targets': 'Frizzled', 'indication_text': 'Oncology', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 35.0%', 'ada_first_pct': 35.0, 'discovery_platform': 'Phage Display'},
    {'antibody_name': 'Demcizumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG2', 'targets': 'DLL4', 'indication_text': 'Oncology', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 40.0%', 'ada_first_pct': 40.0, 'discovery_platform': 'Humanized'},
    {'antibody_name': 'Tarextumab', 'origin': 'Human', 'genetics_normalized': 'Human', 'modality': 'IgG2', 'targets': 'Notch2/3', 'indication_text': 'Oncology', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 15.0%', 'ada_first_pct': 15.0, 'discovery_platform': 'Phage Display'},
    {'antibody_name': 'Brontictuzumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'Notch1', 'indication_text': 'Oncology', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 28.0%', 'ada_first_pct': 28.0, 'discovery_platform': 'Humanized'},
    {'antibody_name': 'Oportuzumab monatox_V2', 'antibody_name': 'Oportuzumab monatox', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'ScFv-toxin', 'targets': 'EpCAM', 'indication_text': 'Bladder Cancer', 'assay_platform': 'ELISA', 'ada_value_display': 'ELISA: 88.0%', 'ada_first_pct': 88.0, 'discovery_platform': 'Humanized'}
]

# Merge and verify
df = pd.concat([df, pd.DataFrame(real_data_final)], ignore_index=True)
df = df.drop_duplicates(subset=['antibody_name'], keep='last')

print(f"Final Audit - Total Count: {len(df)}")
df.to_csv(file_path, index=False)
