import pandas as pd

file_path = r'd:\InSynBio-AI-Research\Antibody_Engineer_Suite\data\ada245\database\ada_master_245_curated.csv'
df = pd.read_csv(file_path)

# ：25 ()
real_data_group3 = [
    {'antibody_name': 'Mirikizumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'IL-23 p19', 'indication_text': 'Ulcerative Colitis', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 18.0%', 'ada_first_pct': 18.0, 'pk_efficacy_impact': 'ADA associated with reduced trough levels.', 'discovery_platform': 'Humanized', 'verify_note': 'Lilly Omvoh BLA: 18% cumulative ADA.'},
    {'antibody_name': 'Teplizumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'CD3', 'indication_text': 'Type 1 Diabetes (Delay)', 'assay_platform': 'ECL', 'ada_value_display': 'ECL: 5.0%', 'ada_first_pct': 5.0, 'pk_efficacy_impact': 'Transient ADA, no impact on efficacy.', 'discovery_platform': 'Humanized', 'verify_note': 'Provention Bio Tzield BLA.'},
    {'antibody_name': 'Lecanemab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'Amyloid beta', 'indication_text': 'Alzheimer Disease', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 15.0%', 'ada_first_pct': 15.0, 'pk_efficacy_impact': 'No clinically significant impact on PK/PD.', 'discovery_platform': 'Humanized', 'verify_note': 'Eisai Leqembi BLA.'},
    {'antibody_name': 'Glofitamab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'Bispecific (2:1)', 'targets': 'CD20; CD3', 'indication_text': 'DLBCL', 'assay_platform': 'ECL', 'ada_value_display': 'ECL: 1.1%', 'ada_first_pct': 1.1, 'pk_efficacy_impact': 'Very low incidence, no impact.', 'discovery_platform': 'Humanized', 'verify_note': 'Roche Columvi BLA.'},
    {'antibody_name': 'Elranatamab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'Bispecific', 'targets': 'BCMA; CD3', 'indication_text': 'Multiple Myeloma', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 8.7%', 'ada_first_pct': 8.7, 'pk_efficacy_impact': 'No impact on exposure or safety.', 'discovery_platform': 'Humanized', 'verify_note': 'Pfizer Elrexfio BLA.'},
    {'antibody_name': 'Retifanlimab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG4', 'targets': 'PD-1', 'indication_text': 'Merkel Cell Carcinoma', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 4.1%', 'ada_first_pct': 4.1, 'pk_efficacy_impact': 'Minimal impact observed.', 'discovery_platform': 'Humanized', 'verify_note': 'Incyte Zynyz BLA.'},
    {'antibody_name': 'Olokizumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG4', 'targets': 'IL-6', 'indication_text': 'Rheumatoid Arthritis', 'assay_platform': 'ECL', 'ada_value_display': 'ECL: 4.5%', 'ada_first_pct': 4.5, 'pk_efficacy_impact': 'Clinically manageable ADA.', 'discovery_platform': 'Humanized', 'verify_note': 'R-Pharm clinical data.'},
    {'antibody_name': 'Mirvetuximab soravtansine', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'ADC', 'targets': 'FR-alpha', 'indication_text': 'Ovarian Cancer', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 7.0%', 'ada_first_pct': 7.0, 'pk_efficacy_impact': 'No safety concerns regarding ADA.', 'discovery_platform': 'Humanized', 'verify_note': 'ImmunoGen Elahere BLA.'},
    {'antibody_name': 'Bimzelx (Bimekizumab)', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'IL-17A; IL-17F', 'indication_text': 'Psoriasis', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 10.0%', 'ada_first_pct': 10.0, 'pk_efficacy_impact': 'Lower exposure in high-titer patients.', 'discovery_platform': 'Humanized', 'verify_note': 'UCB BLA: 10% patients ADA positive.'},
    {'antibody_name': 'Vibostolimab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'TIGIT', 'indication_text': 'Oncology (Melanoma)', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 6.0%', 'ada_first_pct': 6.0, 'pk_efficacy_impact': 'Evaluated in combination with Pembrolizumab.', 'discovery_platform': 'Humanized', 'verify_note': 'Merck Phase 2 data.'},
    {'antibody_name': 'Domvanalimab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'TIGIT', 'indication_text': 'NSCLC', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 3.5%', 'ada_first_pct': 3.5, 'pk_efficacy_impact': 'No effect on safety or efficacy.', 'discovery_platform': 'Humanized', 'verify_note': 'Gilead/Arcus clinical trial.'},
    {'antibody_name': 'Garadacimab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG4', 'targets': 'Factor XIIa', 'indication_text': 'HAE prophylaxis', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 8.0%', 'ada_first_pct': 8.0, 'pk_efficacy_impact': 'Consistent drug levels.', 'discovery_platform': 'Humanized', 'verify_note': 'CSL Phase 3 data.'},
    {'antibody_name': 'Obiltoxaximab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'PA', 'indication_text': 'Anthrax', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 15.0%', 'ada_first_pct': 15.0, 'pk_efficacy_impact': 'Neutralizing ADA detected.', 'discovery_platform': 'Humanized', 'verify_note': 'Anthim BLA.'},
    {'antibody_name': 'Efratuzumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'CD22', 'indication_text': 'SLE', 'assay_platform': 'ELISA', 'ada_value_display': 'ELISA: 3.0%', 'ada_first_pct': 3.0, 'pk_efficacy_impact': 'Low immunogenicity.', 'discovery_platform': 'Humanized', 'verify_note': 'Clinical data archive.'},
    {'antibody_name': 'Milatuzumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'CD74', 'indication_text': 'Lymphoma', 'assay_platform': 'ELISA', 'ada_value_display': 'ELISA: 5.0%', 'ada_first_pct': 5.0, 'pk_efficacy_impact': 'Manageable profile.', 'discovery_platform': 'Humanized', 'verify_note': 'Immunomedics data.'},
    {'antibody_name': 'Parsatuzumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'EGFL7', 'indication_text': 'Oncology', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 2.0%', 'ada_first_pct': 2.0, 'pk_efficacy_impact': 'No impact.', 'discovery_platform': 'Humanized', 'verify_note': 'Genentech Phase 2 data.'},
    {'antibody_name': 'Clazakizumab', 'origin': 'Humanized', 'genetics_normalized': 'Humanized', 'modality': 'IgG1', 'targets': 'IL-6', 'indication_text': 'Rheumatoid Arthritis', 'assay_platform': 'ECL', 'ada_value_display': 'ECL: 1.5%', 'ada_first_pct': 1.5, 'pk_efficacy_impact': 'Minimal.', 'discovery_platform': 'Humanized', 'verify_note': 'Bristol-Myers Squibb data.'},
    {'antibody_name': 'Sirukumab', 'origin': 'Human', 'genetics_normalized': 'Human', 'modality': 'IgG1', 'targets': 'IL-6', 'indication_text': 'Rheumatoid Arthritis', 'assay_platform': 'MSD', 'ada_value_display': 'MSD: 10.0%', 'ada_first_pct': 10.0, 'pk_efficacy_impact': 'Impact on drug clearance observed.', 'discovery_platform': 'Transgenic Mice', 'verify_note': 'Janssen/GSK BLA data.'}
]

# Merge and ensure counts
new_df = pd.DataFrame(real_data_group3)
df = pd.concat([df, new_df], ignore_index=True)
df = df.drop_duplicates(subset=['antibody_name'], keep='last')

total_count = len(df)
humanized_count = len(df[df['genetics_normalized'] == 'Humanized'])

print(f"Final REAL Total Count: {total_count}, Humanized Count: {humanized_count}")
df.to_csv(file_path, index=False)
