"""
PAG1 HADDOCK3 Refinement + Multi-Structure ΔΔG Pipeline
========================================================
Full workflow:
  1. Split AF2-Multimer PDB into antibody + antigen
  2. Generate HADDOCK3 AIRs from CDR→antigen interface contacts
  3. Run HADDOCK3 flexible refinement (WSL)
  4. Collect top-N refined structures
  5. Run EvoEF2 + MM/GBSA ΔΔG scan on multiple structures
  6. Compare AF2 vs HADDOCK results → consensus ranking

Requirements:
  - HADDOCK3 installed in WSL (Ubuntu-22.04)
  - EvoEF2, OpenMM in affmat conda env (Windows)
"""

import os, sys, json, shutil, subprocess, time, tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

# ── Configuration ─────────────────────────────────────────────────────────────

AF2_PDB = Path(
    r"D:\InSynBio-AI-Research\Antibody_Engineer_Suite\projects\PAG-1 project"
    r"\7m_humanPAG1\7m_humanPAG1_df5fc"
    r"\7m_humanPAG1_df5fc_relaxed_rank_001_alphafold2_multimer_v3_model_5_seed_000.pdb"
)
AB_CHAINS = ["A", "B"]   # VH, VL
AG_CHAINS = ["C"]         # PAG1

WORK_DIR = Path(
    r"D:\InSynBio-AI-Research\Antibody_Engineer_Suite\projects\PAG-1 project"
    r"\haddock3_refinement"
)
WORK_DIR.mkdir(parents=True, exist_ok=True)

# CDR interface residues (known from analysis: CDR3 = primary binder)
# VH CDR1: 26-35, CDR2: 49-66, CDR3: 97-107
VH_CDR_ACTIVE = list(range(95, 108))  # CDR3 active (primary contact)
VH_CDR_PASSIVE = list(range(26, 36)) + list(range(49, 58))  # CDR1+CDR2 passive

# PAG1 active residues: N-terminal functional region
AG_ACTIVE = list(range(1, 9))    # MGPAGSLL
AG_PASSIVE = list(range(9, 16))  # GSGQMQIT (near active)


# ── Step 1: Split PDB into chains ────────────────────────────────────────────

def split_pdb(pdb_path, out_dir):
    """Split complex PDB into individual chain files."""
    chains = {}
    with open(pdb_path) as f:
        for line in f:
            if line.startswith(("ATOM", "HETATM")):
                chain_id = line[21]
                chains.setdefault(chain_id, []).append(line)

    out_files = {}
    for chain_id, lines in chains.items():
        out_path = out_dir / f"chain_{chain_id}.pdb"
        with open(out_path, "w") as f:
            for line in lines:
                f.write(line)
            f.write("END\n")
        out_files[chain_id] = out_path
        print(f"  Chain {chain_id}: {len(lines)} atoms -> {out_path.name}")

    # Also create antibody (A+B) combined PDB
    ab_path = out_dir / "antibody_AB.pdb"
    with open(ab_path, "w") as f:
        for cid in AB_CHAINS:
            if cid in chains:
                for line in chains[cid]:
                    f.write(line)
                f.write("TER\n")
        f.write("END\n")
    out_files["AB"] = ab_path
    print(f"  Combined AB: -> {ab_path.name}")
    return out_files


# ── Step 2: Generate HADDOCK3 AIR restraints ──────────────────────────────────

def generate_air_tbl(out_path, active_ab, passive_ab, active_ag, passive_ag,
                     ab_chain="A", ag_chain="C", ab_segid="A", ag_segid="B"):
    """
    Generate HADDOCK-format Ambiguous Interaction Restraints (AIR) .tbl file.

    AIR format:
      assign (resid X and segid A) (resid Y and segid B) 2.0 2.0 0.0
    Each active residue on one side must be within 2A of any active/passive
    on the other side.
    """
    lines = []
    lines.append("! HADDOCK AIR restraints for PAG1 antibody-antigen refinement")
    lines.append("! Generated by pag1_haddock3_pipeline.py")
    lines.append("!")

    # Active Ab -> Active/Passive Ag
    all_ag = list(set(active_ag + passive_ag))
    for ab_res in active_ab:
        target_residues = all_ag
        if not target_residues:
            continue
        or_stmts = " or\n        ".join(
            f"(resid {r} and segid {ag_segid})" for r in target_residues
        )
        lines.append(f"assign (resid {ab_res} and segid {ab_segid})")
        lines.append(f"       (")
        lines.append(f"        {or_stmts}")
        lines.append(f"       ) 2.0 2.0 0.0")

    # Active Ag -> Active/Passive Ab
    all_ab = list(set(active_ab + passive_ab))
    for ag_res in active_ag:
        or_stmts = " or\n        ".join(
            f"(resid {r} and segid {ab_segid})" for r in all_ab
        )
        lines.append(f"assign (resid {ag_res} and segid {ag_segid})")
        lines.append(f"       (")
        lines.append(f"        {or_stmts}")
        lines.append(f"       ) 2.0 2.0 0.0")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  AIR restraints: {len(active_ab)} Ab active + {len(active_ag)} Ag active")
    print(f"  Written to: {out_path.name}")
    return out_path


# ── Step 3: Generate HADDOCK3 configuration ───────────────────────────────────

def generate_haddock3_cfg(work_dir, ab_pdb, ag_pdb, air_tbl, n_models=20):
    """
    Generate HADDOCK3 TOML configuration for refinement protocol:
      topoaa → rigidbody (light) → flexref → emref
    """
    # Convert Windows paths to WSL paths
    def wsl_path(p):
        return str(p).replace("D:\\", "/mnt/d/").replace("\\", "/")

    cfg = f"""# HADDOCK3 configuration for PAG1 antibody-antigen refinement
# Protocol: topology → rigid body → flexible refinement → EM refinement

run_dir = "{wsl_path(work_dir / 'haddock3_run')}"
ncores = 4

# Input molecules
molecules = [
    "{wsl_path(ab_pdb)}",
    "{wsl_path(ag_pdb)}",
]

# Step 1: Generate topology
[topoaa]

# Step 2: Rigid-body sampling (light — just to establish orientation)
[rigidbody]
ambig_fname = "{wsl_path(air_tbl)}"
sampling = {n_models * 5}
noecv = false

# Step 3: Semi-flexible refinement (the key step for peptide)
[flexref]
ambig_fname = "{wsl_path(air_tbl)}"
tolerance = 5

# Step 4: Energy minimization refinement
[emref]
ambig_fname = "{wsl_path(air_tbl)}"

# Step 5: Clustering
[clustfcc]
clust_cutoff = 0.6
min_population = 2

# Step 6: CAPRI evaluation (scoring)
[caprieval]
"""

    cfg_path = work_dir / "haddock3_pag1.cfg"
    with open(cfg_path, "w", newline="\n") as f:
        f.write(cfg)
    print(f"  HADDOCK3 config: {cfg_path.name}")
    print(f"  Rigid body sampling: {n_models * 5}")
    print(f"  Run dir: haddock3_run/")
    return cfg_path


# ── Step 4: Run HADDOCK3 via WSL ──────────────────────────────────────────────

def run_haddock3_wsl(cfg_path, work_dir):
    """Execute HADDOCK3 through WSL."""
    wsl_cfg = str(cfg_path).replace("D:\\", "/mnt/d/").replace("\\", "/")
    wsl_work = str(work_dir).replace("D:\\", "/mnt/d/").replace("\\", "/")

    cmd = f"cd {wsl_work} && haddock3 {wsl_cfg}"
    print(f"\n  Running HADDOCK3 in WSL...")
    print(f"  Command: {cmd}")
    print(f"  (This may take 10-30 minutes depending on sampling size)")

    t0 = time.time()
    result = subprocess.run(
        ["wsl", "-d", "Ubuntu-22.04", "--", "bash", "-c", cmd],
        capture_output=True, text=True, timeout=3600,
    )

    elapsed = time.time() - t0
    print(f"  HADDOCK3 completed in {elapsed:.0f}s")

    if result.returncode != 0:
        print(f"  STDERR (last 500 chars):\n{result.stderr[-500:]}")
        return False, elapsed

    # Check output
    print(f"  STDOUT (last 300 chars):\n{result.stdout[-300:]}")
    return True, elapsed


# ── Step 5: Collect refined structures ────────────────────────────────────────

def collect_refined_pdbs(run_dir, top_n=4):
    """Collect top-N refined PDB structures from HADDOCK3 output."""
    pdbs = []

    # Look for emref or flexref output
    for stage_name in ["emref", "flexref", "rigidbody"]:
        for d in sorted(run_dir.iterdir()):
            if d.is_dir() and stage_name in d.name:
                pdb_files = sorted(d.glob("*.pdb"), key=lambda p: p.name)
                if pdb_files:
                    print(f"  Found {len(pdb_files)} PDBs in {d.name}")
                    pdbs.extend(pdb_files[:top_n])
                    break
        if pdbs:
            break

    if not pdbs:
        print("  WARNING: No refined PDBs found, checking all directories...")
        for d in sorted(run_dir.iterdir()):
            if d.is_dir():
                pdb_files = list(d.glob("*.pdb"))
                if pdb_files:
                    print(f"  {d.name}: {len(pdb_files)} PDBs")

    return pdbs[:top_n]


# ── Step 6: Multi-structure ΔΔG comparison ────────────────────────────────────

def run_ddg_scan(pdb_path, label, mutations, out_results):
    """Run EvoEF2 + MM/GBSA on a single structure for a mutation list."""
    from core.structure.affinity_energy_toolkit import AffinityEnergyToolkit

    try:
        tk = AffinityEnergyToolkit(str(pdb_path), ab_chains=AB_CHAINS, ag_chains=AG_CHAINS)
    except Exception as e:
        print(f"  ERROR initializing toolkit for {label}: {e}")
        return

    # EvoEF2 WT baseline
    r_wt = tk.run_evoef2([])
    evoef2_wt = r_wt["dg"] if r_wt["error"] is None else None

    # MM/GBSA WT baseline
    r_wt_mm = tk.run_mmgbsa([], minimization_steps=200)
    mmgbsa_wt = r_wt_mm["dg"] if r_wt_mm["error"] is None else None

    print(f"  {label} WT: EvoEF2 dG={evoef2_wt}, MM/GBSA dG={mmgbsa_wt}")

    for mut in mutations:
        mutation = [mut]
        mut_label = f"{mut['chain']}{mut['resi']}{mut['wt']}>{mut['mut']}"

        r_evo = tk.run_evoef2(mutation, wt_dg=evoef2_wt)
        r_mm = tk.run_mmgbsa(mutation, wt_dg=mmgbsa_wt, minimization_steps=200)

        out_results.append({
            "structure": label,
            "mutation": mut_label,
            "evoef2_ddg": r_evo["ddg"],
            "evoef2_err": r_evo["error"],
            "mmgbsa_ddg": r_mm["ddg"],
            "mmgbsa_err": r_mm["error"],
        })
        e_str = f"{r_evo['ddg']:+.3f}" if r_evo["ddg"] is not None else "ERR"
        m_str = f"{r_mm['ddg']:+.3f}" if r_mm["ddg"] is not None else "ERR"
        print(f"    {mut_label}: EvoEF2={e_str}  MM/GBSA={m_str}")


# ── Main Pipeline ─────────────────────────────────────────────────────────────

def main():
    print("=" * 70)
    print("PAG1 HADDOCK3 Refinement + Multi-Structure ΔΔG Pipeline")
    print("=" * 70)

    # Step 1: Split PDB
    print("\n[Step 1] Splitting AF2 complex PDB...")
    chain_files = split_pdb(AF2_PDB, WORK_DIR)

    # Step 2: Generate AIRs
    print("\n[Step 2] Generating HADDOCK3 AIR restraints...")
    air_tbl = generate_air_tbl(
        WORK_DIR / "ambig_restraints.tbl",
        active_ab=VH_CDR_ACTIVE,
        passive_ab=VH_CDR_PASSIVE,
        active_ag=AG_ACTIVE,
        passive_ag=AG_PASSIVE,
    )

    # Step 3: Generate HADDOCK3 config
    print("\n[Step 3] Generating HADDOCK3 configuration...")
    cfg = generate_haddock3_cfg(
        WORK_DIR,
        chain_files["AB"],
        chain_files["C"],
        air_tbl,
        n_models=20,
    )

    # Step 4: Run HADDOCK3
    print("\n[Step 4] Running HADDOCK3 via WSL...")
    run_dir = WORK_DIR / "haddock3_run"
    if run_dir.exists():
        print(f"  Removing previous run dir: {run_dir}")
        shutil.rmtree(run_dir)

    ok, elapsed = run_haddock3_wsl(cfg, WORK_DIR)

    if not ok:
        print("\n  HADDOCK3 failed. Check logs above.")
        print("  Attempting to proceed with any partial output...")

    # Step 5: Collect refined structures
    print("\n[Step 5] Collecting refined structures...")
    if run_dir.exists():
        haddock_pdbs = collect_refined_pdbs(run_dir, top_n=4)
        print(f"  Collected {len(haddock_pdbs)} refined PDBs")
    else:
        haddock_pdbs = []
        print("  No HADDOCK3 output found")

    # Step 6: Multi-structure ΔΔG scan
    print("\n[Step 6] Multi-structure ΔΔG scan...")

    KEY_MUTATIONS = [
        {"chain": "A", "resi": 99,  "wt": "Y", "mut": "A"},  # Y99A: top EvoEF2+MM/GBSA
        {"chain": "A", "resi": 99,  "wt": "Y", "mut": "W"},  # Y99W: EvoEF2-MM/GBSA discordant
        {"chain": "A", "resi": 100, "wt": "K", "mut": "R"},  # K100R: charge mutation
        {"chain": "A", "resi": 100, "wt": "K", "mut": "E"},  # K100E: charge reversal
        {"chain": "A", "resi": 101, "wt": "Y", "mut": "A"},  # Y101A: large EvoEF2 signal
        {"chain": "A", "resi": 101, "wt": "Y", "mut": "F"},  # Y101F: discordant
        {"chain": "A", "resi": 52,  "wt": "Y", "mut": "A"},  # Y52A: CDR2 extreme EvoEF2
        {"chain": "A", "resi": 50,  "wt": "Y", "mut": "A"},  # Y50A: CDR2
    ]

    all_results = []

    # AF2 structure (rank_001)
    print(f"\n  --- AF2 rank_001 (original) ---")
    run_ddg_scan(AF2_PDB, "AF2_rank001", KEY_MUTATIONS, all_results)

    # AF2 other ranks
    af2_dir = AF2_PDB.parent
    for rank in [2, 3]:
        rank_pdbs = list(af2_dir.glob(f"*_unrelaxed_rank_{rank:03d}_*.pdb"))
        if rank_pdbs:
            print(f"\n  --- AF2 rank_{rank:03d} ---")
            run_ddg_scan(rank_pdbs[0], f"AF2_rank{rank:03d}", KEY_MUTATIONS, all_results)

    # HADDOCK3 refined structures
    for i, hpdb in enumerate(haddock_pdbs):
        print(f"\n  --- HADDOCK3 model {i+1} ({hpdb.name}) ---")
        run_ddg_scan(hpdb, f"HADDOCK3_{i+1}", KEY_MUTATIONS, all_results)

    # Step 7: Save and report
    print("\n[Step 7] Generating comparison report...")

    out_json = WORK_DIR / "multi_structure_ddg_comparison.json"
    with open(out_json, "w") as f:
        json.dump({
            "mutations": [
                f"{m['chain']}{m['resi']}{m['wt']}>{m['mut']}" for m in KEY_MUTATIONS
            ],
            "structures": {
                "AF2": str(AF2_PDB),
                "HADDOCK3_pdbs": [str(p) for p in haddock_pdbs],
            },
            "results": all_results,
        }, f, indent=2)

    print(f"\n  Results saved: {out_json}")

    # Print comparison table
    print(f"\n{'='*80}")
    print("MULTI-STRUCTURE ΔΔG COMPARISON TABLE")
    print(f"{'='*80}")
    print(f"{'Mutation':<12} {'Structure':<18} {'EvoEF2':>10} {'MM/GBSA':>10} {'Consistent':>12}")
    print("-" * 62)

    for r in all_results:
        e = r["evoef2_ddg"]
        m = r["mmgbsa_ddg"]
        e_str = f"{e:+.3f}" if e is not None else "ERR"
        m_str = f"{m:+.3f}" if m is not None else "ERR"
        if e is not None and m is not None:
            consistent = "YES" if (e > 0 and m > 0) or (e < 0 and m < 0) or (abs(e) < 0.5 and abs(m) < 1.0) else "NO"
        else:
            consistent = "?"
        print(f"{r['mutation']:<12} {r['structure']:<18} {e_str:>10} {m_str:>10} {consistent:>12}")

    print(f"\n{'='*80}")
    print("Consensus: mutations with consistent direction across ≥2 structures")
    print("are the most reliable affinity maturation candidates.")
    print(f"{'='*80}")


if __name__ == "__main__":
    main()
