import sys, json
sys.path.insert(0, '.')
from core.cmc.igg_hpr_ablang import compute_igg_cmc_hpr_ablang

variants = {
    "Murine_Parent": ("QVQLQQPGAELVKPGASVKMSCKASGYTFTSYAMSWVKQTPGQGLEWMGAINPSGGSTYFQKFKGKATLTADESSSTAYMQLSSLTSEDSAVYYCARNYYGSSTYYWGAGTTVTVSS", "QIVLSQSPAILSASPGEKVTMTCRASSSVSYIHWFQQKPGSSPKPWIYATSNLASGVPARFSGSGSGTDFTLTISSVQAEDIADYYCQQWTSNPPTFGGGTKLEIK"),
    "DEEP-FR": ("QVQLVQSGAEVKKPGASVKVSCKASGYTFTSYAMSWVRQAPGQRLEWMGAINPSGGSTYFQKFKGRVTITRDTSASTAYMELSSLRSEDTAVYYCARNYYGSSTYYWGQGTLVTVSS", "DIQMTQSPSSLSASVGDRVTITCRASSSVSYIHWFQQKPGKAPKPLIYATSNLASGVPSRFSGSGSGTDFTLTISSLQPEDFATYYCQQWTSNPPTFGQGTKVEIK"),
    "9AA-CTX": ("QVQLQQPGAELVKPGASVKVSCKASGYTFTSYAMSWVRQAPGQGLEWMGAINPSGGSTYFQKFKGKATLTADTSASTAYMELSSLTSEDTAVYYCARNYYGSSTYYWGQGTTVTVSS", "QIVLTQSPAILSASPGEKVTMTCRASSSVSYIHWFQQKPGSSPKPWIYATSNLASGVPARFSGSGSGTDFTLTISSVQAEDFATYYCQQWTSNPPTFGGGTKLEIK")
}

print("| Variant | AbLang Score |")
print("|---|---|")
for name, (vh, vl) in variants.items():
    try:
        res = compute_igg_cmc_hpr_ablang(vh, vl)
        score = res.get('ablang_score')
        print(f"| {name} | {score} |")
    except Exception as e:
        print(f"| {name} | Error: {e} |")
