"""
scrape_platform_guides.py
==========================
Scrapes submission platform (system-level) documentation pages using Playwright.

Each major submission system publishes platform-wide author guides covering:
  - File format requirements (across ALL journals on the platform)
  - Upload order and step-by-step submission flow
  - Account setup requirements
  - Common errors and how to fix them

Output: assets/submission_system_guides/{system_key}.json

Usage:
  python scripts/scrape_platform_guides.py [--system ScholarOne] [--dry-run]

  --system S   Only scrape one system (key from PLATFORM_TARGETS)
  --dry-run    Print extracted content without writing files
  --no-headless  Show browser window
"""

from __future__ import annotations

import argparse
import asyncio
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

SKILL_DIR    = Path(__file__).resolve().parents[1]
OUTPUT_DIR   = SKILL_DIR / "assets" / "submission_system_guides"

try:
    from playwright.async_api import async_playwright, Page, TimeoutError as PWTimeout
except ImportError:
    print("Install: pip install playwright && playwright install chromium", file=sys.stderr)
    sys.exit(1)


# ── Platform scrape targets ────────────────────────────────────────────────────

PLATFORM_TARGETS: dict[str, dict] = {

    "ScholarOne": {
        "urls": [
            "https://clarivate.com/products/scholarly-and-academic-research/research-publishing-solutions/scholarone/authors/",
            "https://support.clarivate.com/ScholarOne/s/",
        ],
        "fallback_content": {
            "description": "ScholarOne Manuscripts (formerly Manuscript Central) by Clarivate. "
                           "The most widely used manuscript submission system, used by Nature Portfolio, "
                           "Wiley, Oxford University Press, IEEE, Taylor & Francis, and SAGE.",
            "step_by_step": [
                "1. Create account at manuscriptcentral.com for your target journal",
                "2. Click 'Author Center' then 'Submit a New Manuscript'",
                "3. Select manuscript type (Article, Review, Letter, etc.)",
                "4. Enter title, abstract, and keywords",
                "5. Upload main document (anonymised — no author info)",
                "6. Upload Title Page as SEPARATE file",
                "7. Upload each figure as a separate file (FigN.tif naming)",
                "8. Upload supplementary files if applicable",
                "9. Enter suggested and opposed reviewers in 'Peer Review Preferences'",
                "10. Paste cover letter in the text box (do not upload as file)",
                "11. Review PDF proof generated by system",
                "12. Click 'Submit' — system will confirm receipt by email",
            ],
            "common_errors": [
                "Author names in manuscript body → system flags anonymity violation",
                "Title page not separate → editors see author info during review",
                "Figure naming with spaces or version numbers → causes processing errors",
                "Cover letter uploaded as PDF → system may not display it to editors",
                "ORCID not linked → author cannot receive credit for review",
            ],
            "file_requirements": {
                "main_document": "Word (.docx) or PDF; anonymised",
                "title_page": "Separate Word or PDF with all author info",
                "figures": "TIFF (300+ dpi), EPS, or PDF; named Fig1.tif, Fig2.tif ...",
                "supplementary": "Any format; labelled 'Supplementary Material N'",
                "max_file_size_mb": 50,
            },
        },
    },

    "Editorial Manager": {
        "urls": [
            "https://www.ariessys.com/views-and-press/resources/author-tutorial/",
            "https://www.editorialmanager.com/homepage/home.htm",
        ],
        "fallback_content": {
            "description": "Editorial Manager (EM) by Aries Systems. The second most widely used "
                           "system. Used by Springer, most Elsevier journals, Lippincott/Wolters Kluwer, "
                           "and many society publishers.",
            "step_by_step": [
                "1. Go to the journal's EM URL (format: journalname.editorialmanager.com)",
                "2. Register or log in with your EM account",
                "3. Click 'Submit New Manuscript' in the Author Main Menu",
                "4. Select article type",
                "5. Enter title, abstract, keywords, and author details (all co-authors need EM accounts)",
                "6. Paste COVER LETTER in the text box — do NOT upload as a file",
                "7. Upload manuscript file (Word preferred; LaTeX as ZIP with all dependencies)",
                "8. Upload each FIGURE as a separate file",
                "9. Upload tables, supplementary materials",
                "10. EM builds a PDF proof automatically — review it before submitting",
                "11. Accept terms and submit — you will receive a submission number",
            ],
            "common_errors": [
                "Cover letter uploaded as file instead of pasted → editors may not see it",
                "LaTeX without figures/bibliography in ZIP → system cannot compile",
                "Figure files > 10MB → system rejects upload",
                "Co-authors without EM accounts → submission blocked",
                "Track changes not accepted → shows markup in proof PDF",
            ],
            "file_requirements": {
                "main_document": "Word (.docx) preferred; LaTeX as ZIP",
                "cover_letter":  "Paste into EM text box (not a file upload)",
                "figures": "TIFF, EPS, JPEG, or PDF; each < 10MB; named Fig 1, Fig 2 ...",
                "supplementary": "Any format",
                "max_file_size_mb": 10,  # per figure
            },
            "elsevier_extras": {
                "highlights": "Required for all Elsevier journals: 3–5 bullets, ≤ 85 characters each",
                "graphical_abstract": "Recommended: 1 image, width 531 px",
                "credit_roles": "Author contribution (CRediT taxonomy) required",
            },
        },
    },

    "eJournalPress": {
        "urls": [
            "https://www.ejpress.org/authors.html",
            "https://pubs.acs.org/page/4authors/submission/index.html",
        ],
        "fallback_content": {
            "description": "eJournalPress (EJP) used by American Chemical Society (ACS), "
                           "American Society for Microbiology (ASM), and ASBMB journals.",
            "step_by_step": [
                "1. Create account at ejpress.org or pubs.acs.org (ACS Paragon Plus)",
                "2. Select your target journal",
                "3. Choose manuscript type",
                "4. Upload manuscript (Word or LaTeX)",
                "5. Upload cover letter as separate PDF",
                "6. Upload figures: TIFF at 600 dpi (halftone) or 1200 dpi (line art)",
                "7. Upload supporting information as single PDF (SI.pdf) or individual files",
                "8. Enter author information and ORCID",
                "9. Review composite PDF",
                "10. Submit — receive manuscript ID",
            ],
            "common_errors": [
                "Figure resolution < 600 dpi → system warns; editors may request re-upload",
                "SI uploaded as multiple unlabelled files → confuses editors",
                "Wrong journal template → formatting inconsistencies",
            ],
            "file_requirements": {
                "main_document":  "Word (.docx) or LaTeX",
                "cover_letter":   "Upload as separate PDF",
                "figures": "TIFF (600+ dpi halftone, 1200+ dpi line art) or EPS",
                "supporting_info": "Single PDF preferred (SI.pdf)",
                "max_file_size_mb": 20,
            },
        },
    },

    "Frontiers": {
        "urls": [
            "https://www.frontiersin.org/guidelines/author-guidelines",
        ],
        "fallback_content": {
            "description": "Frontiers in-house submission system used for all Frontiers Media journals. "
                           "Unique features: open collaborative review (no anonymous review), "
                           "mandatory ORCIDs, strict word limits enforced by system.",
            "step_by_step": [
                "1. Create or log in to your Frontiers/Loop account (loop.frontiersin.org)",
                "2. Click 'Submit' on your target journal page",
                "3. Select the exact article type (Original Research, Review, Mini Review, etc.)",
                "4. Enter title, abstract (structured format), and 5–8 keywords",
                "5. Add all co-authors — ORCID is MANDATORY for each author",
                "6. Specify specialty section (determines editorial board)",
                "7. Upload manuscript (Word or LaTeX) — DO NOT anonymise",
                "8. Upload figures (TIFF or EPS, ≥ 300 dpi)",
                "9. Complete ethics and data availability statements",
                "10. System checks word limits before allowing submission",
                "11. Submit — reviewers are invited; all review is open and signed",
            ],
            "common_errors": [
                "Missing ORCIDs → submission blocked for any author without ORCID",
                "Anonymised manuscript → against policy; author names required throughout",
                "Word count exceeded → system blocks submission until reduced",
                "Wrong specialty section → manuscript transferred to different editors",
                "Unsigned review response → Frontiers requires all review to be public",
            ],
            "file_requirements": {
                "main_document": "Word (.docx) or LaTeX — NOT anonymised",
                "figures": "TIFF (≥ 300 dpi), EPS, or PNG",
                "cover_letter": "Not required (open review eliminates need)",
                "max_file_size_mb": 30,
            },
            "review_model": "Open collaborative review — reviewers and authors interact openly; "
                            "all reviews published alongside the article.",
        },
    },

    "Snapp": {
        "urls": [
            "https://www.nature.com/authors/author-resources",
            "https://www.nature.com/nature/for-authors",
        ],
        "fallback_content": {
            "description": "Snapp (also called NPG or mts-nature) is Springer Nature's proprietary "
                           "submission system for Nature-branded journals. Separate from ScholarOne "
                           "used by other Springer journals.",
            "step_by_step": [
                "1. Create a nature.com account (distinct from ScholarOne)",
                "2. Navigate to mts-[journal].nature.com",
                "3. Click 'Submit Manuscript'",
                "4. Select manuscript type",
                "5. Enter title, abstract, and author information",
                "6. Paste COVER LETTER in text box — do NOT upload as file",
                "7. Upload main manuscript (Word file preferred; figures embedded AND uploaded separately)",
                "8. Upload each figure as separate high-res file (PDF or TIFF ≥ 600 dpi)",
                "9. Complete the Reporting Summary (mandatory for life sciences papers)",
                "10. Upload Extended Data separately (counts toward figure limit)",
                "11. Upload Supplementary Information as single file if possible",
                "12. Declare all competing interests (all authors, including 'none')",
                "13. Add Data Availability and Code Availability statements",
                "14. Submit",
            ],
            "common_errors": [
                "No Reporting Summary → system flags as incomplete for life sciences submissions",
                "Missing Data Availability statement → required for all Nature journals",
                "Cover letter uploaded as file → editors prefer text box entry",
                "Extended Data not separated from main figures → exceeds figure limit",
                "Competing interests missing for any co-author → submission flagged",
            ],
            "file_requirements": {
                "main_document": "Word (.docx) with figures embedded (also upload separately)",
                "figures": "PDF or TIFF ≥ 600 dpi; named Figure 1, Figure 2 ...",
                "reporting_summary": "Mandatory — download from Nature website for your study type",
                "extended_data": "Separate from main figures; same format requirements",
                "supplementary": "Single PDF preferred",
                "cover_letter": "Paste in text box — NOT uploaded as file",
                "max_file_size_mb": 30,
            },
        },
    },

    "ScienceSubmit": {
        "urls": [
            "https://www.science.org/content/page/science-information-authors",
        ],
        "fallback_content": {
            "description": "Science family submission system used for Science, Science Advances, "
                           "Science Translational Medicine, Science Immunology, Science Signaling, "
                           "and Science Robotics (AAAS).",
            "step_by_step": [
                "1. Create account at submit2.science.org",
                "2. Select target journal and manuscript type",
                "3. Upload manuscript as a SINGLE PDF for initial review "
                   "(figures + legends embedded)",
                "4. Enter structured abstract (≤ 125 words, one paragraph)",
                "5. Enter Impact Statement (one sentence, ≤ 100 characters) — editorial assessment only",
                "6. Upload Supplementary Materials as a single PDF",
                "7. Upload each figure as separate high-res TIFF for production",
                "8. Add all author information and ORCID",
                "9. Declare all conflicts of interest",
                "10. Submit — you receive a manuscript ID",
                "11. For revisions: address all reviewer comments in a separate response document",
            ],
            "common_errors": [
                "Main manuscript not a single PDF → Science requires PDF for initial review",
                "Abstract > 125 words → system flags on submission",
                "Missing Impact Statement → required field",
                "Supplementary as multiple files → should be single PDF labelled 'Supplementary Materials'",
                "Figure legends not in main PDF → editors need legends for review",
            ],
            "file_requirements": {
                "main_document": "Single PDF (MS + figure legends + references embedded)",
                "figures": "High-res TIFF for production; also embedded in submission PDF",
                "supplementary": "Single PDF labelled 'Supplementary Materials'",
                "cover_letter": "Enter in text box on submission form",
                "max_file_size_mb": 25,
            },
        },
    },

    "BMJSubmission": {
        "urls": [
            "https://authors.bmj.com/",
            "https://www.bmj.com/authors",
        ],
        "fallback_content": {
            "description": "BMJ Publishing Group submission system for The BMJ, BMJ Open, "
                           "Heart, Gut, Thorax, and other BMJ journals.",
            "step_by_step": [
                "1. Register or log in at submit.bmj.com (or journal-specific URL)",
                "2. Select article type",
                "3. Enter patient or public involvement (PPI) declaration — required for BMJ",
                "4. Upload manuscript (Word preferred)",
                "5. Upload figures and tables",
                "6. Enter contributor statement (CRediT taxonomy)",
                "7. Declare competing interests — BMJ uses a standardised form",
                "8. Enter data sharing statement",
                "9. Add trial registration number if applicable",
                "10. Review PDF proof",
                "11. Submit",
            ],
            "common_errors": [
                "Missing PPI statement → The BMJ requires patient/public involvement declaration",
                "Missing contributor statement → all authors must have specific contributions listed",
                "No trial registration → randomised trials must be registered before first patient enrolled",
                "Competing interests incomplete → BMJ uses detailed structured form",
            ],
            "file_requirements": {
                "main_document": "Word (.docx)",
                "figures": "TIFF or EPS (300+ dpi)",
                "ppi_statement": "Required for The BMJ — patient/public involvement description",
                "max_file_size_mb": 20,
            },
        },
    },
}


# ── Scraper ────────────────────────────────────────────────────────────────────

async def scrape_platform(page: Page, system_key: str, target: dict) -> dict:
    """Attempt to scrape live documentation, fall back to built-in content."""
    scraped_text = ""

    for url in target.get("urls", []):
        try:
            await page.goto(url, timeout=20000, wait_until="domcontentloaded")
            await page.wait_for_timeout(2000)

            # Dismiss cookie banners
            for sel in ["button:has-text('Accept')", "button:has-text('Accept all')",
                        "#onetrust-accept-btn-handler", ".cookie-accept"]:
                try:
                    btn = page.locator(sel).first
                    if await btn.is_visible():
                        await btn.click()
                        await page.wait_for_timeout(500)
                except Exception:
                    pass

            text = await page.evaluate("() => document.body.innerText")
            if len(text) > 500:
                scraped_text += "\n\n" + text[:8000]
                break
        except Exception:
            continue

    # Build output: start with fallback, enhance with scraped text if available
    content = dict(target.get("fallback_content", {}))
    content["system_key"]   = system_key
    content["scraped_text"] = scraped_text[:4000] if scraped_text else ""
    content["scraped_at"]   = datetime.now(timezone.utc).isoformat()
    content["source_urls"]  = target.get("urls", [])

    # Extract additional details from scraped text
    if scraped_text:
        # Try to find file size limits mentioned on the page
        size_m = re.search(r"(\d+)\s*MB\s+(?:file\s+size|maximum|limit|per\s+file)",
                           scraped_text, re.IGNORECASE)
        if size_m:
            content.setdefault("file_requirements", {})["max_file_size_mb"] = int(size_m.group(1))

    return content


async def run(
    output_dir: Path,
    systems: list[str] | None = None,
    headless: bool = True,
    dry_run: bool = False,
) -> dict:
    output_dir.mkdir(parents=True, exist_ok=True)
    targets = {k: v for k, v in PLATFORM_TARGETS.items()
               if not systems or k in systems}

    results = {}
    async with async_playwright() as pw:
        browser = await pw.chromium.launch(headless=headless)
        ctx     = await browser.new_context(
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/120.0.0.0 Safari/537.36"
            )
        )
        page = await ctx.new_page()

        for key, target in targets.items():
            print(f"  {key} ...", end=" ", flush=True)
            content = await scrape_platform(page, key, target)
            results[key] = content

            if not dry_run:
                out_file = output_dir / f"{key.lower().replace(' ', '_')}.json"
                out_file.write_text(
                    json.dumps(content, indent=2, ensure_ascii=False), encoding="utf-8"
                )
                print(f"✓ → {out_file.name}")
            else:
                print("✓ (dry run)")

        await browser.close()

    # Write index
    if not dry_run:
        index = {
            k: {
                "key":         k,
                "description": v.get("description", "")[:120],
                "source_urls": v.get("source_urls", []),
                "scraped_at":  v.get("scraped_at", ""),
            }
            for k, v in results.items()
        }
        (output_dir / "_index.json").write_text(
            json.dumps(index, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        print(f"\n  Index written: {output_dir / '_index.json'}")

    return results


def main():
    parser = argparse.ArgumentParser(description="Submission platform guide scraper")
    parser.add_argument("--system",    nargs="+", help="Specific system keys to scrape")
    parser.add_argument("--dry-run",   action="store_true")
    parser.add_argument("--no-headless", action="store_true")
    parser.add_argument("--output-dir", default=str(OUTPUT_DIR))
    args = parser.parse_args()

    print(f"Scraping submission platform guides → {args.output_dir}")
    if args.dry_run:
        print("  DRY RUN")
    print()

    results = asyncio.run(run(
        Path(args.output_dir),
        systems=args.system,
        headless=not args.no_headless,
        dry_run=args.dry_run,
    ))

    print(f"\nDone: {len(results)} platform guides written.")


if __name__ == "__main__":
    main()
