#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
sync_standards_alignment.py — SSOT ↔ registry ↔ generated docs
================================================================
Single source of truth: config/standards_ssot.json

  python scripts/sync_standards_alignment.py              # check + emit (default)
  python scripts/sync_standards_alignment.py --check-only # validate only (exit 1 on drift)
  python scripts/sync_standards_alignment.py --emit-only  # regenerate docs/_generated only

Does NOT auto-edit LOCKED files (e.g. docs/STANDARDS_INDEX.md, abenginecore_registry.json).
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Tuple

_SUITE_ROOT = Path(__file__).resolve().parents[1]

SSOT_PATH = _SUITE_ROOT / "config" / "standards_ssot.json"
REGISTRY_PATH = _SUITE_ROOT / "config" / "abenginecore_registry.json"
GEN_DIR = _SUITE_ROOT / "docs" / "_generated"
GEN_TABLE = GEN_DIR / "standards_alignment_table.md"


def _norm(p: str) -> str:
    return Path(p).as_posix().strip()


def load_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def check_alignment() -> Tuple[bool, List[str]]:
    ok = True
    lines: List[str] = []
    ssot = load_json(SSOT_PATH)
    reg = load_json(REGISTRY_PATH)
    prm: Dict[str, Any] = reg.get("pipeline_release_matrix") or {}

    for row in ssot.get("standards") or []:
        key = row.get("registry_pipeline_key")
        if not key:
            lines.append(f"[SKIP] {row.get('id')}: no registry_pipeline_key")
            continue
        if key not in prm:
            ok = False
            lines.append(f"[FAIL] registry missing pipeline_release_matrix['{key}']")
            continue

        pipe = prm[key]
        v_ssot = str(row.get("version") or "").strip()
        v_reg = str(pipe.get("version_label") or "").strip()
        if v_ssot != v_reg:
            ok = False
            lines.append(
                f"[FAIL] {key}: version SSOT={v_ssot!r} registry={v_reg!r}"
            )

        sf_ssot = _norm(str(row.get("standard_file") or ""))
        sf_reg = _norm(str(pipe.get("standard_file") or ""))
        if sf_ssot != sf_reg:
            ok = False
            lines.append(
                f"[FAIL] {key}: standard_file SSOT={sf_ssot!r} registry={sf_reg!r}"
            )

        cfg_ssot = [_norm(x) for x in (row.get("config_files") or [])]
        cfg_reg_raw = str(pipe.get("config_execution") or "").strip()

        def _registry_config_is_simple_path(s: str) -> bool:
            t = s.strip()
            return bool(t) and t.endswith(".json") and not any(
                x in t for x in ("（", "", "mask", "", "")
            )

        if cfg_ssot:
            if _registry_config_is_simple_path(cfg_reg_raw):
                cr = _norm(cfg_reg_raw)
                if cr not in cfg_ssot:
                    ok = False
                    lines.append(
                        f"[FAIL] {key}: config SSOT expects {cfg_ssot!r} registry has {cr!r}"
                    )
            else:
                lines.append(
                    f"[INFO] {key}: registry config_execution not a single .json path; "
                    f"skipped strict match (SSOT config_files={cfg_ssot})"
                )
        else:
            lines.append(f"[INFO] {key}: SSOT config_files empty — registry config not enforced")

        rid_ssot = str(row.get("release_id") or "").strip()
        rid_reg = str(pipe.get("release_id") or "").strip()
        if rid_ssot and rid_reg and rid_ssot != rid_reg:
            ok = False
            lines.append(
                f"[FAIL] {key}: release_id SSOT={rid_ssot!r} registry={rid_reg!r}"
            )

    return ok, lines


def emit_generated(ssot: Dict[str, Any]) -> None:
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    meta = ssot.get("_meta") or {}
    rows = ssot.get("standards") or []
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = [
        "<!-- AUTO-GENERATED by scripts/sync_standards_alignment.py — do not edit by hand -->",
        "",
        "# Standards alignment table (SSOT)",
        "",
        f"- **Generated:** {now}",
        f"- **SSOT:** `config/standards_ssot.json` (schema {meta.get('schema_version', '?')})",
        f"- **Registry cross-check:** `config/abenginecore_registry.json` → `pipeline_release_matrix`",
        "",
        "| id | version | standard_file | config_files (SSOT) | registry key |",
        "|----|---------|---------------|---------------------|--------------|",
    ]
    for r in rows:
        cid = r.get("id", "")
        ver = r.get("version", "")
        sf = r.get("standard_file", "")
        cf = ", ".join(r.get("config_files") or []) or "—"
        rk = r.get("registry_pipeline_key", "")
        lines.append(f"| `{cid}` | {ver} | `{sf}` | {cf} | `{rk}` |")

    lines.extend(
        [
            "",
            "## Maintainer workflow",
            "",
            "1. Edit **`config/standards_ssot.json`** (version, paths, release_id).",
            "2. Run `python scripts/sync_standards_alignment.py`.",
            "3. If FAIL: update **`config/abenginecore_registry.json`** `pipeline_release_matrix` to match SSOT (or update SSOT — governance decides).",
            "4. Update **`docs/STANDARDS_INDEX.md`** and LOCKED standard files **only with owner approval**.",
            "",
        ]
    )
    GEN_TABLE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Align standards SSOT with registry and emit generated docs")
    ap.add_argument(
        "--check-only",
        action="store_true",
        help="Validate only; do not write docs/_generated",
    )
    ap.add_argument(
        "--emit-only",
        action="store_true",
        help="Only regenerate docs/_generated/standards_alignment_table.md",
    )
    args = ap.parse_args()
    if args.check_only and args.emit_only:
        print("Cannot use both --check-only and --emit-only", file=sys.stderr)
        return 2

    do_check = not args.emit_only
    do_emit = not args.check_only

    if not SSOT_PATH.is_file():
        print(f"[FATAL] Missing {SSOT_PATH}", file=sys.stderr)
        return 2

    ssot = load_json(SSOT_PATH)

    if do_check:
        ok, report = check_alignment()
        print("=== SSOT alignment check ===\n")
        for line in report:
            print(line)
        print("\n=== result ===")
        if ok:
            print("PASS — SSOT matches registry pipeline_release_matrix for checked fields.")
        else:
            print("FAIL — fix SSOT and/or registry, then re-run.")
        if not ok:
            return 1

    if do_emit:
        emit_generated(ssot)
        print(f"[emit] Wrote {GEN_TABLE.relative_to(_SUITE_ROOT)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
