#!/usr/bin/env python3
"""Generate all 20 template JSON files into templates/ directory."""
import json
from pathlib import Path

BASE = Path(__file__).parent

TEMPLATES = [
    # ---- PPT (8 templates) ----
    {
        "template_id": "ppt_tech_blue",
        "name_zh": "科技蓝",
        "style": "tech",
        "doc_types": ["ppt"],
        "description": "深蓝渐变背景，现代科技感，适合 AI/SaaS/数字化产品发布",
        "preview_url": None,
        "colors": {"primary": "#0a1628", "accent": "#3b82f6", "text": "#f8fafc", "surface": "#1e3a5f"},
        "fonts": {"heading": "思源黑体", "body": "思源黑体"},
        "slide_aspect": "16:9",
        "layouts_available": ["title_hero", "text_left_image_right", "bullets_3col", "stats_banner", "closing"],
    },
    {
        "template_id": "ppt_minimal_white",
        "name_zh": "极简白",
        "style": "minimal",
        "doc_types": ["ppt"],
        "description": "纯白底，细线排版，适合咨询报告、战略规划",
        "preview_url": None,
        "colors": {"primary": "#ffffff", "accent": "#111827", "text": "#111827", "surface": "#f9fafb"},
        "fonts": {"heading": "思源宋体", "body": "思源黑体"},
        "slide_aspect": "16:9",
        "layouts_available": ["title_hero", "text_only", "image_full", "two_column", "quote", "closing"],
    },
    {
        "template_id": "ppt_warm_brand",
        "name_zh": "暖色品牌",
        "style": "warm",
        "doc_types": ["ppt"],
        "description": "橙红渐变，适合消费品、餐饮、零售品牌介绍",
        "preview_url": None,
        "colors": {"primary": "#fff7ed", "accent": "#ea580c", "text": "#1c1917", "surface": "#ffedd5"},
        "fonts": {"heading": "思源黑体", "body": "思源黑体"},
        "slide_aspect": "16:9",
        "layouts_available": ["title_hero", "product_showcase", "testimonial", "closing"],
    },
    {
        "template_id": "ppt_dark_premium",
        "name_zh": "深色高端",
        "style": "premium",
        "doc_types": ["ppt"],
        "description": "黑金配色，适合奢侈品、投资路演、高端服务",
        "preview_url": None,
        "colors": {"primary": "#0c0c0c", "accent": "#d4af37", "text": "#f5f5f0", "surface": "#1a1a1a"},
        "fonts": {"heading": "思源宋体", "body": "思源黑体"},
        "slide_aspect": "16:9",
        "layouts_available": ["title_hero", "two_column", "stats_banner", "quote", "closing"],
    },
    {
        "template_id": "ppt_medical_clean",
        "name_zh": "医疗清洁",
        "style": "medical",
        "doc_types": ["ppt"],
        "description": "浅蓝白色，医疗/药企/健康科技适用",
        "preview_url": None,
        "colors": {"primary": "#f0f9ff", "accent": "#0284c7", "text": "#0f172a", "surface": "#e0f2fe"},
        "fonts": {"heading": "思源黑体", "body": "思源黑体"},
        "slide_aspect": "16:9",
        "layouts_available": ["title_hero", "text_left_image_right", "bullets_3col", "closing"],
    },
    {
        "template_id": "ppt_green_eco",
        "name_zh": "绿色环保",
        "style": "eco",
        "doc_types": ["ppt"],
        "description": "清新绿色，环保/农业/可持续发展主题",
        "preview_url": None,
        "colors": {"primary": "#f0fdf4", "accent": "#16a34a", "text": "#14532d", "surface": "#dcfce7"},
        "fonts": {"heading": "思源黑体", "body": "思源黑体"},
        "slide_aspect": "16:9",
        "layouts_available": ["title_hero", "image_full", "bullets_3col", "closing"],
    },
    {
        "template_id": "ppt_edu_bright",
        "name_zh": "教育明亮",
        "style": "education",
        "doc_types": ["ppt"],
        "description": "活泼多彩，适合教育机构、培训课程、校园宣传",
        "preview_url": None,
        "colors": {"primary": "#fefce8", "accent": "#7c3aed", "text": "#1e1b4b", "surface": "#ede9fe"},
        "fonts": {"heading": "思源黑体", "body": "思源黑体"},
        "slide_aspect": "16:9",
        "layouts_available": ["title_hero", "text_left_image_right", "two_column", "closing"],
    },
    {
        "template_id": "ppt_finance_formal",
        "name_zh": "金融正式",
        "style": "finance",
        "doc_types": ["ppt"],
        "description": "深蓝正式，银行/基金/财务分析适用",
        "preview_url": None,
        "colors": {"primary": "#1e3a5f", "accent": "#c8a84b", "text": "#f8fafc", "surface": "#254d7e"},
        "fonts": {"heading": "思源黑体", "body": "思源黑体"},
        "slide_aspect": "16:9",
        "layouts_available": ["title_hero", "stats_banner", "two_column", "bullets_3col", "closing"],
    },
    # ---- 小红书 XHS (5 templates) ----
    {
        "template_id": "xhs_lifestyle",
        "name_zh": "生活方式",
        "style": "lifestyle",
        "doc_types": ["xiaohongshu"],
        "description": "粉橙渐变卡片，美妆/生活/穿搭博主风格",
        "preview_url": None,
        "colors": {"primary": "#fff0eb", "accent": "#fe2c55", "text": "#1a1a1a", "tag": "#ffd6d6"},
        "card_size": "1:1",
        "font": "思源黑体",
        "layouts_available": ["cover_photo", "info_card", "product_detail", "closing_cta"],
    },
    {
        "template_id": "xhs_foodie",
        "name_zh": "美食探店",
        "style": "food",
        "doc_types": ["xiaohongshu"],
        "description": "暖黄色系，美食博主/餐饮探店/食谱分享",
        "preview_url": None,
        "colors": {"primary": "#fffbeb", "accent": "#d97706", "text": "#1c1917", "tag": "#fef3c7"},
        "card_size": "4:3",
        "font": "思源黑体",
        "layouts_available": ["cover_photo", "info_card", "recipe_steps", "closing_cta"],
    },
    {
        "template_id": "xhs_tech_review",
        "name_zh": "数码测评",
        "style": "tech",
        "doc_types": ["xiaohongshu"],
        "description": "黑白科技风，数码产品开箱/测评/对比",
        "preview_url": None,
        "colors": {"primary": "#18181b", "accent": "#22d3ee", "text": "#f4f4f5", "tag": "#27272a"},
        "card_size": "4:3",
        "font": "思源黑体",
        "layouts_available": ["cover_photo", "specs_grid", "pros_cons", "closing_cta"],
    },
    {
        "template_id": "xhs_travel",
        "name_zh": "旅行打卡",
        "style": "travel",
        "doc_types": ["xiaohongshu"],
        "description": "天蓝系，旅行攻略/景点打卡/民宿分享",
        "preview_url": None,
        "colors": {"primary": "#eff6ff", "accent": "#2563eb", "text": "#1e3a5f", "tag": "#dbeafe"},
        "card_size": "4:3",
        "font": "思源黑体",
        "layouts_available": ["cover_photo", "info_card", "map_notes", "closing_cta"],
    },
    {
        "template_id": "xhs_knowledge",
        "name_zh": "干货知识",
        "style": "knowledge",
        "doc_types": ["xiaohongshu"],
        "description": "黄黑高对比，知识付费/职场技能/副业攻略",
        "preview_url": None,
        "colors": {"primary": "#fef9c3", "accent": "#854d0e", "text": "#1c1917", "tag": "#fde047"},
        "card_size": "4:3",
        "font": "思源黑体",
        "layouts_available": ["cover_photo", "numbered_steps", "info_card", "closing_cta"],
    },
    # ---- 微信公众号 WeChat (4 templates) ----
    {
        "template_id": "wechat_corporate",
        "name_zh": "企业公告",
        "style": "corporate",
        "doc_types": ["wechat"],
        "description": "简洁正式，企业新闻/政策通知/公告推送",
        "preview_url": None,
        "colors": {"primary": "#ffffff", "accent": "#07c160", "text": "#333", "divider": "#e5e5e5"},
        "max_width": 600,
        "font": "思源黑体",
        "layouts_available": ["banner_title", "rich_text", "card_highlight", "cta_button"],
    },
    {
        "template_id": "wechat_brand_story",
        "name_zh": "品牌故事",
        "style": "story",
        "doc_types": ["wechat"],
        "description": "大图排版，品牌内容营销/故事化传播",
        "preview_url": None,
        "colors": {"primary": "#1a1a1a", "accent": "#e11d48", "text": "#f0f0f0", "surface": "#2d2d2d"},
        "max_width": 600,
        "font": "思源宋体",
        "layouts_available": ["full_banner", "text_over_image", "pull_quote", "cta_button"],
    },
    {
        "template_id": "wechat_industry_insight",
        "name_zh": "行业洞察",
        "style": "insight",
        "doc_types": ["wechat"],
        "description": "数据图表配文，研究报告/行业分析/深度评论",
        "preview_url": None,
        "colors": {"primary": "#f8fafc", "accent": "#4f46e5", "text": "#1e293b", "chart_bg": "#e0e7ff"},
        "max_width": 600,
        "font": "思源黑体",
        "layouts_available": ["banner_title", "stats_card", "rich_text", "key_takeaway"],
    },
    {
        "template_id": "wechat_event_promo",
        "name_zh": "活动促销",
        "style": "promo",
        "doc_types": ["wechat"],
        "description": "红色热烈，节日促销/直播预告/限时优惠",
        "preview_url": None,
        "colors": {"primary": "#fff1f2", "accent": "#dc2626", "text": "#450a0a", "highlight": "#fde68a"},
        "max_width": 600,
        "font": "思源黑体",
        "layouts_available": ["countdown_banner", "product_grid", "coupon_card", "cta_button"],
    },
    # ---- 白皮书 Whitepaper (3 templates) ----
    {
        "template_id": "wp_b2b_formal",
        "name_zh": "B2B 正式白皮书",
        "style": "formal",
        "doc_types": ["whitepaper"],
        "description": "严肃专业，企业 B2B 服务/解决方案/技术架构介绍",
        "preview_url": None,
        "colors": {"primary": "#ffffff", "accent": "#1a56db", "text": "#111827", "surface": "#f9fafb"},
        "page_size": "A4",
        "fonts": {"heading": "思源黑体", "body": "思源黑体"},
        "layouts_available": ["cover", "toc", "section_header", "two_column_body", "case_study", "conclusion"],
    },
    {
        "template_id": "wp_startup_pitch",
        "name_zh": "创业路演白皮书",
        "style": "startup",
        "doc_types": ["whitepaper"],
        "description": "活力科技感，初创公司融资/产品白皮书/投资者报告",
        "preview_url": None,
        "colors": {"primary": "#0f0f23", "accent": "#7c3aed", "text": "#e2e8f0", "surface": "#1e1e3f"},
        "page_size": "A4",
        "fonts": {"heading": "思源黑体", "body": "思源黑体"},
        "layouts_available": ["cover", "exec_summary", "problem_solution", "market_size", "team", "conclusion"],
    },
    {
        "template_id": "wp_research_report",
        "name_zh": "研究报告",
        "style": "academic",
        "doc_types": ["whitepaper"],
        "description": "学术严谨风，研究院/咨询公司/政策报告",
        "preview_url": None,
        "colors": {"primary": "#ffffff", "accent": "#7c2d12", "text": "#1c1917", "surface": "#fafaf9"},
        "page_size": "A4",
        "fonts": {"heading": "思源宋体", "body": "思源黑体"},
        "layouts_available": ["cover", "abstract", "toc", "body_text", "data_figure", "conclusion", "references"],
    },
]


def main():
    out_dir = BASE
    written = 0
    for t in TEMPLATES:
        p = out_dir / f"{t['template_id']}.json"
        p.write_text(json.dumps(t, ensure_ascii=False, indent=2), encoding="utf-8")
        written += 1
    print(f"Generated {written} templates in {out_dir}")


if __name__ == "__main__":
    main()
