"""
Step 2: Fetch 106-week paper + check for 'Claude response' contamination in all records.
"""
import re, time, urllib.request, json, csv

def fetch(url, timeout=15):
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'InSynBio-Verify/1.0'})
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.read().decode('utf-8', errors='replace')
    except Exception as e:
        return f"ERROR: {e}"

def pubmed_efetch(pmid):
    url = (f"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"
           f"?db=pubmed&id={pmid}&rettype=abstract&retmode=text"
           f"&tool=InSynBio&email=info@insynbio.com")
    return fetch(url)

ADA_CTX = re.compile(
    r'anti[\-\s]?drug\s*antibod|immunogenicit|\bADA\b|treatment[\-\s]?emerg|'
    r'immunogenic|neutraliz|\bHAHA\b|anti[\-\s]?antibod',
    re.IGNORECASE
)

def extract_ada_sents(text):
    if not text or text.startswith('ERROR'): return []
    sents = re.split(r'(?<=[.!?])\s+', text)
    return [s for s in sents if ADA_CTX.search(s)]

def extract_pcts(sents):
    pcts = []
    for s in sents:
        found = re.findall(r'(\d+\.?\d*)\s*%', s)
        pcts.extend([float(p) for p in found if 0 < float(p) <= 100])
    return sorted(set(pcts))

# ─── 106-week paper ──────────────────────────────────────────────────────────
print("=" * 70)
print("PMID 38955475 — 106-week safety/efficacy paper")
print("=" * 70)
abs_106 = pubmed_efetch('38955475')
time.sleep(0.4)
print(abs_106[:2500])
sents = extract_ada_sents(abs_106)
pcts  = extract_pcts(sents)
print(f"\nADA-context pcts: {pcts}")
print("ADA sentences:")
for s in sents:
    print(f"  → {s[:220]}")

# ─── PMC full text for PMID 36109142 (Ann Rheum Dis 2022) ────────────────────
print()
print("=" * 70)
print("PMC FULL TEXT: PMC9664111 (PMID 36109142) — searching for ADA section")
print("=" * 70)
pmc_txt = fetch('https://pmc.ncbi.nlm.nih.gov/articles/PMC9664111/', timeout=15)
time.sleep(0.5)
if pmc_txt and not pmc_txt.startswith('ERROR'):
    # Find all sentences with ADA context
    sents_pmc = re.split(r'(?<=[.!?])\s+', pmc_txt)
    ada_sents_pmc = [s for s in sents_pmc if ADA_CTX.search(s) and 
                     len(s) > 20 and len(s) < 500][:15]
    pcts_pmc = extract_pcts(ada_sents_pmc)
    print(f"ADA-context pcts from PMC full text: {pcts_pmc}")
    for s in ada_sents_pmc:
        # strip HTML tags
        clean = re.sub(r'<[^>]+>', ' ', s).strip()
        clean = re.sub(r'\s+', ' ', clean)
        if len(clean) > 30:
            print(f"  → {clean[:250]}")
else:
    print(f"  PMC fetch: {str(pmc_txt)[:100]}")

# ─── Check for 'Claude response' contamination across all 138 records ────────
print()
print("=" * 70)
print("CONTAMINATION AUDIT: scanning all 138 records for AI-generated sources")
print("=" * 70)
master = list(csv.DictReader(open('data/ada_master_136_curated.csv', encoding='utf-8')))

contaminated = []
ai_phrases = [
    'claude response', 'claude-generated', 'ai response', 'gpt response',
    'language model', 'chatgpt', 'llm response', 'ai-generated',
    'according to claude', 'from claude', 'per claude',
    'generated by', 'synthesized from',
]

for row in master:
    name   = row.get('antibody_name', '')
    chain  = row.get('ada_evidence_chain_excerpt', '').lower()
    url    = row.get('ada_source_url_primary', '').lower()
    pmids  = row.get('ada_source_pmids', '')
    tier   = row.get('evidence_tier', '')
    
    flags = [phrase for phrase in ai_phrases if phrase in chain]
    if flags:
        contaminated.append({
            'name': name, 'tier': tier, 'flags': flags,
            'url': row.get('ada_source_url_primary','')[:80],
            'pmids': pmids,
            'chain_snippet': row.get('ada_evidence_chain_excerpt','')[:300],
        })

print(f"\nRecords with AI-generated evidence phrases: {len(contaminated)}")
for r in contaminated:
    print(f"\n  ⛔ {r['name']} [Tier {r['tier']}]")
    print(f"     URL:   {r['url']}")
    print(f"     PMIDs: {r['pmids']}")
    print(f"     Flags: {r['flags']}")
    print(f"     Excerpt: {r['chain_snippet'][:200]}")
