import hashlib
from typing import Set

# Demo sequence hashes (SHA256 of the uppercase sequence)
DEMO_SEQUENCE_HASHES: Set[str] = {
    # Rituximab-type pair
    hashlib.sha256(b"QVQLQQSGPELVKPGASLKLSCTASGFNIKDTYIHWVKQRPEQGLEWIGRIYPTNGYTRYDPKFQDKATITADTSSNTAYLQVSRLTSEDTAVYYCSRWGGDGFYAMDYWGQGASVTVSS").hexdigest(),
    hashlib.sha256(b"DIQMTQSPSSLSASVGDRVTITCRASQDVNTAVAWYQQKPGKAPKLLIYSASFLYSGVPSRFSGSGSGTDFTLTISSLQPEDFATYYCQQHYTTPPTFGQGTKVEIK").hexdigest(),
    # Rat Campath
    hashlib.sha256(b"EVKLLESGGGLVQPGGSMRLSCAGSGFTFTDFYMNWIRQPAGKAPEWLGFIRDKAKGYTTEYNPSVKGRFTISRDNTQNMLYLQMNTLRAEDTATYYCAREGHTAAPFDYWGQGVMVTVSS").hexdigest(),
    hashlib.sha256(b"DIKMTQSPSFLSASVGDRVTLNCKASQNIDKYLNWYQQKLGESPKLLIYNTNNLQTGIPSRFSGSGSGTDFTLTISSLQPEDVATYFCLQHISRPRTFGTGTKLELK").hexdigest(),
    # Toripalimab
    hashlib.sha256(b"QGQLVQSGAEVKKPGASVKVSCKASGYTFTDYEMHWVRQAPIHGLEWIGVIESETGGTAYNQKFKGRVTITADKSTSTAYMELSSLRSEDTAVYYCAREGITTVATTYYWYFDVWGQGTTVTVSS").hexdigest(),
    hashlib.sha256(b"DVVMTQSPLSLPVTLGQPASISCRSSQSIVHSNGNTYLEWYLQKPGQSPQLLIYKVSNRFSGVPDRFSGSGSGTDFTLKISRVEAEDVGVYYCFQGSHVPLTFGQGTKLEIK").hexdigest(),
    # Briakinumab
    hashlib.sha256(b"QVQLVESGGGVVQPGRSLRLSCAASGFTFSSYGMHWVRQAPGKGLEWVAFIRYDGSNKYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCKTHGSHDNWGQGTMVTVSS").hexdigest(),
    hashlib.sha256(b"QSVLTQPPSVSGAPGQRVTISCSGSRSNIGSNTVKWYQQLPGTAPKLLIYYNDQRPSGVPDRFSGSKSGTSASLAITGLQAEDEADYYCQSYDRYTHPALLFGTGTKVTVL").hexdigest(),
    # Abiprubart
    hashlib.sha256(b"QVQLVQSGAEVKKPGASVKVSCKASGYTFTNYWMHWVRQAPGQRLEWIGYINPSNDYTKYNQKFKDRATLTADKSANTAYMELSSLRSEDTAVYYCARQGFPYWGQGTLVTVSS").hexdigest(),
    hashlib.sha256(b"EIVLTQSPATLSLSPGERATLSCSASSSVSYMHWYQQKPGQAPRRWIYDTSKLASGVPARFSGSGSGTDYTLTISSLEPEDFAVYYCHQLSSDPFTFGGGTKVEIK").hexdigest(),
    # 7D12 VHH
    hashlib.sha256(b"QVKLEESGGGSVQTGGSLRLTCAASGRTSRSYGMGWFRQAPGKEREFVSGISWRGDSTGYADSVKGRFTISRDNAKNTVDLQMNSLKPEDTAIYYCAAAAGSAWYGTLYEYDYWGQGTQVTVSS").hexdigest(),
    # Envafolimab
    hashlib.sha256(b"EVQLVESGGGLVQPGGSLRLSCAASGFTFSDNYMSWVRQAPGKGLEWVSYISSSGSTIYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCARDRGSNYGDSWGQGTLVTVSS").hexdigest(),
    # Humanized VHH
    hashlib.sha256(b"EVQLVESGGGLVQPGGSLRLSCAASGRTSRSYGMGWFRQAPGKEREFVAGISWRGDSTGYADSVKGRFTISRDNAKNTLYLQMNSLRAEDTAVYYCAAAAGSAWYGTLYEYDYWGQGTLVTVSS").hexdigest(),
    # HER2 binder VH
    hashlib.sha256(b"EVQLVQSGAEVKKPGASVKVSCKASGYTFTSYNMHWVRQAPGQGLEWMGIINPSGGSTSYAQKFQGRVTMTRDTSTSTVYMELSSLRSEDTAVYYCARDQGSIRGFDYWGQGTLVTVSS").hexdigest(),
    # Tislelizumab
    hashlib.sha256(b"QVQLQESGPGLVKPSETLSLTCTVSGFSLTSYGVHWIRQPPGKGLEWIGVIYADGSTNYNPSLKSRVTISKDTSKNQVSLKLSSVTAADTAVYYCARAYGNYWYIDVWGQGTTVTVSS").hexdigest(),
    # Pembrolizumab
    hashlib.sha256(b"QVQLVQSGVEVKKPGASVKVSCKASGYTFTNYYMYWVRQAPGQGLEWMGGINPSNGGTNFNEKFKNRVTLTTDSSTTTAYMELKSLQFDDTAVYYCARRDYRFDMGFDYWGQGTTVTVSS").hexdigest(),
    # Camrelizumab
    hashlib.sha256(b"EVQLVESGGGLVQPGGSLRLSCAASGFTFSSYMMSWVRQAPGKGLEWVASISSSGGSTYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCARVEGYGNSNGMDVWGQGTMVTVSS").hexdigest(),
    # Nivolumab
    hashlib.sha256(b"QVQLVESGGGVVQPGRSLRLDCKASGITFSNSGMHWVRQAPGKGLEWVAVIWYDGSKRYYADSVKGRFTISRDNSKNTLFLQMNSLRAEDTAVYYCATNDDYWGQGTLVTVSS").hexdigest(),
}

def is_demo_sequence(seq: str) -> bool:
    if not seq:
        return False
    # Remove whitespace and normalize to uppercase
    clean_seq = "".join(seq.split()).upper()
    h = hashlib.sha256(clean_seq.encode()).hexdigest()
    return h in DEMO_SEQUENCE_HASHES
